### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by Daegonna** [ObliqueNET/Server#1002]
So i havent been on for days and aperently i got banned again. It states that they talked to me,but that is not true . It said they asked me to read the rules,they didn't. Futher sinds my temporarly ban i hardly left our town cos i was affraid of doing something wrong without knowing. Aperently they think i did something and i dunno what the hell i did same as last time, there was something about afk avoidence, i don't even know how i'm suposingly doing that. Pjlesure said something about togekiss, but dunno why that has anything 2 do with afk avoidence tho

**Comment by Daegonna** [comment]
Hello, don't u think it's about time 2 respond?!?!

**Comment by Katadreme** [comment]
I apologise for the delay in the response, so i'll forgive the tone. 

In regards to your ban, you have broken few server rules, such as using AFK machines and griefing unclaimed bases. You were temporarily banned after your 2nd offence, which was also your final chance. And now you were permanently banned for griefing another unclaimed base. Its hard to argue that you unaware of the server rules, as you would've been told to read them at some point, or you should've read the rules if you were 'afraid of doing something wrong without knowing'. On these grounds, I am declining your appeal.

**Comment by Daegonna** [comment]
I never used AFK machines so that is defently not true. After i got warned and gave stuff back for taking stuff from a unclaimed base. I didn't do that on purpose either. They said i wasn't allowed to take stuff from unclaimed bases so i didn't. I did take some stuff from bases that were already distroyed. Didn't think that was an isseu coz than it is given back to nature right?  And last u r not talking to a kid, but a mom that just wants to play a game with her kid.
