### ISSUE TITLE
/market list not showing gender

### ISSUE THREAD

**Issue by menno516** [ObliqueNET/Server#1005]
when you go use /market list in game  it wont show the gender.

![image](https://user-images.githubusercontent.com/63118334/108075761-043f4900-706b-11eb-830b-75fff57f66fc.png)
![image](https://user-images.githubusercontent.com/63118334/108075811-13be9200-706b-11eb-8a60-e3fa0478f747.png)

**Comment by Hiroku** [comment]
Should be added now
