### ISSUE TITLE
[Trivia] General improvements

### ISSUE THREAD

**Issue by Rasgnarok** [ObliqueNET/Server#1007]
- Add an reward announcement for every correct announcer.
- More questions (base stats, spawn biomes?)
- Leaderboard of players with the most answers

Pulled from #suggestions on our Discord.

**Comment by Hiroku** [comment]
The first of those is now complete pending the next restart, the second is not really meaningful (base stats and spawn biomes are not good trivia questions though I'm open to others), third is still TO-DO

**Comment by Vohras2** [comment]
Closing this, as we no longer use our trivia plugin, and because the first two were already addressed.
