### ISSUE TITLE
I luv you elemental

### ISSUE THREAD

**Issue by Drericeto420** [ObliqueNET/Server#1009]
i finally mustered up the courage to say this. 

i luv you elemental. be my girlfriend. my valentine left me. i wanna be with a real man like you. luv you bby. mwah. <3 ;) ;) <3 <3<3<3<3<3<3

I cry everynight because you mistreated me. No other minecraft server is as fun as yours. One day i hope you let me come back and play. I feel guilt over my actions and I tear up everytime I think about pokemon. 

I just wanna play with my legendary pokemon and talk with the friends I have made. Dont take away the last bit of happiness I have in life.  Playing pixelmon with you guys has been the most fun I had in a long time. 

Please unban me im very sorry. Im crying while writing this.

**Comment by ElementalMP** [comment]
Taken, sry.

**Comment by Drericeto420** [comment]
thats fine
how about an unban?

**Comment by ElementalMP** [comment]
No. I'm not going to bother explaining to you why. Go read your last 5 appeals, Have a great day.

**Comment by Drericeto420** [comment]
i never did anything. i got perma banned for calling someone a pussy
