### ISSUE TITLE
Sceptile and TRs

### ISSUE THREAD

**Issue by ConversaBC** [ObliqueNET/Server#1011]
I have been testing some TRs and TMs from gen 8 since the recent patch and discovered an issue. Sceptile is unable to learn Dragon Pulse through the Dragon Pulse TR. However, it learned Focus Blast through TRs, which means Dragon Pulse is glitched for Sceptile - likely other pokemon as well.

I'm unsure if the screenshot will show, but I'll try anyway.
![sceptile](https://user-images.githubusercontent.com/79278651/108404572-438da700-71dd-11eb-919f-431000194748.png)

**Comment by Vohras2** [comment]
This is working as intended. Sceptile didn't learn Dragon Pulse by TM in Gen 7, it was a tutor move. It still learns it by tutor as of now.

**Comment by ConversaBC** [comment]
Odd, the website PokemonDB shows that Sceptile can learn Dragon Pulse via TR in the Crown Tundra DLC. Are DLC mons not considered gen 8 mons?

**Comment by Vohras2** [comment]
This will be fixed in the next day or two.
