### ISSUE TITLE
infinite Z moves 

### ISSUE THREAD

**Issue by BunkerMonk** [ObliqueNET/Server#1012]
I just used Inferno Overdrive 3 turns in a row soo uhhh yeah...

**Comment by BunkerMonk** [comment]
just noticed i can use them infinatly because they are not being used up at all.

**Comment by Vohras2** [comment]
Can you test this in SP to confirm if it's a server or pixelmon bug?

**Comment by Rasgnarok** [comment]
Please report this bug directly to Pixelmon, and make sure to provide a step-by-step explanation of how the Pixelmon team could reproduce your bug. Report here: https://pixelmonmod.com/tracker.php?p=2.
