### ISSUE TITLE
Move Tutor Issue

### ISSUE THREAD

**Issue by Blitzmentalist** [ObliqueNET/Server#1013]
The Ione Move Tutor does not work with my Scolipede. When I select the move "Aqua Tail" and click it to go ahead, I am just booted out of the Move Tutor GUI entirely. The GUI works properly with other Pokemon.

As Scolipede is one of the Pokemon that recently had its moveset errors fixed, I believe this is a lingering effect of either the original error or the fix.

**Comment by Vohras2** [comment]
Scolipede no longer can learn Aqua Tail by move tutor. What you are likely seeing is a disconnect between user stat files vs server stat files.
