### ISSUE TITLE
/wiki eevee biome not showing correct information

### ISSUE THREAD

**Issue by Notsensitive99** [ObliqueNET/Server#1014]
![Github](https://user-images.githubusercontent.com/79343174/108576597-18f33980-7316-11eb-9464-f061a80b38cd.png)
when I type /wiki eevee biome it says that it doesnt spawn in any biomes even though it spawns in birch forest, so uhhh ye.

**Comment by Rasgnarok** [comment]
This is a report that should be made to https://www.pixelmonmod.com/tracker.php?p=8, please forward it directly to Pixelmon as /wiki is an official sidemod.
