### ISSUE TITLE
Peoples balance being reset to 100

### ISSUE THREAD

**Issue by CptTCov** [ObliqueNET/Server#1016]
There has been 2 reports of this in 2 days, where someone had money, but a few hours later they had a balance of 100.00
Likely an issue around the /pay issue a few days ago. 
![Screenshot_127](https://user-images.githubusercontent.com/78214029/108610258-3a413d80-7389-11eb-9659-3232df2e41e3.png)
![Screenshot_126](https://user-images.githubusercontent.com/78214029/108610265-49c08680-7389-11eb-955e-efd16989d076.png)

**Comment by SalizarKarifian** [comment]
My balance has reset 3 times, first with the 160k which was used with a /transfer instead of /pay and two other times with my vote and selling money.

**Comment by Squidammo** [comment]
I had the same issue, Had like 7k-near 8k $ and when I came back today, lost everything. Was selling a bunch of slime balls and I had only 1.5k after ):

**Comment by Rasgnarok** [comment]
@CptTCov @SalizarKarifian You'll need to comment on the ticket and give me a proper timeline of the events, including when EXACTLY you were last online before the money glitch, and when EXACTLY you noticed the glitch. **Without precise information, I cannot debug this and fix it!**

**Comment by Rasgnarok** [comment]
Thanks to @Squidammo , we were able to find some specific bugs with the economy plugin. Next restart will patch these, please use this ticket again if the issue persists.

**Comment by Squidammo** [comment]
So will we get back our money? May seems like nothing to you but 7k was actually hard to farm since I'm new lol
