### ISSUE TITLE
The Jewel Thief Quest, Cave bugged. 

### ISSUE THREAD

**Issue by Notesboy123** [ObliqueNET/Server#1017]
I am currently doing the Jewel Thief quest. It tells me to enter the cave. I have run through the cave several times, and I have checked the quest to see if it has updated. It is still asking me to enter the cave. I do not know what to do.

**Comment by BunkerMonk** [comment]
Might sound weird but trying walking through the entrance multiple times with no speed increasing items real quick. Entry zones are kinda finicky especially with fast moving people.

**Comment by Notesboy123** [comment]
> k.

I have multiple times. With and without the running boots, and shifting.

**Comment by menno516** [comment]
username?

**Comment by Notesboy123** [comment]
Notesboy123

**Comment by BunkerMonk** [comment]
I used myself a guinea pig, and the quest worked as intended. Can you get on and show me what your doing?

**Comment by BunkerMonk** [comment]
issue resolved, player was in wrong location.
