### ISSUE TITLE
Balance reset 

### ISSUE THREAD

**Issue by Notesboy123** [ObliqueNET/Server#1018]
Right before the server restarted today I was at around 4000 dollars. After the reset the balance was set to 100.

**Comment by Squidammo** [comment]
If you did not already, you should ask on the discord's support for a refund, this bug has been fixed. You can also close this issue, have a good day :)

**Comment by menno516** [comment]
This ticket does not need to be closed, github works just like "#support" in discord.

**Comment by Vohras2** [comment]
Closing, as I believe Ras refunded you. If not, reopen this ticket.
