### ISSUE TITLE
[Suggestion] Frontier back to greatness

### ISSUE THREAD

**Issue by itanomaly** [ObliqueNET/Server#1023]
Hello!

I used to play the server about a year ago, I played in Stratos. I remember Battle Frontier with many spawners for EVs and it was great! You didn't have to beg around people to help you find certain spawners and it was so fun! I don't know why it was removed, but I think it'll help the server by helping newcomers find the spawners easily which are as of now very hard to find (can tell as a new Terra player).
Thanks for reading!

**Comment by Rasgnarok** [comment]
Though we already have a lot of EV spawns (Nyr is a good example), we could easily help with the signalization by making floating text around those spawn points. All spawns in Nyr should allow you to train up EVs as needed. Alternatively, we might need to double on spawners. Thoughts, @Vohras2 ?

**Comment by Vohras2** [comment]
We already have plenty of spawners that give +2 evs for pokemon. With the current surplus of spawners we have, I don't think this really needs to happen.
