### ISSUE TITLE
I was banned and I find it unfair 

### ISSUE THREAD

**Issue by ECOECOPLUS** [ObliqueNET/Server#1024]
Hi, my nickname in pixelmon is ECO_PLUS,

(sorry for the spelling i use google translate because im not english )

If I open a request it's because I need help. Indeed, I was banned from the OBLIQUE server today just after having been banned for a few days.

The cause of this ban is that I, along with friends made lavas castes in **our** claim, We subsequently asked the moderators for help to remove this grievance with administrator orders, they did not wanted and we therefore continued our pokemon adventure, One day I was ejected from the server before being banned until 24/02/2021 at around 12 hours, and around 22 hours I tried to connect but I have had a message which suggests that I am banned for life, if you accept it, dear moderators and administrators, 

please debanire me, **_if you do not want it I will suplicate you, give all my pokemon to Wizizi._** 

thank you for reading me despite the crappy google translation

I wish you a good day. 

My discord : Kurix#6135

My email : botmaison1@gmail.com

**Comment by Squidammo** [comment]
You should post a screenshot of the reason, You probably griefed someone / cheated or something, in which case you won't be unbanned

**Comment by menno516** [comment]
hi Squidammo, 
Even if the intentions were good, please don't answer on other peoples tickets.
You do not know how we work with certain situations and can give false/wrong answer leading to confusion and misleading information. 

As example you said this guy will not be unbanned, you do not decide that. We have certain people who do ban appeals for a reason and will comment on it if something is missing or if they will be unbanned or not.

The github works just as good as support, the people who need it can answer it them self. So there is no need for you to slide in, tell someone to close a ticket and go to a different place as well when it is not resolved yet

**Comment by wishywoshyjoshy** [comment]
hey remember me its wishywoshyjoshy and you were making fun of my cousin nick gurr im am writing to you because i am annoyed for you banning me

ps.if you dont unban me i will get the karate man on you wishywoshyjoshy out

**Comment by wishywoshyjoshy** [comment]
ree

**Comment by wishywoshyjoshy** [comment]
ree

**Comment by wishywoshyjoshy** [comment]
ree

**Comment by wishywoshyjoshy** [comment]
ree

**Comment by wishywoshyjoshy** [comment]
ree

**Comment by wishywoshyjoshy** [comment]
ree

**Comment by wishywoshyjoshy** [comment]
ree

**Comment by wishywoshyjoshy** [comment]
ree

**Comment by wishywoshyjoshy** [comment]
ree

**Comment by wishywoshyjoshy** [comment]
ree

**Comment by DiddyTheKid** [comment]
Please refrain from using other peoples tickets for your ban appeal. If you would like to make your own ban appeal, press new issue and you can make your own. 
Thanks!

**Comment by Katadreme** [comment]
I apologise for the delay in responding to your appeal. I'm going to give you a second chance and unban you as I feel the language barrier had caused a few problems here. However this doesn't mean that your actions haven't gone unpunished. Lava castes fall under our griefing rule so if we find you are doing them again this ban will quickly be re-instated.
