### ISSUE TITLE
[Quest] Bug: On the Road Again

### ISSUE THREAD

**Issue by Treejan976** [ObliqueNET/Server#1026]
Whatever flag to change Tony's dialogue isn't triggering for this quest, thus making it impossible to progress. 
NPC is at  (-508, 39, -95)
![2021-02-26_19 34 05 copy](https://user-images.githubusercontent.com/72344461/109371345-1474d680-786a-11eb-8976-ba6b528cb6e8.png)
![2021-02-26_19 34 12 copy](https://user-images.githubusercontent.com/72344461/109371348-163e9a00-786a-11eb-8e42-50e0e0907183.png)
![2021-02-26_19 34 15 copy](https://user-images.githubusercontent.com/72344461/109371349-176fc700-786a-11eb-8385-8c75a174e853.png)

**Comment by BunkerMonk** [comment]
I know the answer! (I got stuck here too) You do not have the items that the questgiver handed you at the beginning of the quest in your inventory. You need 3 white wool, 3 melon blocks (not the slices), and 5 wheat to trigger the dialogue. There is no set NBT data needed for them thankfully so if you no longer have them, you can create your own and it counts.

**Comment by Treejan976** [comment]
Damnit, this is what I get for doing a quest over the course of three weeks. I would probably suggest the hint including something about needing said items, but that's more on me. Thank you, Bunker!
