### ISSUE TITLE
Server quests are unclear / not completed !

### ISSUE THREAD

**Issue by Squidammo** [ObliqueNET/Server#1027]
Most of the quests are unclear / unintentionally misleading / and some are even missing infos! I could not tell how many quests I've completed with the help of staff because of that, there's too many. But here's some examples: The heart of the cards (I think), after trying to give the cards to some npcs, the quest is suddenly going back to Nyr, but it doesn't tell the player! what the player will do: search in Agni for more people to talk to. That's not at all what we need to do and I completed this quest by accident, trying to find some new quests. Here's another one: Pick your potion. After completing the riddle #1 (which is completed when going at the entrance of heill portal cave) it's directly updating the quest with the second riddle, before even starting a fight with a random pokemon that's supposed to give us a mushroom AND the quest never tell us that we need to defeat this pokemon, thanks to tkdowning who helped me doing this quest by telling me himself that we got to kill a random pokemon down the cave.
Anyways, I think someone should work on updating these quests, and maybe even add an option to change our choice if we missclicked the wrong quest diffuculty!

I've been told to post this here since misleading infos / unclear / confusing are considered as bugs :)

**Comment by Rasgnarok** [comment]
These will have to be addressed on a case by case, feel free to detail more as needed. I'll forward this to @PrimalCyndaquil so he can take a look at the ones mentioned. After 5 years of quest data, it's normal that this will always be a game of catch-up. It's not possible to systematically fix these.

**Comment by PrimalCyndaquil** [comment]
We're trying to update inaccurate or misleading hints as we find them to make quests easier to understand for players. The issues addressed in this post have since been fixed. Thank you for bringing them to our attention. I'll close this issue- Any inaccuracies in the future brought to our attention in another post would be greatly appreciated. Please include screenshots and such if you ever do. Thanks!
