### ISSUE TITLE
Commands /t info and /town delete will not work if the town name has a space in it.

### ISSUE THREAD

**Issue by PJLesure** [ObliqueNET/Server#1032]
We have tried to figure out why the commands /t info and /town delete stopped working if towns have a space in their name, but as an example, "Cherish Town"  if you do /t info Cherish Town or if you put it in quotes /t info "Cherish Town," it will not work. 
<img width="764" alt="Screen Shot 2021-03-01 at 1 04 44 PM" src="https://user-images.githubusercontent.com/77369060/109559407-7bbfa000-7a8f-11eb-8d7c-4d098287601e.png">
<img width="743" alt="Screen Shot 2021-03-01 at 1 05 23 PM" src="https://user-images.githubusercontent.com/77369060/109559434-811cea80-7a8f-11eb-83aa-2cb7d980c2c7.png">

**Comment by PJLesure** [comment]
Just tested this again, it seems to be working fine now when you put the town's name in quotation marks.👍🏼

**Comment by Hiroku** [comment]
Oh yeah I forgot to say that I fixed it lol
