### ISSUE TITLE
Ban Appeal - Canadian_Lucario 

### ISSUE THREAD

**Issue by CanadianLucario** [ObliqueNET/Server#1036]
I am currently banned on Oblique for the reason "Spamming profanities on HappyCloudMC, byebye". This happened i believe early 2019. I didn't know i was banned on this server until this past week.

Although there is no excuse for hopping on a server for the sole reason to cause trouble, I can say without a doubt that I have moved past this and have become a better person. I have never done something like that before, and I haven't done something like that since. It was a stupid thing I was persuaded into doing one night by people who obviously weren't good influences at the time.

I am unbanned on HappyCloudMC but I would also like to apologize here to anyone who I may have pissed off by doing that.

**Comment by CanadianLucario** [comment]
I should probably leave my ingame name:

Canadian_Lucario

**Comment by CanadianLucario** [comment]
Just wondering if there's been any decisions made on this?
Been about a week.

**Comment by Katadreme** [comment]
Since you have been unbanned on HappyCloud, and I believe you are genuine enough with appeal, I'll unban you. But make no mistake, tis ban will be re-implemented if decide to break server rules.
