### ISSUE TITLE
Banned from server?

### ISSUE THREAD

**Issue by Kyjinx** [ObliqueNET/Server#1037]
Hello guys, i'm really sorry if i did anything but im not really sure what i was banned for. I may have started up the wrong modpack and went onto the server which is entirely my fault but I would really appreciate it if i could recieve a second chance. I had a lot of fun on this server and put in quite a bit of time into things such as my base and team and I would hate to lose them, again im very sorry if i did and thank you to whoever is reading this. Have a good day

**Comment by Katadreme** [comment]
Can see you've logged in twice with these mods lately so Im inclined to believe you started up with the wrong modpacks, so I will unban you. Please delete or disable any and all hacks / mods that you might have next time you are on, as, if you are found to be having these mods enabled again, you will be banned promptly.
