### ISSUE TITLE
I was banned and i havent even been online to do anything wrong

### ISSUE THREAD

**Issue by MissNova97** [ObliqueNET/Server#1038]
I am MissNova, i have been with the server a short time, i got on this afternoon, was kicked for a server restart, and when i tried to reenter the server it said i was banned for stealing. I at one point did loot not knowing it belonged to someone, I returned everything with compensation. That was a few days ago and everyone said things were fine. I havent been on since the 1st and dont understand why i have a ban.

**Comment by Rasgnarok** [comment]
Hi Miss, I took a personal look at your ban appeal following our discussion on Discord. After revising the circumstances surrounding your tempban, I am going to be unbanning you in the coming minutes. I've analyzed with fellow staff the evidence, which pointed to a theft committed on the 27th, _before_ your warning by our helper, Miss Elyri. You were reportedly very collaborative and returned everything with compensation at the time. The secondary theft should have been addressed at the same time, and did not warrant a second warning and tempban, as no theft was committed _after_ our staff's warning.

Please accept my apologies, and thank you for your understanding - I realize that ideally, this should not have happened. We will be taking precautions so logs are more carefully analyzed from now on.
