### ISSUE TITLE
Bug report? i dunno how to call this, ill'try: the Timid nature glitch.

### ISSUE THREAD

**Issue by TheKingmario2** [ObliqueNET/Server#1039]
I don't know how and why. but im a very gifted individual (or kinda cursed, that is all a matter of opinion). I have the ability of getting timid nature pokemons in 2 catches out of 3! and this is not a matter of mere RNG, but definitely something odd buried very deep in the game programming codes.

I already took part in a test for Tylerchu (at first skeptical about my situation), were i catched for her 5 mons......3 of them were timid, in her catched mons there wasn't one timid. She again asked me to catch other 5 speciments.....and once again 3 timids out of 5!
If you don't believe me, just ask to the staffer Tylerchu.

**Comment by Vohras2** [comment]
Do you have a synchronize pokemon in the first slot of your party?

**Comment by TheKingmario2** [comment]
YES! i have a mew with synchronize.

**Comment by Vohras2** [comment]
That would be why. Synchronize has like a 50% chance to make the wild pokemon have the same nature if the pokemon is in slot 1 of your party.

**Comment by TheKingmario2** [comment]
oh......so it basicly has a secret passive ability. neat
