### ISSUE TITLE
Quest builder suggestion: A set weather from turn 1, without the right ability or moves needed for it.

### ISSUE THREAD

**Issue by menno516** [ObliqueNET/Server#1041]
The battle will start having a set weather like sun, rain, hail or sandstorm from turn 1.

The weather would if possible last for as long as possible.
(if possible) the weather wont be able to get changed by things like  drought, drizzle, snow warning, sand stream, air lock, sunny day, rain dance, hail or sandstorm.

Primal things:
the terrains like "Grassy, Misty, electric and psychic terrain" (In ability's same order: Grassy surge, Misty surge, Electric Surge and Psychic surge)
Ultra beast auras getting a stats boost on battle entry.

@Hiroku

**Comment by Vohras2** [comment]
Closing to merge with https://github.com/ObliqueNET/Server/issues/1113
