### ISSUE TITLE
Command not working with the questbuilder

### ISSUE THREAD

**Issue by starwarschamp4** [ObliqueNET/Server#1042]
Last week when I made the seasonal quest for that week, I did this:

fire_command(delay=1;command=/give PLAYER pixelmon:rainbow_badge 10 0 {display:{Name:"Event Token",Lore:["Redeem these with Katadreme or RudolfShmitler for prizes at /warp eventplaza! (Same thing as 1 Knut)"]},ench:[{id:0,lvl:1}],HideFlags:1})

That worked, and still does when I tested it with my name instead of PLAYER. This week when I uploaded the quest it didn't give the item. Idk if it's because of something with PLAYER or what, but it was working last time and now it's not in either quest.

**Comment by Vohras2** [comment]
Closing to move to quest master ticket.
