### ISSUE TITLE
Darumaka Spawns

### ISSUE THREAD

**Issue by GamerTuffGuy** [ObliqueNET/Server#1043]
The Wiki for Darumaka is incorrect for spawn times. The wiki states darumaka spawns at night when in reality they only spawn during the day.

**Comment by Katadreme** [comment]
This is a Pixelmon thing rather server-side so gonna close this ticket for the time being. Would be best to make a ticket on the Pixelmon bug tracker.

**Comment by GamerTuffGuy** [comment]
Ahh okay, my bad. I was told to make a ticket on the server. I’ll be more diligent to do more research before adding another ticket on the sever. 

Chance J.
