### ISSUE TITLE
SWorld Corruption Issues

### ISSUE THREAD

**Issue by SpermitTheFrog** [ObliqueNET/Server#1044]
Multiple players have reported their shulkers turning into blocks such as wood planks, dirt, stone etc, LG logs show the block has actions such as: _____ was added to pink shulker, Not sure the cause but it's occuring more and more often.

**Comment by Rasgnarok** [comment]
It's not something we can prevent, storage in Minecraft is limited by soft-locking on region files during crashes/timeouts. They have to be addressed on a case by case.
