### ISSUE TITLE
Wonder Trade issue - user XKony2012X // Discord - SWAG#6367

### ISSUE THREAD

**Issue by TheSwagMan2** [ObliqueNET/Server#1045]
I got robbed of my shiny excadrill at 10:40 PM ish 3/8/21

I had a normal excadrill that I was going to WT, because today I caught a shiny

I put in the shiny one so I did not lose it then took out the old one I had

I then did the normal command to WT the normal one, then it WT the shiny one instead. I thought I got a shiny wurmple until someone said what shiny did I add. 

I was just told it was a visual glitch, and that I got got, but im still out of a shiny.

![Screenshot 2021-03-08 224635](https://user-images.githubusercontent.com/80303030/110415616-2ae81280-8060-11eb-86be-47ee9c140157.png)

I was then able to take the exact pokemon out of my PC and put it in my party, but then when I tried to throw it out, it did not work. This is when I started asking in the chat about this issue i do believe.

**Comment by TheSwagMan2** [comment]
Is somebody going to look at this or am I just out the shiny

**Comment by Rasgnarok** [comment]
It's been a long while, and this really should've been answered sooner. Can you please tell me where was the normal vs shiny Excadrill? Usually, it asks you to confirm with a command before /wt.

**Comment by Rasgnarok** [comment]
Closing because there's been no response from OP. Please re-open if the issue persists.
