### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by glazzd** [ObliqueNET/Server#1048]
I have been banned for about a month now and was banned just for stealing a few cheap items from unclaimed land which i will pay back. I really miss the server and I really would appreciate it if my ban were to be lifted. I promise i will never steal from unclaimed land again if I am unbanned.

**Comment by Kreweta2115** [comment]
hey I got a ban for nword and my question is if I ever get UB or for how long it is? my mistake a friend let me down and I did not know that immediately bans

**Comment by UnknownFlash** [comment]
@Kreweta2115 If you would like to make a ban appeal please press the new issue button and make your own ticket.

**Comment by Katadreme** [comment]
Though a month has passed, don't see much of a change here. And though you say you miss the server, don't exactly see an apology here. And you weren't 'banned just for stealing a few cheap items from unclaimed land', you were banned for stealing from an unclaimed base after being told to read the server rules twice, one of those times being from me. So no your ban won't be lifted. Also if I recall correctly, you had no problem being banned when we spoke about your stolen money issue, so thought this ban would've helped:

![Screen Shot 2021-03-17 at 8 06 43 pm](https://user-images.githubusercontent.com/50907133/111442402-6f5c6800-875c-11eb-9164-4203920a1b9d.png)
![Screen Shot 2021-03-17 at 8 07 05 pm](https://user-images.githubusercontent.com/50907133/111442420-74b9b280-875c-11eb-9fe8-6841ed8fdcc1.png)
