### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by lolsikinz** [ObliqueNET/Server#1050]
There is an issue where some gymleaders (and probably players) can't mega evolve in gyms. Mega evolution works fine for me in normal player v player fights but not the Aquagyms gymfights. Z-moves still work and it only seems to affect mega evolution.

**Comment by Vohras2** [comment]
Closing as I'm pretty sure this was a pixelmon side issue due to world settings and the way pixelmon handles zmoves vs dynamax. Reopen if this continues to happen post 8.2.
