### ISSUE TITLE
BAN FOR NWORD

### ISSUE THREAD

**Issue by Kreweta2115** [ObliqueNET/Server#1051]
hey I got a ban for nword and my question is if I ever get UB or for how long it is? my mistake a friend let me down and I did not know that immediately bans, i would like to play with friends :((((

**Comment by Katadreme** [comment]
Saying a friend made you do it, or a friend did it on your behalf isn't a really good excuse. Either way not sure why'd you'd need to use the n word in first place on a pixelmon server. And there wasn't much of an apology or appeal here so answer here is no.
