### ISSUE TITLE
Xr_y's Ban Appeal

### ISSUE THREAD

**Issue by JustXray** [ObliqueNET/Server#1052]
Before reading this, please be aware if any screenshots were not shown and are needed, I can provide them. I just did not want to leak DMs to a public place of view. Also, please read everything <3 thank you.

Greetings to whomever is reading this ban appeal,

I’d like to start by first apologizing to Dough and all of the other leads for my disrespectful behavior. I should have gone straight to Dough with my concerns/issues instead of reaching out and venting to another staff member. So, officially, Dough I am sorry for saying what I did in those DMs, it was disrespectful and should have been a civil conversation between the two of us and no one else.

Secondly, I’d like to at least try and to clear things up though. I was fired and soon after banned for “Staff Disrespect.” While this statement is not incorrect, it was honestly a misunderstanding and was never intended to be disrespectful in the tone it was received. What I said was preemptively shown to the staff before I was able to explain myself or even get a word in. Although I am not certain, I believe the words that determined my firing/ban were a combination of the following statements I made during a very stressed and upset time, “dough treats his gym leads like shit,” “he does not care,” “Just tired of being treated like shit by dough,” “he acts like he can do whatever he wants bc he's lead.” 
After reviewing everything I said through DMs, as I said before, I recognize that I was being disrespectful to Dough and I apologize again for that now. However, this is my ban appeal so I am here to explain why I should be unbanned. I want to add a little bit of perspective to the conversation. I spent quite a lot of time on oblique so last year I decided I wanted to be on the Oblique staff team. I first joined the Oblique staff team as a gym leader because I am competitive and I enjoy battling. Off the bat I was entrusted with 3 gyms by Peekay which I was very happy about given I like battling. Being able to run 3 gyms on the server after only being a gym leader for about 2 weeks felt like quite the accomplishment as there were other gym leaders who had been on for longer but had less or one gym. About a month later I applied for helper because I also enjoy helping new players and I might as well since I was already friends with a lot of the staff members after being hired on as a gym leader. Months pass and then Peekay retires, Dough becomes our new gym lead which I was excited about even though I liked Peekay a lot, Dough seemed very cool and I had only talked to him a couple times so I was very intrigued to see how things were going to change. After the AquaGyms plugin was added and the gyms reset I first flew through the gyms undefeated (99.9% sure I was the first to beat them all this time, I was also very proud of this and hoped the leads would notice) and then I took as many battles as I could with staff and regular players. After a month or so the gym battles died off so I became bored and decided to ask for another or more gyms (this happens quite a lot with other gym leaders as well). Every time I asked Dough or even mentioned it in the #gyms chat, it was either ignored or simply said “Stop asking” or “If you keep asking I’m going to fire you.” While these statements can be funny and understandable the first couple of times but at a certain point it just felt useless to ask for more gyms. As I’m sure this would’ve been brought up anyways, I complained about this fact as well a couple months ago and was then told to DM Dough instead of complaining about him, so I felt bad about complaining about him because that was never the intention I was really just venting as was the case this time. So the first time this happened, I quickly shot Dough a dm about getting another gym and he actually replied saying he would have to look for a spot to see where he had room but I would definitely be getting another gym. 
![image](https://user-images.githubusercontent.com/49011518/111713151-5ff52180-8825-11eb-86f9-fd1f26a01e17.png)

A couple months passed and still no response from him about getting another gym and if I ever brought it up again it would basically get ignored. This made me, as a gym leader, Dough’s employee, feel disconnected and disrespected. Dough’s actions and words after this point just further made me feel almost worthless as a gym leader. It may be his personality but it just seemed to me like he did not care about me or anyone else on the gym team for that matter. I always got this feeling (and I’m pretty sure he even said it at one point) that Dough did not care if we were there or not and that if any of us left he would just replace us. A perfect example of this would be the recent event of Lexjo being promoted to Wildcard after Loki’s departure. I said this in the gym chat;
![image](https://user-images.githubusercontent.com/49011518/111713091-481d9d80-8825-11eb-9893-139d07042289.png)

To be clear, I have nothing against Lex, I consider Lex a friend, I just never expected him to get Wildcard not because he wasn’t a good battler, it was just unexpected. So I was curious about the decision making process but as you can see, this doesn’t exactly make an employee so to speak, feel welcome or appreciated. I was going to DM dough about this matter after seeking some guidance from some of my friends on the staff team, however I was fired and banned before getting the chance to speak with Dough but have since messaged him explaining everything, with no response back yet.

You might be wondering “Xray why the long story, this is a ban appeal, there is no need for all of this.” The reason I am bringing all of this to my ban appeal is because I simply hope that you can see why I said what I said about Dough and hopefully, understand that it was never about disrespecting Dough, I was venting to a friend about such matters and expressing how I felt. Given the things I said were disrespectful, yes, and I accept that, but during that time and currently I have been under a lot of stress between school, work, and Oblique. I completely understand and accept my removal from the staff team, and I will use this ban appeal once again to say that I am sorry for disrespecting Dough the way that I did, I really never meant it to be that way I was just frustrated that my goal was no longer obtainable.

Thank you for reading my ban appeal.  

~Xray

**Comment by kingmathew** [comment]
Same thing happened with me my freind i have been asking questsions about my application fir weeks but no response

**Comment by Treejan976** [comment]
Kingmathew please do not use other people's ban appeals as a forum to complain about an unrelated subject. Your ban appeal will be handled in due time, but going on other issue threads to talk about it does help us or your chances at getting unbanned.

**Comment by kingmathew** [comment]
I never talked about myban appeal in that comment I was saying I was asking dough questions and he didn’t answer but that’s been resolved


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Treejan976** [comment]
Well then, if it's been resolved then there is no reason for you to be commenting about it in another person's thread. Please do not comment on this ban appeal any further, thank you.

**Comment by Rasgnarok** [comment]
After reviewing your ban appeal, I've come to the conclusion that focal point of it was completely misguided. You were fired because you were disrespectful and pushing for advancement by threatening to quit. You were in turn banned for justifying your banning by stating we, the admin team, were "proving [you] right and further showing [you] how corrupt the Oblique staff team is." That's what earned you your ban.

When confronted with your blatant disrespect of others, your continuous insinuations of your admin working "for the players and not for his staff", you did not relent and explain the situation, as you are doing now. You instead justified your discourse, and that earned you your ban - Oblique has no reason to keep that toxicity around.

Your screenshot provided ample proof of you using your position as leverage to get where and what you want. I could also provide proof of your disturbing complaints about our new AquaGyms plugin, which "was too centered around the players and not enough on staff" (it's incredulous to think that's a bad thing). Of course, you also took conversations out of context - Dough not providing the reasons right then and there (screenshot above) for his choices doesn't mean there weren't any, but that perhaps the tone of the public staff channel should have been kept lighthearted. Had you actually intended on understanding his reasons, you would've known not to trust a simple joke answer as a true answer.

You saw what you wanted to see, and even now, in writing this ban appeal, you set off to both accept your wrongdoings, and at the same time, justifying them as valid. It is not satisfying. I will be leaving this ticket up for your reply, and will make my decision then.

**Comment by JustXray** [comment]
Before reading this, please be aware if any screenshots were not shown and are needed, I can provide them. I just did not want to leak DMs to a public place of view. Also, please read everything <3 thank you.

Greetings to whomever is reading this ban appeal,

I’d like to start by first apologizing to Dough and all of the other leads for my disrespectful behavior. I should have gone straight to Dough with my concerns/issues instead of reaching out and venting to another staff member. So, officially, Dough I am sorry for saying what I did in those DMs, it was disrespectful and should have been a civil conversation between the two of us and no one else.

Secondly, I’d like to at least try and to clear things up though. I was fired and soon after banned for “Staff Disrespect.” While this statement is not incorrect, it was honestly a misunderstanding and was never intended to be disrespectful in the tone it was received. What I said was preemptively shown to the staff before I was able to explain myself or even get a word in. Although I am not certain, I believe the words that determined my firing/ban were a combination of the following statements I made during a very stressed and upset time, “dough treats his gym leads like shit,” “he does not care,” “Just tired of being treated like shit by dough,” “he acts like he can do whatever he wants bc he's lead.” 
After reviewing everything I said through DMs, as I said before, I recognize that I was being disrespectful to Dough and I apologize again for that now. However, this is my ban appeal so I am here to explain why I should be unbanned. I want to add a little bit of perspective to the conversation. I spent quite a lot of time on oblique so last year I decided I wanted to be on the Oblique staff team. I first joined the Oblique staff team as a gym leader because I am competitive and I enjoy battling. Off the bat I was entrusted with 3 gyms by Peekay which I was very happy about given I like battling. Being able to run 3 gyms on the server after only being a gym leader for about 2 weeks felt like quite the accomplishment as there were other gym leaders who had been on for longer but had less or one gym. About a month later I applied for helper because I also enjoy helping new players and I might as well since I was already friends with a lot of the staff members after being hired on as a gym leader. Months pass and then Peekay retires, Dough becomes our new gym lead which I was excited about even though I liked Peekay a lot, Dough seemed very cool and I had only talked to him a couple times so I was very intrigued to see how things were going to change. After the AquaGyms plugin was added and the gyms reset I first flew through the gyms undefeated (99.9% sure I was the first to beat them all this time, I was also very proud of this and hoped the leads would notice) and then I took as many battles as I could with staff and regular players. After a month or so the gym battles died off so I became bored and decided to ask for another or more gyms (this happens quite a lot with other gym leaders as well). Every time I asked Dough or even mentioned it in the #gyms chat, it was either ignored or simply said “Stop asking” or “If you keep asking I’m going to fire you.” While these statements can be funny and understandable the first couple of times but at a certain point it just felt useless to ask for more gyms. As I’m sure this would’ve been brought up anyways, I complained about this fact as well a couple months ago and was then told to DM Dough instead of complaining about him, so I felt bad about complaining about him because that was never the intention I was really just venting as was the case this time. So the first time this happened, I quickly shot Dough a dm about getting another gym and he actually replied saying he would have to look for a spot to see where he had room but I would definitely be getting another gym. 

A couple months passed and still no response from him about getting another gym and if I ever brought it up again it would basically get ignored. This made me, as a gym leader, Dough’s employee, feel disconnected and disrespected. Dough’s actions and words after this point just further made me feel almost worthless as a gym leader. It may be his personality but it just seemed to me like he did not care about me or anyone else on the gym team for that matter. I always got this feeling (and I’m pretty sure he even said it at one point) that Dough did not care if we were there or not and that if any of us left he would just replace us. A perfect example of this would be the recent event of Lexjo being promoted to Wildcard after Loki’s departure. I said this in the gym chat;

To be clear, I have nothing against Lex, I consider Lex a friend, I just never expected him to get Wildcard not because he wasn’t a good battler, it was just unexpected. So I was curious about the decision making process but as you can see, this doesn’t exactly make an employee so to speak, feel welcome or appreciated. I was going to DM dough about this matter after seeking some guidance from some of my friends on the staff team, however I was fired and banned before getting the chance to speak with Dough but have since messaged him explaining everything, with no response back yet.

You might be wondering “Xray why the long story, this is a ban appeal, there is no need for all of this.” The reason I am bringing all of this to my ban appeal is because I simply hope that you can see why I said what I said about Dough and hopefully, understand that it was never about disrespecting Dough, I was venting to a friend about such matters and expressing how I felt. Given the things I said were disrespectful, yes, and I accept that, but during that time and currently I have been under a lot of stress between school, work, and Oblique. I completely understand and accept my removal from the staff team, and I will use this ban appeal once again to say that I am sorry for disrespecting Dough the way that I did, I really never meant it to be that way I was just frustrated that my goal was no longer obtainable.


RESPONSE TO RAS



I was considering that might have been another possible reason I was banned but I concluded it would have been safer to take the route more towards Dough. Now that I know that was the reason I will adjust my response accordingly. Thank you for allowing me to respond.

I’ll start with the claim that I was pushing for advancement through the threat of quitting. While this may seem like the case from an outside point of view, once the position was taken, I felt like there was no chance for me to achieve my primary goal in being a gym leader, to become a Wildcard. This was extremely discouraging hence why I was considering retirement. My statement of “retirement looking real nice 😂” while this may have inadvertently seemed like I was trying to use my position as leverage, it was mostly out of frustration and jealousy with a hint of laughter. Regardless, the response received from Dough was also discerning. Back to the main point, I apologize for calling the upper level staff team corrupt, as I said before I was going through, and still am going through, a very stressful time and I urge you to try and understand this statement was purely out of frustration and stress. I felt, at that moment, that the entire oblique staff team was against me. I am not trying to justify my actions, as I have said and will say again, I take full responsibility for my actions. Even if it was a stressful time, I should’ve never acted the way I did. I am fully prepared to accept a perm ban, but I decided to appeal because there are still people and players I enjoy talking to on the server.
The AquaGyms plug-in issue. Yes, I had many issues with this plugin, and now, I apologize for making those harsh complaints. It was unnecessary and excessive, although I did lose a great many battles to some of the glitches that came with the plug-in, which was disappointing and frustrating knowing the battle would’ve been a win. I don't quite know if I ever said the AquaGyms plug-in was “centered” around the players, if anything it makes an admin’s job easier, but I will say that, with its glitches, it does favor any challengers. In hindsight, I believe the reason I complained about the plug-in making it easier is because I personally prefer the gyms to be challenging and wanted it to be so for the challengers, not because it’s a bad thing to be easier for players. 
Dough’s decision. I wasn’t really expecting Dough to give a list of reasons, I know his joke answer was not the true answer. I know that Lex was promoted over others because he is a very great battler and deserves the position. I think the reason I said ”why Lex,” was again out of jealousy that I did not get the position I had strived for. I will not try to validate my response as it was immature to talk like that in the first place.
I’d like to conclude by saying that I never meant to justify my actions in my last post, I was seeking a little bit of understanding from my end to give perspective and context. I know what I said was wrong and I’m saying now that I accept and regret my actions and words. Again, I apologize for calling the oblique staff team corrupt. I hope that you can accept my apology as I do not wish to end on a bad note. Had I been able to retire instead of being fired I would’ve liked to stay on the friendly side, I still would prefer it that way given the opportunity. Again I’d like to thank you for giving me the chance to respond as I know that doesn’t always happen. 

Thank you for reading my ban appeal once more.

**Comment by JustXray** [comment]
I was considering that might have been another possible reason I was banned but I concluded it would have been safer to take the route more towards Dough. Now that I know that was the reason I will adjust my response accordingly. Thank you for allowing me to respond.

I’ll start with the claim that I was pushing for advancement through the threat of quitting. While this may seem like the case from an outside point of view, once the position was taken, I felt like there was no chance for me to achieve my primary goal in being a gym leader, to become a Wildcard. This was extremely discouraging hence why I was considering retirement. My statement of “retirement looking real nice 😂” while this may have inadvertently seemed like I was trying to use my position as leverage, it was mostly out of frustration and jealousy with a hint of laughter. Regardless, the response received from Dough was also discerning. Back to the main point, I apologize for calling the upper level staff team corrupt, as I said before I was going through, and still am going through, a very stressful time and I urge you to try and understand this statement was purely out of frustration and stress. I felt, at that moment, that the entire oblique staff team was against me. I am not trying to justify my actions, as I have said and will say again, I take full responsibility for my actions. Even if it was a stressful time, I should’ve never acted the way I did. I am fully prepared to accept a perm ban, but I decided to appeal because there are still people and players I enjoy talking to on the server.
The AquaGyms plug-in issue. Yes, I had many issues with this plugin, and now, I apologize for making those harsh complaints. It was unnecessary and excessive, although I did lose a great many battles to some of the glitches that came with the plug-in, which was disappointing and frustrating knowing the battle would’ve been a win. I quite know if I ever said the AquaGyms plug-in was “centered” around the players, if anything it makes an admin’s job easier, but I will say that, with its glitches, it does favor any challengers. In hindsight, I believe the reason I complained about the plug-in making it easier is because I personally prefer the gyms to be challenging and wanted it to be so for the challengers, not because it’s a bad thing to be easier for players. 
Dough’s decision. I wasn’t really expecting Dough to give a list of reasons, I know his joke answer was not the true answer. I know that Lex was promoted over others because he is a very great battler and deserves the position. I think the reason I said ”why Lex,” was again out of jealousy that I did not get the position I had strived for. I will not try to validate my response as it was immature to talk like that in the first place.
I’d like to conclude by saying that I never meant to justify my actions in my last post, I was seeking a little bit of understanding from my end to give perspective and context. I know what I said was wrong and I’m saying now that I accept and regret my actions and words. Again, I apologize for calling the oblique staff team corrupt. I hope that you can accept my apology as I do not wish to end on a bad note. Had I been able to retire instead of being fired I would’ve liked to stay on the friendly side, I still would prefer it that way given the opportunity. Again I’d like to thank you for giving me the chance to respond as I know that doesn’t always happen. 

Thank you for reading my ban appeal once again.

**Comment by Rasgnarok** [comment]
I will be giving you the benefit of the doubt, because I believe in second chances, and having been part of staff, you know that the community extends beyond just current staff. It's friendship, for at large members, active or otherwise.

I'll be unbanning you shortly, feel free to join when you want: https://discord.gg/B3XcYcR .
