### ISSUE TITLE
King mathew ban appeal (discord)

### ISSUE THREAD

**Issue by kingmathew** [ObliqueNET/Server#1054]
Hi im mathew and about a month Ago (i think) i made a server and sent it to every server i was in like an idiot and i got banned 😱 so i just want to say that was a mistake and please unban me

**Comment by Katadreme** [comment]
To be clear, you were banned from the discord for distributing a server invite, which would reward you for Nitro if you managed to invite 3 people. So it wasn't a server you made, and I really do think you were aware of what you were doing. Also I see you are tempbanned on the server. Until you can show that you can adhere to the server's rule, I won't be unbanning you from the discord.
