### ISSUE TITLE
Ban Appeal 3/20 xKONY2012x 

### ISSUE THREAD

**Issue by TheSwagMan2** [ObliqueNET/Server#1055]
my username is xKONY2012x. I was just logging on to vote and it said I was banned. Did I get banned for saying stuff like this is a bad trivia or?

**Comment by Katadreme** [comment]
You were banned as we had found your account is connected to another user JackDimonds, via IP. This is seen as ban evading by using another account, hence you were banned.

**Comment by TheSwagMan2** [comment]
I can say I disagree with this because I have a dynamic IP. So unless it
![Internetss](https://user-images.githubusercontent.com/80303030/112876412-7efc7a80-9093-11eb-9159-e30b6f770a01.png)

Unless TWC // Spectrum gives IPs that someone else owns then I disagree

**Comment by Katadreme** [comment]
I deeply apologise for the immense delay in responding to this again.

I have unbanned you as this seems like a plausible reasoning and apologise again for the ban in the first place and thank you for your patience.
