### ISSUE TITLE
I would like to get unbanned

### ISSUE THREAD

**Issue by williamwontonsoup** [ObliqueNET/Server#1059]
The reason I got banned is because I evaded staff questioning after they attempted to contact me several times. I am sorry that I didn't look at chat and would like to be given another chance. My IGN: fillingbrunch

**Comment by Katadreme** [comment]
You say you weren't paying attention to chat, however seems as though you disconnected each time a staff member tried to contact you. Either way, I will give you benefit of the doubt and unban. I highly advise you contact a staff member next time you are online.
