### ISSUE TITLE
Z-Moves not working.

### ISSUE THREAD

**Issue by PCGamingUniverse** [ObliqueNET/Server#1060]
It's similar to how you can't dynamax against a mega. The user would press the Z-Move button when trying to attack, the z-moves will pop up but when used it just uses their basic attack for whichever slot they clicked.

**Comment by Rasgnarok** [comment]
What world were you in, and what were you fighting exactly? Please explain a bit more so we can try to reproduce it.

**Comment by PCGamingUniverse** [comment]
A member of the server was attempting to use greninja's z-move for the first time. We were in the regular world. He would click the button that says z-move, then select the z move from his move list. When it came to his turn instead of using the z-move it would use his regular move for whatever slot he selected. We tried against wild pokemon, against trainers and even trying to use a different z move on a different mon.

**Comment by Rasgnarok** [comment]
This will have to be re-tested after 8.2, battle UI changes are coming in. If it keeps reproducing, this has to be reported to the mod first: https://pixelmonmod.com/tracker.php?p=2.
