### ISSUE TITLE
I was banned for Discord

### ISSUE THREAD

**Issue by mildsoma** [ObliqueNET/Server#1061]
mildsoma#4578
ign :  mildsoma

Joined the discord server and a few seconds after i joined like 5 seconds later , the server got removed and i was not able to join again . I've been playing on the minecraft server for a few days now and i never been in trouble on the server or anything realted to the discord server , i wanna be unbanned and be able to link my account with discord.
![Capture2](https://user-images.githubusercontent.com/81653613/113058952-d4608680-917c-11eb-9185-5a2b5d77d1ec.PNG)

**Comment by Rasgnarok** [comment]
Unbanned, that was our Discord bot being overzealous. I am very sorry for the issue - please rejoin using https://discord.gg/B3XcYcR
