### ISSUE TITLE
has_money trigger not actually checking players for money and returning errors when uploaded.

### ISSUE THREAD

**Issue by PrimalCyndaquil** [ObliqueNET/Server#1062]
![image](https://user-images.githubusercontent.com/48627086/113060661-dd674d00-91a8-11eb-8670-72ae0ded7669.png)
The has_money trigger does not check for players actually having the bal they need. Furthermore, quests with this trigger return like above when uploaded. Both uppercase "False" and lowercase "false" have been tried, as well as inserting a comma in "15000" to make it "15,000". None of these attempts have worked.

This being fixed would allow a few QoL changes when it comes to purchasing keys and similar items in bulk.

**Comment by Hiroku** [comment]
Fixed in the next restart
