### ISSUE TITLE
Move Relearner not functioning for User's Zoroark

### ISSUE THREAD

**Issue by Blitzmentalist** [ObliqueNET/Server#1063]
This issue occurred with the user "TheLemonadeMan_"'s Zoroark. The Pokemon was unable to learn Night Daze from the Move Relearner. The move appeared in the UI, but selecting it would not proceed. This occurred even when Zoroark had empty slots in its moveset, and when attempted by yours truly. Could possibly be the result of moveset updates or recent TM issues. Will keep an eye out for recurring instances.

**Comment by Vohras2** [comment]
What level was the Zoroark in question?

**Comment by Vohras2** [comment]
Closing as there has been no response to this.
