### ISSUE TITLE
Lilian NPC bugged

### ISSUE THREAD

**Issue by itanomaly** [ObliqueNET/Server#1065]
Hi, at the coords -295 72 -1188, the NPC Lilian (Lv. 40) is bugged, a player reported it says that before the end of the battle it says there's a bug with the fight, and to go check the console for more details.

**Comment by PrimalCyndaquil** [comment]
This is a pixelmon bug and, luckily, this NPC is currently not involved in any quests. Please get timestamps in the future if this issue occurs again. Thanks!
