### ISSUE TITLE
Triggers not activating after Log-Off objective completed.

### ISSUE THREAD

**Issue by PrimalCyndaquil** [ObliqueNET/Server#1067]
Currently, triggers attached to a log-off objective do not activate when a player logs off. This has resulted in numerous workarounds being trialed and it is getting progressively convoluted. A solution to this would be greatly appreciated.

For testing purposes, a quest was built in the QD-Training area to see what triggers may work and what may not.
A battle was started, with the following triggers attached to log-off as a failsafe:
-Skip to stage. 
-Send Chat.
-Send Mail (Fire-Command). I rigged this to send a mail to myself in the case that it activates.

Both skip stage and send mail failed, and did not activate. The file for the quest is available on request. Thanks!

**Comment by Vohras2** [comment]
Closing to move to master ticket.
