### ISSUE TITLE
I left town and lost all my money

### ISSUE THREAD

**Issue by Vinbot123** [ObliqueNET/Server#1069]
I was in a town which I named Temporarytown and I left 2 days ago using the command /t leave as the last person in the town. however I left 100k in the shared bank and I can't get it back. IGN: Vinbot123, whoever deals with this sorry for the inconvenience.

**Comment by Vinbot123** [comment]
I was in a town which I named Temporarytown and I left 2 days ago using the command /t leave, as the last person in the town. However I left 100k in the shared bank and I can't get it back. IGN: Vinbot123

**Comment by Rasgnarok** [comment]
I can handle the refunding, but asked Vin to make a ticket so we know why this happens - if he is the last person, then it should auto-disband, right? @ Hiro

**Comment by Vinbot123** [comment]
Thanks a lot for getting on this and helping so quickly, sorry for any troubles this caused.

**Comment by Hiroku** [comment]
Fixed
