### ISSUE TITLE
Lucky Eggs Disappearing

### ISSUE THREAD

**Issue by beehtoken** [ObliqueNET/Server#1070]
While playing on the server, I have lost a total of 3 lucky eggs due to visual glitches. While leveling up and switching in and out of my held items, sometimes pokes will turn into eggs. During this visual glitch if a lucky egg is the held item it disappears. I wish I had video evidence of this process happening but I don't. I don't want anything replaced all I want is this issue to be know. 

Thank you for your time,

Beehtoken

**Comment by Rasgnarok** [comment]
This is an issue with Pixelmon storage itself, I don't think much can be done about it due to the instability of Spongeforge inventory handling and Pixelmon. Closing, but thank you for the heads up!
