### ISSUE TITLE
[Trivia] 'Air' as a message reward

### ISSUE THREAD

**Issue by godverdmme** [ObliqueNET/Server#1071]
After the latest restart (around 2pm CEST 10/04/2021) the market is down, giving a nullpointer whenever you try to use the /market commands.

https://gyazo.com/39557ca5d627800a4f4e68be274185fa

secondly the quiz rewards are broken as well, giving the items to the winner as normal but giving the following message to everyone:
https://gyazo.com/a5e395547ab4c3a4fefb9b3a46e1cceb

**Comment by Rasgnarok** [comment]
Market has since been fixed, sometimes ability storage fails, and it has to be debugged manually via a command. As for quizzes, the message itself is visual, correct?

**Comment by godverdmme** [comment]
It is, the rewards are correctly given to the person. but the entire server gets the message among the lines of"<player> received 0xAir as a reward"

**Comment by Hiroku** [comment]
Fixed
