### ISSUE TITLE
No more statues

### ISSUE THREAD

**Issue by Specter882** [ObliqueNET/Server#1072]
Since the server restart I don't have access to any statues that I had before.

**Comment by Rasgnarok** [comment]
Can you please give me your username? I need to look into your perms.

**Comment by Specter882** [comment]
> Can you please give me your username? I need to look into your perms.

My username is Specter

**Comment by Vohras2** [comment]
Was this ever fixed?

**Comment by Vohras2** [comment]
Going to just close since this hasn't been replied to. Reopen if you still have these issues.
