### ISSUE TITLE
Sync Pokemon dont'work 

### ISSUE THREAD

**Issue by beehtoken** [ObliqueNET/Server#1073]
The GitHub does not specifically state that sync pokemon do not work on legends and the quest that pertain to them. Can we add a clause stating the above? 

-Thank you for your time

Beehtoken

**Comment by menno516** [comment]
I have verified through testing the Groudon quest 30 times that the chance for synchronise to activate is the same as normal. The set nature only comes into effect if Sync doesn't activate, or if it is not present at all.
