### ISSUE TITLE
Drunk Relicanth

### ISSUE THREAD

**Issue by BunkerMonk** [ObliqueNET/Server#1077]
I found a Relicanth in my house yesterday, yes this is awesome, but there is one problem. I live in a skyblock island above y140 in a swamp. I saw another Relicanth chilling out in a waterfall in the cave im building under Nyr. This is a sealed chamber, so unless a lead or mod+ was messing with me, it can't be someone using a disguise. Both locations are definitively not the Deep Ocean biome they are supposed to be limited too. =D

**Comment by Vohras2** [comment]
Relicanth has a chance to spawn in all underground water areas. So it's not out of the ordinary.
