### ISSUE TITLE
Spawn of wingull are less than legendaries

### ISSUE THREAD

**Issue by juju338** [ObliqueNET/Server#1080]
Just wanna know why wingulls and pellipers are so so so so so so so rare. I only found one in literally 7 hours.

**Comment by CenizaRey** [comment]
Wingulls have a rarity rating of 90, spawn in all oceanic biomes as well as all beach biomes, and spawn at all times except night time. Below you'll find a photo of 9 wingulls that spawned after I teleported to an ocean and waited 30 seconds. If you need any help with pokemon spawning in the future, remember to do "/wiki (pokemon) biome/time/rarity", or ask a staff member.

Hope this helped!

![Wingulls](https://user-images.githubusercontent.com/42212238/116284518-12a19380-a785-11eb-8e48-14ecfe328774.png)

**Comment by juju338** [comment]
> Wingulls have a rarity rating of 90, spawn in all oceanic biomes as well as all beach biomes, and spawn at all times except night time. Below you'll find a photo of 9 wingulls that spawned after I teleported to an ocean and waited 30 seconds. If you need any help with pokemon spawning in the future, remember to do "/wiki (pokemon) biome/time/rarity", or ask a staff member.
> 
> Hope this helped!
> 
> ![Wingulls](https://user-images.githubusercontent.com/42212238/116284518-12a19380-a785-11eb-8e48-14ecfe328774.png)

Thanks for your answer. I am actually in a beach biome close to an ocean and not a single wingull has spawn. I have done the experience with an admin and the result was the same. Wingull should be really rare on the server. I waited 10 minutes and still not a single one.

**Comment by Vohras2** [comment]
Ras has made adjustments to hopefully fix this issue, so I'm going to close this for now. Please open a new one if you still find this to be a problem.

**Comment by juju338** [comment]
Thank you :)
