### ISSUE TITLE
Logan19582 unban request

### ISSUE THREAD

**Issue by Logan19582** [ObliqueNET/Server#1081]
I was just messing around trying to be funny, also I have just got discord and didn't understand what the bot thing was. I am deeply sorry and would like to request a unban on discord please.

**Comment by Logan19582** [comment]
also i wont ever mess around again

**Comment by Logan19582** [comment]
I would like to be able to use market place

**Comment by Katadreme** [comment]
Firstly, sorry for the long delay in respond to your discord appeal.

With that said, I understand you didn't understand how the bot worked, but that doesn't excuse the excessive trolling you displayed afterward. This kind of trolling is not welcome here. I will unban you from the discord in hopes that during this time of waiting for a appeal response, you had matured. You will be banned from the discord and in-game if need be if the trolling or other rule-breaking is continued.
