### ISSUE TITLE
invite friend

### ISSUE THREAD

**Issue by XxZephanxX** [ObliqueNET/Server#1082]
hello i friend invited a friend my name is XxZephanxX and my friend is Saint0cean and we have played more then 12 hours together but we didnt get any rewards im not sure if it broke or something.

**Comment by Vohras2** [comment]
Try having both of you relog.

**Comment by XxZephanxX** [comment]
we just tried nothing happened

**Comment by Vohras2** [comment]
Try playing another hour or so together, and then relogging once more. If that doesn't work, post a screen shot of your server play time here and we'll sort it out. It's possible you were on the server for a little bit before inviting them, so it's not counting the full 12 hours. It only counts 12 hours -after- you send the invite.

**Comment by XxZephanxX** [comment]
ok will do thank you for fast response

**Comment by XxZephanxX** [comment]
![imag5e0](https://user-images.githubusercontent.com/83356952/116428055-8f2e8380-a812-11eb-864a-1bbe7eb66ea2.jpg)
![6](https://user-images.githubusercontent.com/83356952/116428063-92297400-a812-11eb-85d9-f5f5c25dcfc6.jpg)
theres mine and his

**Comment by Vohras2** [comment]
Closing since refunded.
