### ISSUE TITLE
Unable to start sentence with "redeem"

### ISSUE THREAD

**Issue by lolanonymous** [ObliqueNET/Server#1083]
Cosmetic plugin will interperet any sentence you start with "redeem", without the slash as an attempt at a command.

https://streamable.com/79jdv0

linked is a video.

**Comment by Vohras2** [comment]
This is a pixelmon issue, as that's their redeem command for cosmetics. Should be reported to their bug tracker.

**Comment by fatyg5** [comment]
Transferred by me. Will leave this open till fixed

**Comment by Vohras2** [comment]
Appears to be fixed, at least with my testing.
