### ISSUE TITLE
SUGGESTION /tryevolve (slot) [TICKET SO NOBODY FORGETS]

### ISSUE THREAD

**Issue by CenizaRey** [ObliqueNET/Server#1084]
At the request of Ras, posting my suggestion from a few months ago as a ticket:

(Some information may be outdated as this is a direct copy/paste that is several months old)

Suggestion: '/tryevolve (slot)' - A definitely possible command to develop which checks to see if a pokemon should be evolved at its current level, and if it should be, fires the evolution event.

Reasoning: Pixelmon's evolution mechanic can be patchy. Sometimes pokemon evolve forever, sometimes they evolve into themselves, and sometimes they don't attempt to evolve at all. /tryevolve aims to remedy that by allowing the player to independently trigger the evolution event without staff aid, without giving them the power of the /evolve command, which triggers the evolution event regardless of the pokemon's level.

Notes: By adding this command, you remove the need for helpers and other lower-end staff members to have access to the powerful /evolve command, while also reducing the number of instances where a player makes a report to staff on the server, or in #support when their pokemon fails to evolve under the correct circumstances. This, while minor, frees up a few seconds of time for staff members that may be otherwise occupied.

**Comment by Hiroku** [comment]
@Rasgnarok if the node has been configured pls close

**Comment by Rasgnarok** [comment]
It's now live on the server, closing.
