### ISSUE TITLE
Outposts 

### ISSUE THREAD

**Issue by Quadehar97** [ObliqueNET/Server#1085]
Just wondering if this will ever be looked at its not a big deal for small towns but for the bigger ones that have more outposts then what shows up it the /outpost list there are then outposts that are hard for the town members to get to unless they use a limited number of /sethome they can have

**Comment by Rasgnarok** [comment]
I am not sure I understand - you want better display of outposts, or you prefer more outposts?

**Comment by Quadehar97** [comment]
Nvm it's now fixed
