### ISSUE TITLE
Quest book erroring sometimes.

### ISSUE THREAD

**Issue by menno516** [ObliqueNET/Server#1086]
I do not have a screenshot ATM, but sometimes when a player tries to open the quest book and view the quests it gives an Error null zone or something like that.

This started around 1/2 days ago, a relog can resolve the issue for the player but it should not happen

When I get more info I will send it here if it is steel needed by than.

**Comment by Rasgnarok** [comment]
I really need a timestamp so I can pull a log through. If you have time, let me know
