### ISSUE TITLE
Town user info and LG info showing up as [sponge] instead of usernames.

### ISSUE THREAD

**Issue by SmodJah** [ObliqueNET/Server#1092]
When trying to look at any town's /t info, [sponge] shows up in place of player's usernames, Certain LG info has changed to [sponge] aswell.

**Comment by Hiroku** [comment]
This is caused by the Sponge cache being cleared. When the players in question log in next, we'll again be able to load their username from their UUID again. Not a bug, or at least, not something we can actually do anything about
