### ISSUE TITLE
enter the dojo legendary quest

### ISSUE THREAD

**Issue by XxZephanxX** [ObliqueNET/Server#1094]
i spent some time with tkdowning with this quest the first problem i had with it was it told me to follow coords on a paper i didnt get he set me back a step and it didnt give it to me again so he showed me the coords the i went in to do the final boss after awhile of farming for this i got to the last fight i went to throw a master ball and i got the glitch where it continually was loading i waited a long time before i put in /endbattle and it told me i failed i figured i should put this in

**Comment by Rasgnarok** [comment]
Hi, can you please give me your username as well as the quest name, so I can forward to Quest Designers?

**Comment by PrimalCyndaquil** [comment]
Fixed. In addition, the quest has been futureproofed.
