### ISSUE TITLE
Transfer/Move Tutor

### ISSUE THREAD

**Issue by DiddyTheKid** [ObliqueNET/Server#1100]
Transfer and Move Tutor names keep switching back and forth. Small bug, but thought it should be known.

**Comment by Katadreme** [comment]
The NPC also changes skins too to add.

**Comment by DiddyTheKid** [comment]
They also do not keep any moves/prices saved. They get reset once you exit out of their edit mode.

**Comment by Rasgnarok** [comment]
This is a known Pixelmon issue, it's been forwarded to the tracker: https://www.pixelmonmod.com/tracker.php?p=2.
