### ISSUE TITLE
lost a ultra

### ISSUE THREAD

**Issue by ItsMedley** [ObliqueNET/Server#1101]
i caught a buzzwole about a minute before the server went down (about and hour ago) after the server relaunched, it was gone.

**Comment by ItsMedley** [comment]
i din't have a sc, but there has to be a way to check server files. I have been looking for this thing for real life days.

**Comment by ItsMedley** [comment]
ign ItsMedley

**Comment by Rasgnarok** [comment]
You'll need to ping me when you're online, and I can give you a random Buzzwole

**Comment by Rasgnarok** [comment]
Refunded
