### ISSUE TITLE
Pixelmon 8.2.0 arisen issues

### ISSUE THREAD

**Issue by Psiclefai** [ObliqueNET/Server#1102]
To start, after the new update to 8.2.0, quite a few people voted (including myself), and from that, my vote crate gave 16 ultraballs (where I spent some on a cufant). Since the reversion back before 8.2.0, the vote keys did not restore, thus I had lost some money.

Another issue with the reversion is that I spent 10k on a heart scale to teach one of my legendaries an otherwise unobtainable move, but since the reversion, I had lost the 10k, and the move was reverted as if the heart scale was bought albeit not used. 
(It probably says on my logs or the server logs, idk)

**Comment by Rasgnarok** [comment]
Can you give me your username and the list of the stuff lost? As far as I understand, you need 16 ultra balls, and 10k.

**Comment by Katadreme** [comment]
Since there was no response I assume it was just as Ras says, 16 Ultra Balls and 10k?

**Comment by Vohras2** [comment]
You've been refunded the 16 ultra balls and heart scale.

**Comment by Psiclefai** [comment]
Oops, sorry... That was essentially all, yeah (lol)
