### ISSUE TITLE
Some vouchers do not seem to work with the new 8.2 update.

### ISSUE THREAD

**Issue by tkdowning** [ObliqueNET/Server#1104]
Decided to start working on new breeds with the 8.2 update and tried using some vouchers. Of the vouchers I have used, only 1 has worked and the others don't let me confirm or just tab me out of the voucher option. IV vouchers work, but eggmove, nature, and gender voucher don't appear to be working for me. -tk

**Comment by Rasgnarok** [comment]
Can you three (Hiro, Ele and Faty) see if vouchers spit an error, and if so, can we get it updated please?

**Comment by fatyg5** [comment]
![image](https://user-images.githubusercontent.com/8277657/119240073-87b18000-bb1b-11eb-9d0e-e516ec33511c.png)
Hello and thank you for the report. Hiro, I assume you will be fixing so here is the error. Good luck o/

**Comment by Vohras2** [comment]
Fixed, as per Ras post in changelog.
