### ISSUE TITLE
lost ditto after restart

### ISSUE THREAD

**Issue by CuteCanary** [ObliqueNET/Server#1105]
hai I caught a ditto earlier today, but it disappeared after the server restarted. It had mild nature and 31 ivs in HP. I don’t remember the other ivs being anything special. was wondering if i could get it back ? xd
ign CuteCanary

**Comment by Rasgnarok** [comment]
Do you have any proof of it?

**Comment by CuteCanary** [comment]
all I've got is me saying I got it ):
I typed this in chat right after I caught it, then I msged booty about it
![image](https://user-images.githubusercontent.com/48975028/118348590-69df8c00-b519-11eb-9370-38ddb775ccb1.png)
![image](https://user-images.githubusercontent.com/48975028/118348605-7e238900-b519-11eb-9139-5b291e67e7af.png)
![image](https://user-images.githubusercontent.com/48975028/118348724-35200480-b51a-11eb-8602-212a1859d3fc.png)

**Comment by Vohras2** [comment]
Refunded.
