### ISSUE TITLE
Trace ability is not working at the start of a battle

### ISSUE THREAD

**Issue by PJLesure** [ObliqueNET/Server#1107]
When you lead with a trace ability mon it doesn’t say what the opposing mons ability is, instead it takes you straight into the battle screen.
<img width="1792" alt="Screen Shot 2021-05-13 at 8 21 37 AM" src="https://user-images.githubusercontent.com/77369060/118147451-70102400-b3c4-11eb-8412-3340ca72a38c.png">

**Comment by Vohras2** [comment]
Should report this to pixelmon, as it is probably on their side.

**Comment by Rasgnarok** [comment]
https://www.pixelmonmod.com/tracker.php?p=2
