### ISSUE TITLE
Texture pack Quest legend

### ISSUE THREAD

**Issue by TheArkJester** [ObliqueNET/Server#1109]
Moltres seems to have lost its texture due to the new update not sure if there are any other legends like this but just wanted to report that this one is broken, Tree also can confirm that his also does not work.
![2021-05-13_13 19 35](https://user-images.githubusercontent.com/84147710/118162538-e0cc3600-b3ee-11eb-81c5-42451dec868f.png)

**Comment by PrimalCyndaquil** [comment]
This will be fixed with the next texture pack update. Thanks for bringing it to our attention!
