### ISSUE TITLE
Fishious Rend

### ISSUE THREAD

**Issue by TheArkJester** [ObliqueNET/Server#1110]
Dracovishs new move Fishious rend seems to have an error where NPC battles swaps out a poke it fails instead of actually hitting (double damage).  Seems to work fine in regular player battles as tk and i were going through Anniversary Surprise where we saw it fail multiple times.

**Comment by Katadreme** [comment]
Mind testing this in a Singleplayer world? If you can replicate it in a singleplayer will mean it is a Pixelmon issue rather than server side, at that point will need to make a ticket on the Pixelmon bug tracker

**Comment by TheArkJester** [comment]
Seems to be a pixelmon issue just tested it in singleplayer.

**Comment by Rasgnarok** [comment]
Please report directly to https://www.pixelmonmod.com/tracker.php?p=2, since this is a mod's issue.
