### ISSUE TITLE
Adding Music Particle Effect

### ISSUE THREAD

**Issue by mosbuttpirate** [ObliqueNET/Server#1111]
As recommended by Ras I am putting my suggestion here:

Adding the Music Note Particle as an effect for the Particle Vouchers. As there are multiple colors instead of flooding the voucher menu with the a rainbow of notes, I would suggest the music note particle cycle in a rainbow. It never hurts to have more cool customizations for our Pokémon and with there being a good array of singing/music based Pokémon this is a pretty fitting particle effect.

**Comment by Vohras2** [comment]
Closing... for now. (hehehe)
