### ISSUE TITLE
Lost my lvl 100 jolteon after reset

### ISSUE THREAD

**Issue by MonkeeSprout** [ObliqueNET/Server#1112]
I had a lvl 100, 5/6 iv, max ev jolteon on the market before the reset and now i havent got it back. I had it on the market for 10000 with the magnet item. The ivs that were maxed were everything except defence and it was a jolly nature.

**Comment by Vohras2** [comment]
Should now be refunded thanks to Diddy.

**Comment by MonkeeSprout** [comment]
Thank you so much
