### ISSUE TITLE
TMs being destroyed

### ISSUE THREAD

**Issue by Psiclefai** [ObliqueNET/Server#1115]
Y'know how when you right-click a pokemon with a tm, but later choose not to teach the move?

As it turns out, some people have been asking around about their TMs being removed when they try precisely that.
Members include "Imagine" (Kirikoz), and I believe someone else, but couldn't find them...

**Comment by Vohras2** [comment]
This is a pixelmon issue and should be reported to them.

**Comment by Psiclefai** [comment]
Oops, misread Ras' message, sorry.
