### ISSUE TITLE
Quest Hint for Moonlit Memories (SPOILERS)

### ISSUE THREAD

**Issue by mosbuttpirate** [ObliqueNET/Server#1119]
SPOILERS AHEAD:

Ras wanted a tracker for this awful hint so I'll make one. So during the quest after you catch the Munna and give it to her the Quest NPC tells you to go to a "nearby" grand structure made of quartz and lapis and a treehouse in the night. Spoilers: It's in Ione... which no longer uses lapis but dark prismarine. Grand structure isn't the best description, I would personally use city. As for the second part which is a tree house, I'm not trying to pick a fight with any builders but this tree house (see attached) is pretty... unfinished. It's also small and kinda hard to find unless you tell them that there's wheat surrounding it.  Now for my personal suggestion for the hint: Within a tree house that is surrounded by wheat, nearby a city of quartz and prismarine. Something to that effect tells you that you're looking for a tree by a good amount of wheat, which is pretty easy to narrow down what does and doesn't qualify as a potential location compared to just tree house in a city with a lot of big trees. The second note swapping "grand structure" with "city" makes it easy for anyone who's been to the different towns to instantly think to look near Ione, which while was an early guess of mine, the treehouse was so hard to find and the hint was vague enough that you may think to look throughout Vanha for another "Grand Structure of Quartz and Lapis."
![notatreehouse](https://user-images.githubusercontent.com/35019889/120074216-c674a680-c0d6-11eb-8c50-b6da6fbfe51f.png)

**Comment by PrimalCyndaquil** [comment]
Hint has been changed to better reflect the location- It now references the wheat and flowers present on the island. Thank you for reporting this!
