### ISSUE TITLE
i was ban from discord

### ISSUE THREAD

**Issue by Pyromoss** [ObliqueNET/Server#1120]
i was ban from discord and i havent done anything on the server to be ban. Can i please be unbanned so i can link my account.

**Comment by Katadreme** [comment]
Tried searching for Pyromoss and found nothing, so would you mind telling me your discord username or ingame name.

**Comment by Pyromoss** [comment]
my discord username is Pyro   
(#0890 the number ifneeded)

**Comment by Katadreme** [comment]
You have been unbanned. Was over Discord Bot being overprotective, I apologise for that. You can rejoin now: https://discord.gg/B3XcYcR
