### ISSUE TITLE
Nyctophobia bugs

### ISSUE THREAD

**Issue by SmodJah** [ObliqueNET/Server#1122]
-Nyctophobia stage 8 "Deafeat Necrozma" not progressing after battle, and softlocking not letting players re-encounter Necrozma.
-Also reports of battle terminating mid-battle and giving failure dialogue.
-Player Axel_is_epic had an issue of capturing Necrozma in further parts of the quest, then the same step re-triggering allowing him to encounter and capture Necrozma a second time.

**Comment by PrimalCyndaquil** [comment]
This issue has been fixed. Thank you for reporting it in detail- its a big help.
