### ISSUE TITLE
PVP disabled regardless of /pvp on or off

### ISSUE THREAD

**Issue by SmodJah** [ObliqueNET/Server#1123]
PVP and Self-Damage is not currently possible, players cannot shoot themselves or others with a bow, the arrow travels through them instead. /pvp and /togglepvp seem to function, just doesn't actually change the ability to pvp, tested with another user who toggled pvp on, Cannot hit with melee of any kind or with a bow.

**Comment by Rasgnarok** [comment]
Still occuring?

**Comment by SmodJah** [comment]
Just tested, no forms of pvp are possible regardless of if /pvp is toggled on or off, including bows

**Comment by Rasgnarok** [comment]
Fixed as of last night.
