### ISSUE TITLE
Been banned for like 6 years

### ISSUE THREAD

**Issue by yershii** [ObliqueNET/Server#1124]
my friend got me and another one of our friends banned falsely years ago. we are still banned to this day for no reason. is there a process to us being unbanned

my IGN is currently Yershii

**Comment by yershii** [comment]
I'm not gonna have logs or anything. 

But me and 2 of my friends used to play on the server years ago. 

My friend shadowed_demon (I think is/was his username) got upset with me and izen_vol one day and falsely reported us for survival flight hacks which we didn't have. All we had was pokeradar which at the time was allowed(idk if it still is or not) I estimated 6 years because I was still in school when this happened however I can't give exact dates as the discord server we were in has since been deleted

**Comment by Rasgnarok** [comment]
Pokeradar was never allowed. I can see that the only hack you were banned for was fly hacks however, but usually, that requires proof. Obviously, after all this time, I too have no records of your ban. What server did you play on?

**Comment by yershii** [comment]
Back when we played it was just the one server named oblique as far as my memory serves. I say pokeradar was allowed because the players at the time told us it was and it was mentioned in the discord by people. I don't remember more than that. We just remembered the server when we started playing pixelmon again and forgot we had been banned until we tried to log in.

**Comment by Rasgnarok** [comment]
Considering you have been banned for that long, I am willing to unban you. I feel it's been long enough of a ban. Please make sure to read the /rules, and enjoy the server. Welcome back!
