### ISSUE TITLE
Also being been banned for like 6 years.

### ISSUE THREAD

**Issue by IzenVol** [ObliqueNET/Server#1125]
I have been banned for 6 years.  My friend said that I have stolen something from his house even though he misplaced it.  He went to the staff and said he was mistaken but I have still been banned since.

**Comment by Rasgnarok** [comment]
As I mentioned in #1124 , you'll have to give us a lot more information. Usernames, timestamps, chat logs, or game logs.

**Comment by Rasgnarok** [comment]
Bumping, I need your username please.
