### ISSUE TITLE
Ban Appeal 

### ISSUE THREAD

**Issue by SamuelNguyen1131** [ObliqueNET/Server#1128]
IGN: SamNguyen1
Ban Reasoning: X-ray
Reasoning: No real reason, I had an x-ray in my mod folder for my single player world and I guess it was detected by the admins
Appeal: For the past week I've been breeding eggs and just staying AFK at my base while it breeds/hatches, I was actually banned while AFK. Even if you look at the logs, I don't even think I went mining except for coal, and x-ray was not utilized as I know it is bannable on the server. I have removed the x-ray from my mod folder and it will not be done again. It was a nice 23+ days on the servers, wonderful staff/community, hopefully I get to be apart of it again. 

Thank you,

Sam

**Comment by Rasgnarok** [comment]
Unbanned, handled in DMs.
