### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by Psiclefai** [ObliqueNET/Server#1130]
In all seriousness, we do agree for no "hacks" upon playing, and as such the only hacks/cheats I used were passive and minor hacks such as auto-sprint and show-healthbar. I did implement some mods (like morph, where they can't be utilised on servers).

I cannot prove that I used what I say I used or anything (since any screenshot I take would look like I altered them), and my isolation in the server doesn't help much. Although, during my time in the server, I have not once tried to abuse what staff permit nor what I have (such as enabling op hacks).

**Comment by fatyg5** [comment]
I’m going to be absolutely forward with you, the use of _any_ hack mods, whether you “used” them or not is against our rules. You installed ForgeWurst which has some of the abilities you described as well as many others. Whether some of the mods abilities are allowed and some aren’t is regardless. 

This is my one and only warning for you. I’m changing your permanent ban to be one more day of a tempban, under the implication that you remove ForgeWurst and never use it again on our server. If you’re caught with any hack mods installed, _used_ or not, it will be a permanent ban with no chance of appeal.
