### ISSUE TITLE
Ban appeal for xray/texture modifications

### ISSUE THREAD

**Issue by TheBeardOfZeus** [ObliqueNET/Server#1131]
So, I was banned for xraying it says, on the server listing. I'm sorry that it might seem that way, but I spend hours a day mining and that's all I do. I have screenshots of my files and everything to prove I don't have the mod installed. I showed JAH the other day my files and all I have installed separately is JEI which he said was fine. 

https://imgur.com/a/y7yd8Qx

Again, sorry for the inconvenience. 

I can run anyone through my files via discord streaming if required as well.

**Comment by ElementalMP** [comment]
Settled in DMs and unbanned
