### ISSUE TITLE
/trylevelevo allows pokemon that evolve by being levelled up in a magnetic field to evolve 1 level earlier than should be possible

### ISSUE THREAD

**Issue by lexjo** [ObliqueNET/Server#1132]
Magneton, Charjabug and Nosepass can be evolved through /trylevelevo at levels 30, 20 and 1 respectively which should only be possible at 31, 21 and 2 for these pokemon due to the thunderstone evos not being implemented in pixelmon yet.

**Comment by Hiroku** [comment]
The JSONs for the evolutions need to be changed to specify a level, currently they have no level condition. I leave that decision to Vohras though

**Comment by Vohras2** [comment]
Migrating this to evo stone, as pixelmon actually has this already for charjabug and magneton. Nosepass... will just go ahead and add.
