### ISSUE TITLE
hello admins hope you are staying safe. ban appel

### ISSUE THREAD

**Issue by Rainingdimonds** [ObliqueNET/Server#1134]
hello, my name is Rainingdimonds please can you unban me I was asking for free ditto and leaching is wrong please can you unban me. I a really sorry. I will buy a key from the store if that ill help me get unbanned.

**Comment by Rainingdimonds** [comment]
hello

**Comment by Katadreme** [comment]
No.

**Comment by Rainingdimonds** [comment]
why

**Comment by Katadreme** [comment]
Why? Because you strung up a web of lies to get a free ditto, even going as far as making an alt discord account to prove your case. Lying and deception are quite heavy problems considering this is a pixelmon server, both of which is not welcome in server.
