### ISSUE TITLE
/Ec or /Enderchest not functioning on offline players

### ISSUE THREAD

**Issue by SmodJah** [ObliqueNET/Server#1135]
the /ec command for staff to view a player's enderchest does not function on players who are offline

"Exception from /enderchest
Could not find user with the name _____.
_____
^

Usage: /enderchest [<Player>]"

**Comment by Rasgnarok** [comment]
@ElementalMP Is this not related to the usernames issue? Should work offline

**Comment by ElementalMP** [comment]
Moderators were missing permission node `nucleus.enderchest.offline`, and therefore nucleus could not find a valid online player to inspect. Has been resolved.
