### ISSUE TITLE
i got banned and am sorry for what i did i didnt think i would get banned for it

### ISSUE THREAD

**Issue by NoJoKo1** [ObliqueNET/Server#1137]
I'm truly sorry for doing what i did i lied to a staff member to report for someone and I thought the person that i was helping report was telling the truth my user name for pokemon is NoJoKo

**Comment by Katadreme** [comment]
You can try apologising but you lie more than a rug. If you had been honest and more cooperative with staff, I would've taken that into consideration and quite possibly you could've been unbanned but no. Sorry.
