### ISSUE TITLE
The random quizes/trivia in-game not showing in Discord

### ISSUE THREAD

**Issue by Psiclefai** [ObliqueNET/Server#1139]
(Just as a heads up, I did Discuss this in #suggestions, to which Butler and Ras had added their perspectives)

Y'know how you're reading in #server, and then suddenly several people suddenly say "ice" or something, but there's not 'right answer' response sent by Mia, which leaves you curious about what it could've been or what the heck was going on?

I don't suggest letting Discord users answer it, but just letting you check on the quizes/trivia from #server so you can either help someone (if no one knows, but you do), or so you can learn and add it to your pool of knowledge. 
If you do let people answer the questions from trivia, then it's all fine, most users who do type in #server are linked. Although, some people in-game would be pretty unhappy if you win, despite not being able to join (it'd be another reason why you don't need to log-in but still be fairly successful).

^ But this is all assuming that I interpreted their messages correctly (that's why there're no quotes or references)

**Comment by Katadreme** [comment]
It does show up in discord now so will be closing this.
