### ISSUE TITLE
TM/TRs glitch with CarrotShop

### ISSUE THREAD

**Issue by Kirikoz** [ObliqueNET/Server#1144]
When putting up signs to sell TM/TRs, they are read as the same item rather than separate items. 

Example: I keep both ice and ground TRs in the same chest for storage purposes and link all the TRs separately like any other item. If someone buys any TR from that chest, it gives them the first TR in the chest rather than the specific TR. Say I bought a ice beam TR but the first TR in the chest is earth power, they would get earth power instead of ice beam.

**Comment by Vohras2** [comment]
That's because TM/TRs now are the same item with different NBT data. It's not something that we can edit.
