### ISSUE TITLE
/outpost list broken for users who had outposts in nether prior to nether reset

### ISSUE THREAD

**Issue by SmodJah** [ObliqueNET/Server#1147]
Any users who's town had an outpost in the nether prior to the nether's reset back to it's natural state now recieve an error when trying to run /outpost list

**Comment by SmodJah** [comment]
![image](https://user-images.githubusercontent.com/75085971/122563956-69d22f00-d077-11eb-83a9-8fd5f42b9532.png)

**Comment by Vohras2** [comment]
Closing for now as this is a known issue. Have anyone that has this issue make a new ticket here.
