### ISSUE TITLE
Please unban me.

### ISSUE THREAD

**Issue by Tyroned1** [ObliqueNET/Server#1159]
I was banned of the discord for saying deez nuts to a worker, please can I get unabanned I will not do this again, and I will never insult a worker again my disc is Tyrone#4589 AMEN.

**Comment by Katadreme** [comment]
Imma be real. I really despise trolls. Y'all just really have nothing better to do with your time huh. Against this bitter disliking I have, I will unban you from the discord, as a second chance. For the love of sweet jesus, don't repeat your actions.
