### ISSUE TITLE
im deeply sorry

### ISSUE THREAD

**Issue by TinfoilHat1** [ObliqueNET/Server#1160]
my bad i was being a bit SILLY :( i put on public chat repost if balls itches and i got banned. This will never happen again its all my bad guys :((((((. Hope we can all be homies till we dead lol, the acronym lol looks like a person drowning lmao

**Comment by TinfoilHat1** [comment]
lol
 ()
/ \

**Comment by Tyroned1** [comment]
Goodluck getting unbanned, although you did say some rather rude stuff in public chat I think the way you said ''the world lol looks like a person drowning'' it is very much correct XD, AMEN.

**Comment by Katadreme** [comment]
This is disgusting. Go find some other server to demonise.
