### ISSUE TITLE
Quest "The Heart of the Cards" triggers not functioning

### ISSUE THREAD

**Issue by SmodJah** [ObliqueNET/Server#1162]
Player Death_Space had issues on multiple stages of this quest.
Stages 6-8 all seemed to fail to trigger, Leaving the house, if step was progressed to the next stage  through '/questprogress set' they could not trigger the electabuzz fight, even after relogging, even then after skipping to the next stage, they were not able to progress by speaking to any of the 3 NPC's.

**Comment by PrimalCyndaquil** [comment]
Did you ensure the player had the "red card" item they had obtained previously? Is the player still afflicted with this issue? If so I can hop on and run the questdebug to find the issue.

**Comment by SmodJah** [comment]
I do believe the player did have the item on them while trying, for the time being they asked that their progress be set to 0 so they could continue other quests.

**Comment by menno516** [comment]
Hi zuko here, I mean Atred, I mean Menno.

Quest works fine like it is supposed to, if the player has been set to 0 it should be fixed.
Player would just need try again in that case.
