### ISSUE TITLE
nicokou ban appeal

### ISSUE THREAD

**Issue by Nicokou** [ObliqueNET/Server#1163]
Hello. 
I got banned around a year ago for "inappropriate behaviour and harassment". 
Basically, I and my friend were in the public oblique discord voice chat with your moderator "Kung of Sweden". He sat quietly while we were bantering so on so forth. I acknowledge that I said inappropriate stuff and was basically a pain in the ass for the whole staff team. 
I ask if I can get a second chance and get unbanned, as I spent a lot of time on this server a long time ago. 
 :)

**Comment by Nicokou** [comment]
Right, IGN: nicokou

**Comment by Katadreme** [comment]
It took a while but I finally was able to find some context your ban. It seems the harassment and inappropriate things that were said in the vc was excessive and intolerable to a point. Don't know whats so funny about harassing someone and saying such inappropriate things to which you can classify as 'banter' but anyways. Although you acknowledge you said these things, you haven't exactly apologised either and just asking to be unbanned like nothing happened. We didn't tolerate this behaviour before and we don't tolerate now. So I'm going to decline this appeal.
