### ISSUE TITLE
A bug with /invsee

### ISSUE THREAD

**Issue by tkdowning** [ObliqueNET/Server#1166]
So I decided last night to refund someone their items due to a misunderstanding by giving them shulkers into their inventory with /invsee. What I woke up to this morning was the person not having the shulkers in their inventory at all. I trust this person, although I did look around to see if they were placed and there was a potential scam, and I didn't see anything at all. So I refunded them with creative and then refunded the rest of their items that didn't show up on LG with my own stuff. But the shulkers never appeared in their inventory at all. Idk if that's because giving items to someone offline at the time doesn't work or something but it should be looked at.. thx

**Comment by Vohras2** [comment]
Going to just close this now, as it's possible it was a minor hiccup. Let us know if it happens again.
