### ISSUE TITLE
Ban Appeal attempt number 2: LimitlessJoker

### ISSUE THREAD

**Issue by LimitlessJoker** [ObliqueNET/Server#1167]
After providing new evidence to Ras and refurther explaining the situation and having abuse displayed publicly by another staff member about the first appeal, I would very much appreciate another opportunity to be unbanned from the server, I wish the situation would ease and drop but sadly since the ban it has only provided more issues. I'm kindly asking to be unbanned even in the case of a punishment has to be made in response for me getting unbanned for example a reset as I am very open to my mistakes which I'm very up mostly sorry for yes I will admit that I didn't mean to store abused items and for that I am truly sorry and it was not my intention but I am definitely most truly sorry for not reporting the issue to a lead mod staff member sooner rather than later. I will try to learn from this mistake in future if I ever become staff on a different pixelmon based server. But after some reflection time I would kindly at minimum like my access back onto the server I care about very much. And if starting from scratch is the case as punishment. So be it. I also would like my staff role back but I'm happy to just remain a normal bystander on the server like everyone else if that's what it takes.

**Comment by Rasgnarok** [comment]
Considering recent developments, I am going to go ahead and deny this appeal as well. Please do not remake them freely, as if there is a chance at an unban, it'll come from me personally.

Should you have questions, feel free to reach out. Some of the reasons to keep your ban are extremely private, and I feel they should not be publicized in such a way.
