### ISSUE TITLE
[Bug] Move Tutor Not Accepting Heart Scales with Descriptions

### ISSUE THREAD

**Issue by Treejan976** [ObliqueNET/Server#1169]
Issue is as stated in the title, acts as if there is no heart scale in the inventory when trying to use the move tutor in Ione if the heart scale has a description. This issue was first brought up by a player who had received such a scale from some staff event (probably a crate or gym battle). A normal heart scale was tested and worked just fine
![2021-07-17_22 37 11 copy](https://user-images.githubusercontent.com/72344461/126055044-68733f82-5904-435b-a3db-88008ba21cb9.png)
![2021-07-17_22 37 06 copy](https://user-images.githubusercontent.com/72344461/126055045-4143323c-92d6-4869-8362-20e4ae773627.png)

**Comment by Vohras2** [comment]
These will be replaced with ones without descriptions soon. Just have a mod change out any that still have lore on them.
