### ISSUE TITLE
Quest Glitches

### ISSUE THREAD

**Issue by Power-Note** [ObliqueNET/Server#1172]
I made the mistake of teleporting away from my Lugia final battle and glitched the entire quest. A mod on the server put me back a couple of steps but I think that messed it up even further. This was a couple of weeks ago and the quest now appears done at 74% but has disappeared from my current quest tab (only appears when I click on the legendary quest tab) 

Recently, I've noticed that the legendary quests I've completed in the past are showing up as not even started. I had a mod help with the Rayquaza quest but now the "A Blank Mind" quest (Celebi) is appearing in my quest book as not started. I've completed them both. At the moment I'm not sure which other quests are appearing as not started (if any) even though I have completed them.

**Comment by Vohras2** [comment]
Closing this, as it's over a month old. If you are still having this issue, reopen the ticket and we will get it sorted out.
