### ISSUE TITLE
/resetallquests cmd not working

### ISSUE THREAD

**Issue by Katadreme** [ObliqueNET/Server#1175]
Player Epix120 requested a player reset, which I did. When trying to reset their quests with /resetallquests command, chat said it worked: 
![Screen Shot 2021-08-08 at 4 07 01 pm](https://user-images.githubusercontent.com/50907133/128622674-0f75b2f6-b7d4-44b7-b6b5-f05199672613.png)

But their quests were not reset. Even after asking them to relog, questbook still says this: 
![Screen Shot 2021-08-08 at 4 07 14 pm](https://user-images.githubusercontent.com/50907133/128622701-f71259d5-30c4-46cb-9a2d-52815074aecc.png)

**Comment by Vohras2** [comment]
Closed as i'm moving this to the quest master list.
