### ISSUE TITLE
Lost Darkrai to /gift command to a user that reportedly doesn't exist

### ISSUE THREAD

**Issue by MedicalMaul** [ObliqueNET/Server#1179]
Tried to send Darkrai to quolzyy, accidentally typed quolzzy, darkrai got sent and no one can pull it. Asking for the Darkrai to be returned.
![SendingProof](https://user-images.githubusercontent.com/89060626/129666051-bb20199c-217b-4a3f-af75-2f00dd5db93b.PNG)
Can send the actual log instead if needed- quolzyy confirms they haven't seen the darkrai in their party/box.

**Comment by CptTCovenant** [comment]
Hello :D I have returned your Darkrai to you! Please check your PC next time you log in.

**Comment by Katadreme** [comment]
Closing since this was resolved.
