### ISSUE TITLE
Unable to Connect

### ISSUE THREAD

**Issue by MusicMichael** [ObliqueNET/Server#1180]
I was having trouble getting a pokemon I traded for from Cpt to lvl evolve so I asked how to fix it.  I used /trylvlevolve and it didn't work so I tried /suicide to see if lvlevo would work after death.  but after dying I couldn't respawn so I left the server now I can't connect.

**Comment by SmodJah** [comment]
What error are you recieving upon trying to connect to the server? Could you send a screenshot or any sort of logs?

**Comment by MusicMichael** [comment]
[image: image.png]

**Comment by Katadreme** [comment]
Going to close this since it has been resolved
