### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by BltchM0nkey** [ObliqueNET/Server#1181]
I was banned for typing one long message of the letter R. I typed that after another user typed the same message as a joke, I was not aware of that being against the rules. In the ban message it states I was talked to numerous times when I was only talked to once and that was about a different issue. 

-BltchM0nkey(Thats my GamerTag)

**Comment by Katadreme** [comment]
After checking any and all of your logs pretaining to server rule breaking, can see you were spoken to by a moderation staffer twice. The second time being where you were explicitly told to read the /rules of the server and that further rule-breaking from there on would result in a permaban, which is the case here. In the instance of which you were banned, were you spammed the 'R', you had a chance to erase your message of the 'R' spam, even after the staffer warning the previous player to spam 'R'. 

Taking into account the other offences you have committed, especially after lying about the base you claimed over, and this, I won't be unbanning as it seems evident you don't seem to take the server's rules seriously.

**Comment by BltchM0nkey** [comment]
yo can get unbanned yet

**Comment by Katadreme** [comment]
Read the comment above ^
