### ISSUE TITLE
Ban Appeal 

### ISSUE THREAD

**Issue by Sonictheeggnog12212131** [ObliqueNET/Server#1183]
I got banned from Xray I'm super sorry I wont do it again. I was in the server for about 2 weeks and I was unknown of this being cheating.
i will not do this again and I'm sorry.
Minecraft username- Sonictheeggnog
Discord - Hex#9691
feel free to contact me about the appeal

**Comment by Katadreme** [comment]
I've been given reason to suspect that you were aware that xray usage on the server was not allowed, but I'll give you the benefit of the doubt here. I've reduced your ban to a 1 day tempban starting from now.
