### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by ThyRedWolf** [ObliqueNET/Server#1184]
Hello,
So recently I was banned for stealing from a player, but I can justify why I did this.
A few days ago I met 2 people.  They had invited me to their town and I had joined. They made me an executive and told me I could take from peoples homes that quit/they had permission to take from. They told me a specific home was one I could take from, So I did take from this home thinking that they had full permission from the owner, who they had claimed quit. To my surprise the person who lived there had not quit. I had apologized and explained to the owner, and he was understanding and just wanted his stuff back. I paid a moderator the money so I would not use it furthermore, and I proceeded to get banned for 5 days.
As much as I did technically break a rule, it was only because of the fact the owner of this town gave me full permission to, and Lied to me about the whole situation. I am very sorry for my actions, and will make sure in the future that before even thinking about looking in someone's home I am allowed to be there and take from there from the owner of the home themselves. 
Again, I sincerely apologize for my actions and something like this will never happen again on my behalf. 
Thank you so much for your time reading this!
Discord: ThyRedWolf#4456
IGN: ThyRedWolf
Have a great day!

**Comment by Katadreme** [comment]
I am very sorry I didn't respond in time. Your ban was a 5 day tempban, and you have explained and sounded very genuinely in your appeal, so had I of responded earlier I would've said to wait out the 5 days. Again I apologise for my belatedness. Closing this now since your tempban has expired.
