### ISSUE TITLE
Im very stupid and got banned

### ISSUE THREAD

**Issue by Swagster-87** [ObliqueNET/Server#1187]
Title. I said a gamer word and screwed myself over because I didnt know it wasnt allowed. guess im just too used to CS chat lmao. If you decide to unban it wont happen again.

Ign; Swagster87

**Comment by Katadreme** [comment]
I too get CS and Minecraft mixed up all the time. Also it wasn't just a gamer word, you managed to get a whole gamer sentence out so although you sound apologetic, won't be unbanning you as it was quite filthy and we can do without it here.
