### ISSUE TITLE
Banned From Discord?

### ISSUE THREAD

**Issue by ThyRedWolf** [ObliqueNET/Server#1190]
Hello,
I was banned from the discord for a very dumb reason.
I sometimes send people on my friends list my discord server to promote my stream and try to grow, and since I sent it to everyone on my friends list, I got banned for self promo. Oblique mods are on my friends list and I'm not paying attention while pressing invite, so some invites went to them. I think this is a very stupid reason for me to get banned as I was not using oblique for personal promo, I was sending it to friends on my friend list.
Thanks for your time.

**Comment by Katadreme** [comment]
Sorry for the delay. I have unbanned you, but you're gonna need to be more careful next time. To explain, had several moderators inform me they received your invite which is similar to how we have dealt with mass invites from randoms, hence the ban. Please do be more careful
