### ISSUE TITLE
Softbanned, need help!

### ISSUE THREAD

**Issue by MusicMichael** [ObliqueNET/Server#1191]
I was slightly glitched, like not being able to "View All Quests" in /quests. I died and it was taking too long to respawn, so I restarted the game during the death screen. When I try to connect I'm met with "Disconnected".

**Comment by MusicMichael** [comment]
I'm technically still logged in and that's preventing me from logging in. I can't remove the double of myself.

**Comment by Katadreme** [comment]
Closing now since its been sorted
