### ISSUE TITLE
/hadpoke command update suggestion

### ISSUE THREAD

**Issue by Menno165** [ObliqueNET/Server#1196]
The /hadpoke quest only tells you that the player has caught that Pokémon, if possible maybe make it so that it can also give some information, for like special textured Pokémon/legendary "when was it, where was it, what texture does it have, is it shiny, ability"

This might be a lot of data to run for the server, so maybe limit it to sections,
if its for a normal Pokémon it will give you only the information of the last Pokémon that you encountered. so a 10/10/2021 Ratata will be changed for a 11/10/2021 Ratata.

If its a mythical/legendary it will have one for wild and/or one for special textured ones.

A example of how I kind of imagine the command to work is that when you hover over the Pokémon, or click the Pokémon's name, it will show/send the info to you in a order like:
- Is it shiny? true or false
- What ability does it have
- Does it have a special texture
- Where was it caught
- When was it caught
- (more optional could also be " what move set, what ivs, what evs, size, nature ect)

**Comment by Vohras2** [comment]
/hadpoke is a command that isn't from one of our mods. Pretty sure it's from one of either pixelextras or the evenmorepixelmoncommands mod, so we don't have the ability to extend the usage.
