### ISSUE TITLE
Stutter every 5 seconds just on Oblique servers

### ISSUE THREAD

**Issue by kilo1243** [ObliqueNET/Server#1203]
Ive talked with teammates and have had a chat with staff one night with a couple people complaining of the same thing. I have done everything on my end aswell to solve the issue but the problem persists its a constant small freeze every 3 - 5 seconds. At first i thought it was shaders but moving to any other server and stress testing that way has only showed that it is only only the Oblique server. I cant do anything more on my end with hours of troubleshooting and want to see if anything can be the cause server side making this happen. Thankyou :D if you need anything else let me know

**Comment by Vohras2** [comment]
Closing as the reason for this has been discovered.
