### ISSUE TITLE
Ione under Terra instead of Towns

### ISSUE THREAD

**Issue by CaptainTCovenant** [ObliqueNET/Server#1205]
Doing /warps, ione will show in the terra tab instead of towns
![Screenshot_46](https://user-images.githubusercontent.com/92965754/139604199-3ff6c869-d928-45bf-be86-34398f1fe8f5.png)
.
![Screenshot_45](https://user-images.githubusercontent.com/92965754/139604205-e2256d94-db1b-4ed9-8e21-3e40732ab74d.png)

**Comment by Vohras2** [comment]
Fixed.
