### ISSUE TITLE
Ban Appeal LimitlessJoker

### ISSUE THREAD

**Issue by LimitlessJoker** [ObliqueNET/Server#1206]
Hey Guys its me again, any chance I could possibly have a second chance to play on oblique again - i don't want the staff role if the choice is given of course ill accept it back but i mainly just want the ability to play again. My therapist has told me as part of my recovery to tackle all things that have affected me in life and sadly its now led up to this.

I'm just hoping a second chance could be offered but if a longer cooldown for me is still needed then i will happily accept that too.

**Comment by fatyg5** [comment]
Unfortunately, your therapist means nothing to the things that have happened or to me. I will not list anything here, in respect for you and others involved, but everything done is against our rules and will not be tolerated or pardoned now or any time in the future.

Thank you for the appeal.
