### ISSUE TITLE
Ribbon Voucher Suggestion

### ISSUE THREAD

**Issue by GracieTheLatias** [ObliqueNET/Server#1209]
With the newest 8.3.3 update, there is a way to add ribbons on pokemon through use of commands. I think having vouchers for these ribbons in crates would be a nice cosmetic thing to sink money into

**Comment by Vohras2** [comment]
Not sure if we will look into adding them specifically to the voucher system, since it needs to be recoded. However, you will for sure be seeing more ribbons in the future! Crazy Crates have already picked them up with more to come hopefully.
