### ISSUE TITLE
Level Evolution bug

### ISSUE THREAD

**Issue by ReverentDeath** [ObliqueNET/Server#1210]
What's happening: So I have encountered a repeating problem when it comes to evolving pokemon. When my poke's hit the level they are supposed to evolve at after a battle, the pokemon appears beside me as normal. Except they don't have the coloured sparkles nor any animation. The text box immediately state it has evolved, but into the pokemon it already was. Ex. "Shuppet has evolved into Shuppet."  It's has happening with a shuppet, a Pidgy, and an Oddish. /Trylevelevo doesn't work to fix it and leveling the pokemon up again doesn't trigger evolution either. 

Background Info: I have a Crazy Crate mon, Dusknoir (It started happening after I got it) and I'm now using an EXP. ALL; These are the only things I can recall that have changed before and after the Bug started happening.

**Comment by GracieTheLatias** [comment]
With that bug you should either relog then level it again or do /suicide then level again

**Comment by Vohras2** [comment]
Only way to fix is as Gracie said.
