### ISSUE TITLE
Ban appeal for "freddypwner"

### ISSUE THREAD

**Issue by freddypwner** [ObliqueNET/Server#1211]
I used to play on this server a few years ago, then just over a year ago, and I was a huge asshole. Every time I beat a gym leader I would call them trash and flame them, and I even took it to the Discord one time. I was a huge asshole. It's been about a year and I haven't been able to stop thinking about this server and I really want to be able to play on it again. I grew up with it, and I've grown up now, and I want to be able to revisit it again. I'm sincerely sorry to all of the gym leaders I insulted, including but not limited to those from Ione, Agni, and Tesla. I am much more respectful now, and I will never insult others on the server again. My Discord is SoYeah,ImAGamer#2585.

**Comment by Katadreme** [comment]
You were banned in Februrary of this year, and i appreciate your sincerity and genuinity in facing your transgressions and owning upto your toxicity towards the gym leaders. However, there are only so many chances we can give you. You've been previously tempbanned for a non-related issue but after that and the ample chances and second chances you had after going after the gym leaders, I'm sorry but the banks depleted. I'm happy you've learned from your mistakes so lets not make them again on other servers.
