### ISSUE TITLE
Sableye can't learn gravity

### ISSUE THREAD

**Issue by PenginKami** [ObliqueNET/Server#1215]
![2021-12-30_17 53 48](https://user-images.githubusercontent.com/96862959/147732633-012f8f86-8fb3-4873-83c5-51c5b7bc4dc0.png)
![2021-12-30_17 54 00](https://user-images.githubusercontent.com/96862959/147732655-e50ad77b-6f0a-4807-853f-9a078353a236.png)

On the wiki it says sableye can learn gravity from transfer, but the transfer tutor will not allow it to learn it.
It can get it from move tutor in usum.

**Comment by CaptainTCovenant** [comment]
Hi there Kami! I tested it on a single player world, and my findings was that sableye cannot learn Gravity there either. So it's a Pixelmon bug. 
Recommend posting it on the Pixelmon tracker: https://www.pixelmonmod.com/tracker.php
![Screenshot_74](https://user-images.githubusercontent.com/92965754/147798315-e8ba8667-e94c-4e3e-8483-a57286bdeb42.png)

**Comment by Vohras2** [comment]
Fixed.
