### ISSUE TITLE
Wishing Star not being applied to new players.

### ISSUE THREAD

**Issue by CaptainTCovenant** [ObliqueNET/Server#1216]
I am not entirely sure how players obtain Wishing Star, as heard both of "Just by logging in" and "beating a wild mega boss giving both keystone and star" 
However, have noticed that players joining after the server updated to 8.3.6, have not been getting a Wishing Star and seems nobody knows why. 
Here is a screenshot from Clockwork13_'s inventory (joined Dec30), as well as KokryuKami's inventory (Joined Dec26)

![clockworker](https://user-images.githubusercontent.com/92965754/147849872-361f5492-4c1e-4b3c-b517-e8faa8ef5082.png)
![Kokryu](https://user-images.githubusercontent.com/92965754/147849875-3f450c01-268c-4d66-b311-be0ef392566a.jpg)

**Comment by Vohras2** [comment]
Assuming this is the dynamax band, yes? If so, it's been fixed.
