### ISSUE TITLE
unban discord

### ISSUE THREAD

**Issue by therealfazejesus** [ObliqueNET/Server#1217]
pls unban me i have changed my ways i have had a hard long talk with a staff member no names mentioned and he has put me on my final warning all i did was say i dont do pronouns because i think they are a load of bullshit you are born whats between ur legs man or woman get used to it hitler was a man he didnt identify as a woman- love the real faze jesus if u want to unban me my discord is the real faze jesus#4043

**Comment by therealfazejesus** [comment]
free my mans the real faze jesus

**Comment by Katadreme** [comment]
Please take your transphobia someplace else. And while you're at it, learn some manners.
