### ISSUE TITLE
skill reset

### ISSUE THREAD

**Issue by lindatjuh** [ObliqueNET/Server#1218]
Hi I've been mining away today to craft some disks for pokeballs. I smelted everything and shot up to lvl 5 in smelting. I got the furnace stash abbility and tried it out. even stored the furnace. then a server reset happened about 3-4 hours later and when I thought of checking my last furnace after all that time it suddenly claimed I gained the experience for up to level 2? so I checked my skills. everything was normal and nothing changed except my smelting skill apparently got reset back to 1? no one can tell me whats going on... before that I also had problems with not even gaining exp for mining or chopping wood..... (which still isnt happening)

kinda regards,

Linda

**Comment by Vohras2** [comment]
Mining and Woodcutting skills are disabled currently due to conflicts with our claiming plugin that we are working on sorting out. What's your IGN and I will restore your smelting level.

**Comment by lindatjuh** [comment]
My ign is lindatjuh,  thank you!

Op ma 10 jan. 2022 14:35 schreef Vohras2 ***@***.***>:

**Comment by Vohras2** [comment]
Alright, your smelting has been set to 5.
