### ISSUE TITLE
Unban on Discord server!

### ISSUE THREAD

**Issue by ThyRedWolf** [ObliqueNET/Server#1226]
Hello,
So I just today decided to get back onto the server, and realized I was banned on the discord server. I would like to explain my side of the story, and request an unban from the discord server! Starting off, I am a small content creator. I will sometimes see random people on my friends list (added as a friend) and send them my discord server link (gain some more clout). One of these people, who I think might have been staff I don't remember, got sent the link since they were on my friends list. I'm guessing I got reported and banned for it, though I was not intentionally using members of Oblique to promote my discord. I know that self-promo is not allowed in the server, but I did not intentionally send the server to people in oblique. If possible, could I have an unban on the discord server? 
Discord: ThyRedWolf#4456
IGN: ThyRedWolf
Thanks again!

**Comment by Katadreme** [comment]
Hello again, sorry for the delay in responding. I remember this similar story when you were first banned for the same thing to which I unbanned you and then you did it again. And unluckily for you, the 2nd time you were caught was by our server owner herself. So you had your chance and sadly didn't learn from it so will not be unbanning.

**Comment by ThyRedWolf** [comment]
Hello again,
If I can have some sort of context, how the heck is it my fault that discord put these people in my INVITE FRIENDS menu… I didn’t purposely invite them as it’s against the rules on the server. It isn’t my fault discord said they were in my friends list. As much as I understand your concern, it’s not going to happen again. I have no need to do the same thing I have done in the past since I am growing using twitch and not randomly advertising on discord using the INVITE FRIENDS menu might I add again. This ordeal is quite frankly not my fault, and discords for again, putting these people in my INVITE FRIENDS menu. 
This is kind of just an annoyance at this time, and if you would like to see a example of this happening, I will gladly send a video of discord showing people that are not my friends in the INVITE FRIENDS menu on my server. 
thanks again,
ThyRedWolf

**Comment by ThyRedWolf** [comment]
@Katadreme 
Hello again,
If I can have some sort of context, how the heck is it my fault that discord put these people in my INVITE FRIENDS menu… I didn’t purposely invite them as it’s against the rules on the server. It isn’t my fault discord said they were in my friends list. As much as I understand your concern, it’s not going to happen again. I have no need to do the same thing I have done in the past since I am growing using twitch and not randomly advertising on discord using the INVITE FRIENDS menu might I add again. This ordeal is quite frankly not my fault, and discords for again, putting these people in my INVITE FRIENDS menu.

**Comment by Katadreme** [comment]
Dont blame discord for sending the invite. We told you to be careful and not do it again and you did it again.

**Comment by ThyRedWolf** [comment]
I am not blaming discord for sending the message. Im blaming discord for putting these people where my invite friends is. It already takes long enough to invite people, let alone check every one to see if they are on your server.
