### ISSUE TITLE
/ag Command doesn’t work for me

### ISSUE THREAD

**Issue by PJLesure** [ObliqueNET/Server#1228]
<img width="1213" alt="Screen Shot 2022-02-18 at 9 09 34 PM" src="https://user-images.githubusercontent.com/77369060/154787214-311d7682-7b97-47d0-9356-5aeff9988d56.png">
When trying to do /ag, chat gives me this error. Dough asked me to wait until the server restart to see if it persisted, and it did. (Also, this is only a problem for me.)

**Comment by PJLesure** [comment]
So, any progress on a fix for this?

**Comment by ElementalMP** [comment]
Closing as we have no way to reproduce or test fixes to this issue. It can be reopened if the issue crops up again.
