### ISSUE TITLE
Ban appeal- elatal8254

### ISSUE THREAD

**Issue by tapetaxd** [ObliqueNET/Server#1234]
hey everyone reading this, my name is elat and i was banned from this server on the count of raiding... im not sure what exactly is that and i dont recall doing this, and if i did i am sorry. its been atleast a year and i belive its been even longer.. i wish to return and play on this server if possible.

thank you all for reading this and i wish you all the best of regards.
(sorry for my english <3)

**Comment by ElementalMP** [comment]
Hi! I've reviewed this ban, and it was quite some time ago. I am one for second chances, and you've been respectful, so I have unbanned your account in good faith. Enjoy!
