### ISSUE TITLE
Ban Appeal - Yaporeo

### ISSUE THREAD

**Issue by Yaporeo** [ObliqueNET/Server#1235]
i was banned for simply saying  "sex" 
it was an insta-ban 
i didn't know i couldn't say sex. i thought swearing was okay, because i saw someone say the F word. my friend on the other hand [joshiewoshiepoo] said the n word so he would be banned too. hes black, dont worry.
i hope i can be let back onto the sever because i love the map and the community. i understand if i am still banned. thank you.

**Comment by fatyg5** [comment]
I was considering the unban in the first half of your appeal, but considering the second half is a poor joke, you won't be unbanned.
