### ISSUE TITLE
Discord Unban

### ISSUE THREAD

**Issue by ThyRedWolf** [ObliqueNET/Server#1241]
Hello,
So I have gotten back into Oblique recently again, and wanted to apply for an unban on the discord server. I was originally banned for an accidental self promo, which I take the blame for but was not necessarily my fault. Last year, when I played this server, I had been into streaming and wanted to grow, so I had sent my server to every person on my friends list. What I did not know was discord had the menu set up to friends of friends, recommended friends, etc. One of the people on this list had happened to be a moderator on oblique, which the most likely scenario for this was me DM'ing mods with concerns, and discord recommending them on this list. I had never had the intent of breaking a rule, but take responsibility for the actions that took place. I am deeply sorry for the breaking of this specific rule, but not being able to interact on the server is an annoyance and makes me lose motivation to play on the server more than I already do.

I would like for whoever is reading this to consider unbanning me, because it really was just an honest mistake.
Again I am very sorry for my actions, this will not happen again (also due to the fact I don't share my server anymore because of this reason LOL)
-ThyRedWolf
ThyRedWolf#4456 is my discord

**Comment by CenizaRey** [comment]
Sorry for the delayed response. I'm satisfied this was an honest mistake and I'm happy to say you're unbanned from the Oblique Discord, just please be more careful next time!
