### ISSUE TITLE
Killerdom733 Ban appeal 

### ISSUE THREAD

**Issue by killerdom733** [ObliqueNET/Server#1247]
You may not remember me but my account on Oblique was killerdom733. 
So a few years ago I was banned for taking my friends master ball without paying him back. And I also believe part of my ban was that I took things from him many times and got many warnings which I completely agree with and I should not have ever done that. I have matured over the years and I believe that I am ready to come back to the server and not break any rules. I completely understand if you do not accept this ban appeal due to me breaking the same rule on the server over and over. I take complete responsibility over my actions in the server. Thank you for your time if you read this. And I hope that we can put my bad actions behind us  just this once. And become friendly with one another once more.

With my utmost apologies killerdom733

**Comment by MissElyri** [comment]
I have taken some time to read over this ban appeal and let it simmer. At first, the severity of your actions that caused the original ban made me want to deny this.

However. Knowing who you were then, and seeing your interactions with others on discord as of late, I have taken your ban appeal as being an honest apology. To me, it seems as if you have indeed made a night and day difference in terms of maturity and communication. Taking your history into consideration, though, I can firmly say that there isn't much room for error here. 

I have decided to unban you. Welcome back to Oblique!
