### ISSUE TITLE
Drericeto ban appeal

### ISSUE THREAD

**Issue by billy420blazeit** [ObliqueNET/Server#1253]
can i be unbanned pwease 
🥺👉👈 
❤️ ❤️ ❤️ ❤️ ❤️

**Comment by billy420blazeit** [comment]
no i am a changed person

**Comment by ElementalMP** [comment]
For the sake of fairness, I will reopen this on the off chance you have a legitimate appeal this time around. How are you changed?

**Comment by billy420blazeit** [comment]
i dont say disrespctful things any more. also I don't want u to die because ur a nice person
🥺👉👈
❤️ ❤️ ❤️ ❤️ ❤️

**Comment by fatyg5** [comment]
That's not really a better appeal. Gonna deny and close.
