### ISSUE TITLE
Can we add a way to see completed quest steps?

### ISSUE THREAD

**Issue by Rocker113** [ObliqueNET/Server#131]
Can we add a way to see your currently completed quest steps? I feel like this would help those who forget key parts of the quest which then leaves them stuck and unable to continue.

**Comment by Rasgnarok** [comment]
Celes02/19/2018
Well since it seems the wildfire is over with, how about a way to know what quests you've completed?
Pulling from #suggestions channel in our Discord. Probably a good idea to eventually have 'Completed Steps' and 'Completed Quests'.

**Comment by Vohras2** [comment]
Closing, as extremely old and not sure if it will be functional with new quest plugin or not.
