### ISSUE TITLE
Compiling all /kit books into a single command booklet

### ISSUE THREAD

**Issue by BlitzAsogi** [ObliqueNET/Server#141]
Since people keep complaining that /kit books is annoying to sort through, plus it creates lots of junk, possibly combine them all into a single command that functions like /quests, where all the books are accessible thru a menu inside a book itself.

**Comment by Bontoose** [comment]
You could also just add some of that info to a type of intro quest, Like Ev Training could be taught via a quest as well as breeding... just a thought don't mean to hijack

**Comment by Hellblox** [comment]
![image](https://user-images.githubusercontent.com/72059360/94513274-4cf58300-01ec-11eb-92c9-ce6897f04b4f.png)
he bullied me

**Comment by Hellblox** [comment]
![Screenshot 2020-09-29 003721](https://user-images.githubusercontent.com/72059360/94513297-5d0d6280-01ec-11eb-8bf2-c5a778e5a7c6.png)

**Comment by Rasgnarok** [comment]
Closing in favour of the master ticket, WIP.
