### ISSUE TITLE
/wiki issue (post any that you find with an issue here)

### ISSUE THREAD

**Issue by McConnell2111** [ObliqueNET/Server#391]

**Comment by McConnell2111** [comment]
/wiki gible rarity (gible does not spawn)

**Comment by Valjean42** [comment]
/wiki sneasel rarity OR /wiki weavile rarity, same problem as McConnell's (Sneasel/Weavile does not spawn)

**Comment by Hiroku** [comment]
These seem like issues with PixelExtras more than anything else, since /wiki isn't ours

**Comment by Rasgnarok** [comment]
This should be reported directly to the PixelmonMod, https://pixelmonmod.com/tracker.php?p=6.
