### ISSUE TITLE
[Master Ticket] Custom Legends

### ISSUE THREAD

**Issue by Rasgnarok** [ObliqueNET/Server#413]
Please post here all your custom legend issues - especially the ones related to Quests not giving any special legend at all. If you were not able to get one as expected, a QD will reset you. 

Provide:
- Username in-game
- Legend Name
- Quest Name
- Timestamp (eg, "Dec 1st, 5PM EST)

**Comment by McConnell2111** [comment]
McConnell2111
moltres
Avenging flames
Dec 1st 19:43 GMT 
WORKS

**Comment by Ranger17** [comment]
Ranger17
Jirachi
Flute of the Pure Note
Dec 1st 12:54 PM
Texture not working, I have the 2.7 pack...

**Comment by Ranger17** [comment]
Ranger17
Magearna
Project-TALLOW
Dec 1st 8:38 PM
Texture also not working, also have the 2.7 texture pack enabled.

**Comment by McConnell2111** [comment]
McConnell2111 and megagamesdr
moltres
Avenging flames
Dec 2st 16:41 GMT
DOES NOT WORK

**Comment by GenesisAbsol** [comment]
GenesisAbsol
Phione
A Soul for a Soul
Dec 1st around 16:20 CET
No Special texture not Battle ready moveset

**Comment by GenesisAbsol** [comment]
Genesis Absol
Moltres
Avening Flames 
Dec 3rd around 16:00 CET
No Special Texture nor Battle ready Moveset

**Comment by GenesisAbsol** [comment]
Genesis Absol
Articuno
The Monarchs Labyrinth
Dec 4th around 3:25 CET 
No Special Texture nor Battle-ready moveset

**Comment by GenesisAbsol** [comment]
Genesis Absol
Jirachi
Flute of the Pure Note
Dec 4th around 12:30
No Special Texture nor Battleready Moveset

**Comment by reaginicfiddle** [comment]
reaginicfiddle
Moltres
avenging flame
nov. 29th 4am cst
no move set or texture

articuno
the monarchs labyrinth
dec 1 10 am cst
no move set or texture

Aself
enter the dojo 
Dec 1  12 pm cst
no move set or texture

**Comment by ZackieKun** [comment]
ZackieKun

Moltres
Avenging Flame
December 3rd (About 9PM CST)
No move Set (Not sure about texture as I don't have the pack)

Articuno
The Monarchs Labyrinth
December 3rd (About 10PM CST)
No move Set (Not sure about texture as I don't have the pack)

**Comment by Rasgnarok** [comment]
I'll ping the QDs so refunds can get started, it should have been fixed with @Hiroku 's recent changes. Have we restarted Hiro?

**Comment by BlitzAsogi** [comment]
@Rasgnarok the above people have been restarted, they've reported getting the correctly spec'ed mons

**Comment by fatyg5** [comment]
I think this can be closed. Reopen if I'm mistaken.
