### ISSUE TITLE
Erudi Quest Path

### ISSUE THREAD

**Issue by starwarschamp4** [ObliqueNET/Server#418]
I've seen this a few times, don't know if it happens to the other guilds. Recently in #terra-support, someone couldn't advanced down the Erudi quest path. From what I saw last time this happened, it said they weren't in Erudi guild, even though they chose that path. From the looks in the files, it might be the trigger delays being the same, but can't get on to test anything.

**Comment by PrimalCyndaquil** [comment]
This is a thing with /sudo not working well with guild join. In future tell players to do /guild join <guild>.
