### ISSUE TITLE
Quest Issue

### ISSUE THREAD

**Issue by WickedShadow498** [ObliqueNET/Server#424]
For the Quest: Enter the Dojo it appears to have gave an extra catch trigger. Apparently the first catch was said it failed and they also got the legend and it forced battled another one which was also caught. Not sure if its just a random bug that happened or if it was caused by the reworks of the quest.

**Comment by PrimalCyndaquil** [comment]
This has since been fixed as far as I know, or was a one-time issue as I cant reproduce it right now.
