### ISSUE TITLE
Guild Quests Distinction

### ISSUE THREAD

**Issue by Lieren-HuntGhosts** [ObliqueNET/Server#430]
I have noticed Guild Quests cant be differenciated from any other quests. in /quests they appear as regular quests, and there is no section for them in /questlore. This happens with all Guild Quests. This can be easily solved with either creating a section for them in /questlore , and adding a ''tag'' in /quests (Example: **Flight of the Light Brigade** Chatter has been heard... and see if you can learn more -Vulpe) [I dont really know what guild that quest is for] Basically adding a tag at the end of the description, so people are able to know which guild that quest is for.

**Comment by Soshisen** [comment]
This will be fixed in the next big update. Stay tuned
