### ISSUE TITLE
Berry Growth balancing

### ISSUE THREAD

**Issue by PrimalCyndaquil** [ObliqueNET/Server#443]
Suggestion: Lower the time needed to grow berries if it is currently at its default. The time taken to grow berries is ridiculous at its default and un-needed as we cannot sell the berries we grow. Even to to other players, they are sold for very little amounts. 
The default berry growth rate is _1-2_ real days for the berries that have any use, breaching 60 hours for the rarer ones which is a lil crazy considering you can get only up to 9 berries per yield.
I understand that, with the introduction of Lures, they're a bit more valuable, but it feels worthless to wait days for just berries.

**Comment by PrimalCyndaquil** [comment]
Nevermind that, seems a few of my berries were glitched and frozen in the seedling phase, making me think the server used the defaults. based on the growths of the other ones I think we already have a faster rate?

**Comment by Vohras2** [comment]
Closing this since it seems to be a glitch.
