### ISSUE TITLE
UnsafeAbilities Spec not working atm.

### ISSUE THREAD

**Issue by PrimalCyndaquil** [ObliqueNET/Server#445]
I have posted about this before in lore and other channels, but it gets quickly buried so I figure I should post it here. Unsafe Abilities is currently not working, as I tested it with a quest in the QD Training Area. both ua:Magic_Guard and ua:MagicGuard do not work, and just provide a mon with their normal ability.
Reason I'm posting this now is cuz if it ain't fixed there'll be more people that will have to get their legendaries modified by a lead, especially considering two of them (phione and articuno) are common quest legends to have.

**Comment by PrimalCyndaquil** [comment]
Steps to reproduce: Use the ua: spec in a command/give-pokemon trigger.

As examples, these commands were all tested and all of them yielded a Pikachu with Static rather than the specified ability.
/pokegive PrimalCyndaquil Pikachu ua:Fluffy

/pokegive PrimalCyndaquil Pikachu ua:SwiftSwim

/pokegive PrimalCyndaquil Pikachu ua:Swift_Swim

/pokegive PrimalCyndaquil Pikachu ab:Fluffy

**Comment by Vohras2** [comment]
Closing this as we found a workaround.
