### ISSUE TITLE
Voting rewards

### ISSUE THREAD

**Issue by forbiddenarcher** [ObliqueNET/Server#448]
My main idea is a monthly reward system where if. Someone votes for the full month they get a legendary or ultra beast at the end of the month if u miss a day of voting u lose that oppertunity till the next month but every 7 votes prior to the top prize u get a ultra rare poke and any other votes could be money or masterballs or a stack of coal blocks or iron blocks etc.

Add a calender to show all the rewards for the month except for the legendary

And if i may suggest the first vote prize should be the a Pokemon you choose as the server "mascot" this way the first day everyone has 3 pokes to start their start their carry over and the mascot

**Comment by qnom** [comment]
We are mainly trying to keep legends a rare occurrence on the server. Though your idea isn't bad, we do have rewards already for consistent voting which we believe are generous. I'll keep this issue open though in case anyone else wants to comment on it.

**Comment by Vohras2** [comment]
We already have vote rewards for hitting certain milestones, and like Qnom said we are trying to keep legends rare. Thank you for the input, but I can't see us implementing this idea.
