### ISSUE TITLE
Ban appeal for members of the town "Smyk"

### ISSUE THREAD

**Issue by Venyl** [ObliqueNET/Server#451]
So from what I understand we (Venyl [me], Wenyl, MoloCreator, SzefowaMaja, Niebezpieczny) got banned for "knowingly abusing a loophole in the kit system", here's what happened:
1.Right after we discovered this glitch we informed 2 staff members about it. Their nicknames on discord I think are: Elemental#0002 and Sunday15th#5744
![unknown](https://user-images.githubusercontent.com/63075314/78300695-2fdf4080-7538-11ea-8383-91caec8b4283.png)

2.As you can see your staff members let us keep the items as a reward for discovering and informing you about this bug

3.Even before they let us keep the items right after we discovered the loophole we decided that we shouldn't use the items for now or that we should just throw them away and we did that.

I don't think it's okay that some people in your staff were okay with this and told us everything's fine and now we're getting banned out of nowhere. I hope that you will positively examine what I wrote above and look at the situation from our point of view.

**Comment by ElementalMP** [comment]
In-Game I asked you guys not to abuse it and even here you say the items were destroyed. Despite this, y'all have #2 on baltop, and also continued to redeem the kit after you talked to me and were told not to abuse it. When I said you could keep the items, that was of the the understanding that you only had an extra copy of the items, not that you and all your mates were sitting down spamming the shit out of it behind my back. Even if you did destroy the items, where did you put the money? Money can't be destroyed as easy, and to my knowledge you didn't move it away.
