### ISSUE TITLE
Quest book: Toxic Crook

### ISSUE THREAD

**Issue by menno516** [ObliqueNET/Server#454]
when entering the ship you have to fight 5 people on that deck before you can go to below deck and fight npcs there.

the npc their hints arent really matched up.

i only saw 1 hint that was for the wrong npc so that might means that the others also have the wrong hints for them. (cant see the hint if you defeat a npc)

so for like 4 defeated and 1 left, the hint is useless because its wrong.

**Comment by starwarschamp4** [comment]
The pirates you fight match their hints, quest works as intended
