### ISSUE TITLE
Drop item clearer 1) gets stuck in a loop and 2) deletes shulker boxes

### ISSUE THREAD

**Issue by plasmarob** [ObliqueNET/Server#457]
It will say items being cleared in 30sec, every 30 sec, for 10+minutes in a row where you risk losing an item somewhat indefinitely. This happened just now, but also about a month ago.

This has happened for the third time to Stormy_DLoA now.
The item clearer keeps killing items that are less than a second old. It should leave the items less than, say, 10 sec old or something.
We keep losing shulker boxes to it.

Lucky this time it wasn't anything valuable, but the lack of trust is upsetting.
Perhaps some items should be excluded from it, or have it ignore very new items.

**Comment by fatyg5** [comment]
It's not stuck in a loop, we have a plugin that, when our server lags too much, runs commands to lessen the lag. If it's lagging a lot, it will continue to try and clear items.
