### ISSUE TITLE
Kyogre tunnel quest

### ISSUE THREAD

**Issue by menno516** [ObliqueNET/Server#458]
in the kyogre quest:

when entering the 3th tunnel the tunnel is half build/half natural with caves in it.
this might be confusing for people who do the quest first time and accidentally
![2020-04-05_01 00 42](https://user-images.githubusercontent.com/63118334/78463135-b8e1ad80-76d9-11ea-8e79-9babb532ccef.png)
 go in it.

**Comment by Vohras2** [comment]
Going to assume this was fixed, since it is several months old.
