### ISSUE TITLE
Quests reseting

### ISSUE THREAD

**Issue by Lieren-HuntGhosts** [ObliqueNET/Server#460]
Seems that Nattryon's quests and Ranger's vanished as the first crashes happened. Don't know how to work with that. Our main proof would be Ranger if both are telling the truth.

**Comment by Soshisen** [comment]
Which quests? When did this happen? I need day/time. Was it the same quest or did they both lose the same quest?

**Comment by Lieren-HuntGhosts** [comment]
Nattryon didn't specified any quest. They just said that during one crash their quests got reseted. Neither I have Ranger's information, he just stated that he lost his quests too when Nattryon said. Nattryon said that was just a little annoyed to having to redo the quests but didn't care so with the poor information I got from him I think that job is done. Ranger could still be asked tho.

**Comment by Vohras2** [comment]
Going to close this since it's almost 3 months old, and I assumed fixed since Ranger is a QD.
