### ISSUE TITLE
Server Ban appeal

### ISSUE THREAD

**Issue by Krothesis** [ObliqueNET/Server#461]
I got banned for the use of an Xray but the closest thing I've got installed is a thing that turns off fog from when I lived in the Ultrazone before the map reset

**Comment by fatyg5** [comment]
I'll give you once chance to admit to having xray installed, because Forge reports every client mod that a player tries to join with, and it so happens that every time you have tried to log into our server it has reported xray 1.4.0.

**Comment by Krothesis** [comment]
Ah, Yeah I it did then and I promise I won't do it again

**Comment by Krothesis** [comment]
Can I keep the no fog thingy though?

**Comment by fatyg5** [comment]
As we can not enforce mods like that, yes you can keep it, but if you connect to our server ever again with an xray or other hack mod we will fully ban you. Enjoy your unban.

**Comment by Krothesis** [comment]
Thank you, I'll double check before installing any other mods in the future
