### ISSUE TITLE
Ban Appeal 

### ISSUE THREAD

**Issue by BootyHadMeLike** [ObliqueNET/Server#462]
Hey, I was banned for hacking with fly hacks. That's my bad. I read the rules and saw xraying and "hacking" to be bannable, but not a fly mod. Typically when I think of the term "hacks", I assume a hacked client. I'm not exactly too experienced with modded minecraft and how they classify this stuff, as I'm more from the PvP scene of Minecraft. I figured since pokemon can already fly and people give out /fly all the time, it wouldn't be too big a deal, but I definitely understand how it'd give me an unfair advantage over other players, and that's the general point of this rule. I have enjoyed this server quite a bit, as I am the leader of a town with a few of my close friends. I apologize for this, and I have deleted the mod completely.
Oh, and my IGN is BootyHadMeLike, just to be sure xd

**Comment by fatyg5** [comment]
Your ban will be moved to a 3 day tempban starting today, but please remember that we do not condone hacks. If you are caught again with any hack mod you will be instantly banned. Thanks!
