### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by HypoNok** [ObliqueNET/Server#463]
Dear admin.

I have been banned for creating an anti afk thing.
i was told to stop with it and builded it again.
i did not used it though
i am sorry and see in that it is a mistake from me.
i wont do it again.
My ing is HypoNok

Greetz HypoNok

**Comment by ElementalMP** [comment]
You were told explicitly not to build one, and knew that we were watching to make sure. Against all odds, you still went ahead and built it. Your ban is only 3 days, and it seems you are only sorry that you got banned because of it. For these reasons, you will wait out the ban.
