### ISSUE TITLE
Quest: "Help at the Pokecenter"not working properly.

### ISSUE THREAD

**Issue by Saltypeper** [ObliqueNET/Server#466]
After i finnished the part for the quest that you needed to go to Agni, i went to the clocktower to battle the NPC. after i battled the NPC i was tped somewhere and got suffocated somewhere (didnt see where) and didnt get the thing that shows that you finnished the quest. the quest isnt under /quests so i think i finnished it

**Comment by BlitzAsogi** [comment]
Teleport has been fixed, as well as an unintended skip of the last stage where you were supposed to talk to percy.
