### ISSUE TITLE
I got banned for typing @everyone

### ISSUE THREAD

**Issue by tim92673** [ObliqueNET/Server#471]
Like seriously? You LITERALLY wrote in a catch for @everyone, and instead of just simply replacing it with "\\@everyone," you instantly ban someone that says it? Excuse me? A server that you would need to be on for at least a couple hours if not a couple days to know it even has a discord server, let alone one that posts every single message in chat into a server, instabans anyone who types @everyone? You couldn't possibly have thought that was a good idea.

**Comment by Hiroku** [comment]
100% of the people that have used it before you (and that is quite a few people) did so to troll by making Mia tag everyone in the discord. Cmon, use your head, how many people use @ everyone in a minecraft chat that they know links to discord and AREN'T trying to tag everyone on the discord

**Comment by tim92673** [comment]
That shouldn't be a problem in the first place. Mia doesn't need nor should have @everyone privileges, and adding an instant ban towards anyone that says it is just crazy. Secondly, not everyone knows that the server has a bot that repeats every single message that is sent in the first place, having this phrase automatically ban someone just seems like a very overzealous booby-trap, and is bound to catch plenty of innocent people when it's only useful as a booby-trap in the first place.

**Comment by Hiroku** [comment]
It's caught zero innocent people prior to you. Also Mia does actually benefit from having that, I've used her for global announcements in other discords for instance. Anyway, the catch doesn't actually ban you, it's the staff that banned you so it should be an appeal to them that you weren't trying to troll rather than an a complaint about the bot

**Comment by Rasgnarok** [comment]
Correct, as I did the ban myself. Let me know when you want to appeal the reasons for you trying to tag 100 or 4000 people.

**Comment by tim92673** [comment]
One line code blocks don't even work with @everyone, so it's a moot point regardless, wtf even is this ban?

**Comment by fatyg5** [comment]
A permanent one! Enjoy :)
