### ISSUE TITLE
Unable to damage mobs in Heill's admin claim

### ISSUE THREAD

**Issue by Vohras2** [ObliqueNET/Server#475]
The Heill admin claim has quite a large number of hostile and peaceful mobs inside it, including spawners placed their for their use. Currently, players are unable to do any damage to said creatures due to the landlord blocking the damage interaction. /IC allows you to bypass and damage them.

**Comment by menno516** [comment]
for now a bypass i found is using a bow and arrow, but yeah. this is kinda annoying

**Comment by Vohras2** [comment]
Closing this since there's a more recent issue likely to get more attention.
