### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by jotha9** [ObliqueNET/Server#478]
IGN: jotha9

So last night me and my friends were joking around in chat and one of my friends joked about me being a convicted r*pist and I decided to play along, and it got out of hand. At the time I didn’t realize how alot of people can actually take offense to that, because when you joke around with friends it’s easy to slip up and go a bit too far. I thought I had stopped after one of the mods told me it was my only warning but I didn’t realize I was still being hurtful. It was 3 am and me and my friends were just being stupid. Of course I don’t take pride in what I did and I do feel sorry for mai and I now know the boundaries of how far you can go. I have played on this server for over a year and have never done something like this before, I love the server and it hurts to just never be able to play again for one slip up and I’m angry at myself. I don’t expect to be unbanned, but nonetheless I’m sorry for what I did and especially sorry to mai.

**Comment by Rasgnarok** [comment]
I will review and discuss with mai, then post my final decision here.

**Comment by Rasgnarok** [comment]
I will lessen your ban to 1d 12h remaining. Be aware that next time this happens, it will be permanent.
