### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by pumori66** [ObliqueNET/Server#480]
Banned for "mass raiding the town Whisperers and refusing to give items back." I never took mass amounts of items, and couldn't have given any that i took back as i used it for my pokemon.

**Comment by Howesey** [comment]
Same thing happened to me recently. Same town, owned by the same moderator that i assume banned you. Clearly for personal gain and not for the benefit of the server.

**Comment by pumori66** [comment]
alright, good to know that its not just me

**Comment by BlitzAsogi** [comment]
> Clearly for personal gain and not for the benefit of the server.
I won't be the one handling your ban, but if you do plan on appealing for your ban to be removed, i believe it would be in your best interests to not badmouth the staff, or assume their intents.

**Comment by Howesey** [comment]
> i believe it would be in your best interests to not badmouth the staff, or assume their intents.

I apologise for the lack of clarity in my reply, however, if you haven't already I would invite you to read the final conclusive paragraph of my ban appeal, posted a few days ago. This shows that I have no intention to "badmouth" or attack anyone in question. Furthermore, I believe it is best to let those who are dealing with the issues deal with proceedings.

If, like stated previously, you would like to view my ban appeal it can be found here:
https://github.com/ObliqueNET/Server/issues/474#issuecomment-611111497

**Comment by pumori66** [comment]
I agree with your whole ban appeal, this is similar to what happened to me, with the same moderator. Anytime that i asked, I was told they were public. The 5 chests in the back were all mine, and I felt fine with anyone taking as much as they needed to help grow the town. And this ban may have been fueled by the fact that I quit the server (for a couple of days, i wasn't sleeping and needed to). and then he messaged me saying, "where did you put all the stuff from the chests?" and I only ever took what I was going to use, and some of the stuff in the chests was mine. So anything i would have had would be either in my chests at the town home or my base, but I never put anything in my base. Another player in my town claimed my plot after i left (again temporarily, no connection to events going on with the town or WickedShadow) and would have had access to all of my chests. I had a few other homes set, but these were just for finding biomes. I never acted in any way against my town or the mods, yet I am banned. The rule "do not steal" would not apply to this, for as far as i knew these chests were public.

**Comment by Howesey** [comment]
Hwsy#5604
Feel free to contact me, happy to help someone with a similar issue to myself

**Comment by Rasgnarok** [comment]
Following a review of the discussions that led to your ban, I've deemed it erroneous, considering you were never questioned, and therefore never allowed to explain your case. You've now been unbanned, and any involvements with this instance cleared.
