### ISSUE TITLE
Avenging Flames Quest 

### ISSUE THREAD

**Issue by Dakarti** [ObliqueNET/Server#482]
so i am currently trying to ha hutn the moltress quest. i did 12 runs in witch 5 of them glitched out. after i defeat the endboss my quest Progress gets reset to 40% as if i failed to capture the moltress. but the Problem is that i dont Even get an Encounter with it. i dont get the message i should get after defeating him. the only Thing i get is the dark blue message that sais you have to start all over again.

i know i can just warp out of the cave and start again but i wanna know if i can avoid the broken runs somehow because  i dont wanna have to do like 50 additional runs to get the 1 in 150 Chance

thanks for helping and sorry for my spelling 

P1TT

**Comment by BlitzAsogi** [comment]
No, you cannot. The way the quest is coded is for each time you fail, to rerun the whole thing.

**Comment by Dakarti** [comment]
idk if you understood but it Auto failed me before or after i defeated the boss. but that doesnt matter now :D
