### ISSUE TITLE
Level Lock Plugin 

### ISSUE THREAD

**Issue by Tac3403** [ObliqueNET/Server#483]
Fix the /levellock command to be able to lock pokemon at the level they are already at, 
such as LVL 75 Alakazam
/ll 1 75
This would be very nice thank you.

**Comment by Vohras2** [comment]
You can already disable leveling in this scenario by clicking the L in the top right corner above the Pokemon's picture on the summary screen.

**Comment by Tac3403** [comment]
> You can already disable leveling in this scenario by clicking the L in the top right corner above the Pokemon's picture on the summary screen.

Ras told me to put it on the tracker to get it changed so you can /ll Pokemon to a level they are at already- so she wouldn't forget to do it lol

**Comment by fatyg5** [comment]
Has been fixed following our next restart, if it's still an issue reopen this topic.
