### ISSUE TITLE
I got banned cause xray, but dont have xray

### ISSUE THREAD

**Issue by Richie1608** [ObliqueNET/Server#486]
Hi, 
I got banned because of the use of xray, while i was flying (fly was activated) through a Savana to find Nidoran's. 
I added the mod JEI to the modpack and did a texturepack to change some textures of the pokemon but I did not used xray.
You can check my inventory and my chests, but there is nothing I could've even xrayed.

My IGN is Richie_Richer
On Discord it's: Richie #8199

**Comment by fatyg5** [comment]
You realize we can see every mod you log into the server with, right? It explicitly states every time you log in that you have "xray 2.0.0".

**Comment by Richie1608** [comment]
Yes I know you can see this, but I didn't use Xray at any point.

**Comment by fatyg5** [comment]
And we can prove that how? You logged onto our server with xray and were banned for it. Whether you used it or not, we don't care.

**Comment by Richie1608** [comment]
Well I understand that. 
And I must admit I had the mod installed, but I didn't know it anymore.
I removed the mod immediately. It was not my plan to xray or cheat on this server.
I'm playing on Terra for one year now with my friends and really don't want to lose it, because there was a mod installed I allready forgot about.

And about the prove, you can certainly not prove if I used it or not, but I can show you all of my items I got, there is nothing from X-Raying. 
And I can repeat my statement, that I did not use the mod at any point on the Server.
