### ISSUE TITLE
Mia Market Unbreedable Message

### ISSUE THREAD

**Issue by fatyg5** [ObliqueNET/Server#489]
When you attempt to buy an unbreedable Pokemon off the market, Mia should DM you something like "This Pokemon is unbreedable, are you sure you want to proceed? If so, retype your marketbuy command with 'confirm' after it" and require you to retype it like **!marketbuy ID confirm**

However, if you add confirm the first time you type it, it should instantly buy.

See WonderTrade for intended behavior

**Comment by Hiroku** [comment]
but it already shows unbreedable pokemon, that's like "hey wait I didn't realize it was bashful natured" when it legit says

**Comment by fatyg5** [comment]
To a new player, showing scissors in the top right corner means nothing and there's absolutely nothing that educates them that this means that. We just assume that they will be told and or ask about it

**Comment by Hiroku** [comment]
This has been resolved, the pokemon is specifically referred to as unbreedable and is coloured red in the new market.
