### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by ooouf** [ObliqueNET/Server#492]
Hi! I am deeply sorry, I used a survival flight to explore faster. I removed the mod and I assume your server recognizes the mods I use so I won't bother try cheating again. Sorry again for breaking the rules.

In game name: ooouf

**Comment by rickjuhh** [comment]
Hi sorry I claimed people's land I won't do it again and I'll never pack stuff without someone else's permission. Sorry for breaking the rules and maybe my english too

**Comment by fatyg5** [comment]
@rickjuhh This isn't the place for your ban appeal go elsewhere.

As for @ooouf you will be unbanned in one day following my message on this appeal, but if you are caught using hacks again you will be banned permanently.
