### ISSUE TITLE
The Monarchs Labyrith

### ISSUE THREAD

**Issue by Svenniegaming** [ObliqueNET/Server#493]
I've been working on The Monarchs Labyrith quest but at this point i can't move on because the right clicking the ice wall won't work. I do have the flame and everything i need.

Please fix this asap.

**Comment by BlitzAsogi** [comment]
Instead of demanding a quest be fixed and that it's broken, perhaps you should add more details about the issue. For example, what stage are you on, and perhaps a screenshot of your questbook. 
I can't help you simply because I don't have enough information to know what your issue is.

**Comment by Vohras2** [comment]
Closing this as it is over 2 months old.
