### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by rickjuhh** [ObliqueNET/Server#496]
Hi. Sorry I took stuff fromunclaimed land. I promise I'll never do that again and I will never break the rules . I wouldn't claim any more ungeclaimed land either. I hope you'll forgive me
Oh yeah, and one more question do I keep my rank?

Ingame name : rickmine2006

**Comment by Rasgnarok** [comment]
Considering you were banned almost 6 months ago, I have decided to unban you. Know that you already had received warnings and had been spoken to about stealing, so if you are caught again, it'll be a permanent ban with no appeal allowed. Your unban is effective immediately.
