### ISSUE TITLE
I had survival flight and deeply regret using it

### ISSUE THREAD

**Issue by verysenset** [ObliqueNET/Server#497]
Hi I was dumb and used a flight mod I want to apologize and hope for a second chance. I promise I will never cheat again, I think your server was very enjoyable.

in game name: Verysenset
Sorry again for breaking the rules

**Comment by fatyg5** [comment]
You will be unbanned one day following me posting a reply to this issue. If you are caught using hacks on our server again you will be permanently banned, we do not tolerate them. I hope that you have learned your lesson and we won't have any more issues!
