### ISSUE TITLE
Ban appeal X-Ray Josbrecht

### ISSUE THREAD

**Issue by Josbrecht** [ObliqueNET/Server#498]
Hey, My name is Jos

I joined the pixelmon server 3 days ago went mining all over the place not in straight lines or something found some coal etc. I just came out of school, So i "was" very hyped to play again and i joined and it straight said "You are banned from this server!" Reason Xray. but i am playing with the Technic launcher and there's no x ray installed.

So i would like to ask to be unbanned.

Greetings, Jos 

Discord : Heino033

![Knipsel](https://user-images.githubusercontent.com/63848848/79557995-ce74b100-80a3-11ea-8b0f-72b42e0ded65.PNG)

**Comment by fatyg5** [comment]
You realize we are able to see every mod that a client logs in with, right? At first during the day you were banned, you had no Xray installed. Then the next few times you logged into our server, it reported you having "xray@1.4.0". Now, I've been running servers for 3 years now and this has never been wrong and I can ensure you that no one was attempting to log in at the same time as you. Are you still going to play dumb and say you didn't have Xray installed?

Also, showing me a picture of what modpack you use means nothing. You can add or remove mods from Technic modpacks.

**Comment by Rasgnarok** [comment]
Closing this ban appeal as there has been no response in the last week. Please reply here if you wish to answer the latest reply.
