### ISSUE TITLE
Banned for swearing in teamchat?

### ISSUE THREAD

**Issue by Smeuner** [ObliqueNET/Server#499]
Hello, I got banned just now after typing a swearword in teamchat? My friend and I do this all the time and never did any of us get banned in doing so. however, I get on and type the *exact* same word my townmember used just seconds before. And I get insta banned while he gets to play on the server? So I went ahead and asked a mod about this and I was told that I am in fact allowed to swear in our teamchat. That brings me to why I'm writing this appeal. I shouldn't be banned for typing a swear word in team chat. I'm sure it's just a mistake with the auto ban system or whatever but I would like to be unbanned, and adding to the fact that I can now no longer play until I get unbanned I also have a couple items including a legendary pokemon that is not mine, but instead one of my friends'.

I hope this issue can be resolved quickly and I'll add some proof that I did actually send the message in teamchat and not in the global chat. Thank you for your time.

proof: (WARNING: explicit language) https://prnt.sc/s1fyq0

**Comment by Smeuner** [comment]
IGN is smeuner (forgot to add)

**Comment by Rasgnarok** [comment]
Unbanned. For next time, remember that slurs in moderation does not include homophobic slurs.
