### ISSUE TITLE
Quest Typo - Fallen But Not Forgotten

### ISSUE THREAD

**Issue by CenizaRey** [ObliqueNET/Server#500]
<img width="579" alt="Screenshot 2020-04-19 at 16 28 03" src="https://user-images.githubusercontent.com/42212238/79692060-e5113880-825a-11ea-96fc-34452f67a2bc.png">

Should be "A newly opened crypt stands open before you, do you (dare?) enter?"

**Comment by Soshisen** [comment]
Dare is not needed, Only thing I would, and will, change is the second open.
