### ISSUE TITLE
Debug - Breath of a Dragon

### ISSUE THREAD

**Issue by CenizaRey** [ObliqueNET/Server#501]
<img width="960" alt="Screenshot 2020-04-19 at 16 55 28" src="https://user-images.githubusercontent.com/42212238/79692770-d6c51b80-825e-11ea-9379-ada0e6f3ae55.png">

"Cerberus" is spelled incorrectly.

<img width="957" alt="Screenshot 2020-04-19 at 16 55 37" src="https://user-images.githubusercontent.com/42212238/79692777-e6446480-825e-11ea-8fc2-1d5ba52f157d.png">

"Standoffish" is spelled incorrectly and doesn't need a hyphen.

**Comment by BlitzAsogi** [comment]
Names arent part of the grammar we check or care about, and the dialogue box also does not originate from this quest.
