### ISSUE TITLE
Debug - Trainer's Way of Life

### ISSUE THREAD

**Issue by CenizaRey** [ObliqueNET/Server#502]
<img width="849" alt="Screenshot 2020-04-19 at 16 55 52" src="https://user-images.githubusercontent.com/42212238/79692813-1a1f8a00-825f-11ea-91b1-9a9c438ace9b.png">

The dialogue says Professor Ras hands you 10 pokeballs, but the player receives 32.

**Comment by BlitzAsogi** [comment]
fixed
