### ISSUE TITLE
Debug - The Electric Demon

### ISSUE THREAD

**Issue by CenizaRey** [ObliqueNET/Server#504]
<img width="680" alt="Screenshot 2020-04-19 at 16 56 05" src="https://user-images.githubusercontent.com/42212238/79692832-3c190c80-825f-11ea-9a1d-29dd664376a7.png">

Bill's dialogue box comes up too quickly after you defeat him in battle, causing the F5 glitch.

<img width="920" alt="Screenshot 2020-04-19 at 16 56 14" src="https://user-images.githubusercontent.com/42212238/79692840-4a672880-825f-11ea-9550-94ccc749368b.png">

Simon, despite being a questgiver, lacks the label

**Comment by BlitzAsogi** [comment]
Delay has been added, person who does the tags has been notified
