### ISSUE TITLE
Debug - The Forgotten Witch

### ISSUE THREAD

**Issue by CenizaRey** [ObliqueNET/Server#505]
<img width="957" alt="Screenshot 2020-04-19 at 16 56 23" src="https://user-images.githubusercontent.com/42212238/79692860-67036080-825f-11ea-8ecc-0fc850207fd9.png">

"Thats" needs an apostrophe.

<img width="963" alt="Screenshot 2020-04-19 at 16 56 30" src="https://user-images.githubusercontent.com/42212238/79692865-6f5b9b80-825f-11ea-9ef3-b342683e0947.png">

"hand" should be "hands".

**Comment by BlitzAsogi** [comment]
Fixed
