### ISSUE TITLE
Debug - Remember to Exorcise

### ISSUE THREAD

**Issue by CenizaRey** [ObliqueNET/Server#506]
<img width="1279" alt="Screenshot 2020-04-19 at 17 04 46" src="https://user-images.githubusercontent.com/42212238/79692948-f1e45b00-825f-11ea-89ab-11b9ac45540d.png">

Losing to Merrin in the cave causes his dialogue box to come up too quickly, causing the F5 glitch.

**Comment by BlitzAsogi** [comment]
Added a 4 second delay after losing before the dialogue pops up
