### ISSUE TITLE
Wiki Debug - Trimming the fat

### ISSUE THREAD

**Issue by CenizaRey** [ObliqueNET/Server#507]
<img width="208" alt="Screenshot 2020-04-19 at 17 19 33" src="https://user-images.githubusercontent.com/42212238/79693360-045f9400-8262-11ea-8d49-a28ff2f2bff1.png">

As the Dynamap is now functionally not in use, perhaps it should be removed from the sidebar to clear the space of the existing 404 link.

**Comment by fatyg5** [comment]
Dynmap will be readded at a later time.
