### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by Crotaz** [ObliqueNET/Server#508]
Greetings, 
I used a client for a while today (ign crotaz), and I would like to apologize for it. I used forge-wurst in order to find some fossils and a few diamonds. I love the server and I hate myself for jeopardizing my ability to enjoy it. Obviously it is very easy for you to detect cheats and so if I am unbanned I won't resort to using them again.
EDIT: I decided it'd be best to come clean for also stealing a few items from an unclaimed underground base since I feel bad for doing it. (This is not something I have been convicted of)
I apologize for all the malicious activities I conducted and despite them I hope you find it in you to give me a second chance. I won't do it again

**Comment by Crotaz** [comment]
My discord is Kela#7285 if you wish to discuss there

**Comment by Rasgnarok** [comment]
Considering your honesty, and the fact you have never been caught for any other rules, I have decided to unban you, effective immediately. Please remember that we can check for cheats whenever we feel like it, and that next offence will mean a permanent ban.
