### ISSUE TITLE
In-Battle Glitch

### ISSUE THREAD

**Issue by matiera** [ObliqueNET/Server#509]
Hello, I have been having a recurring issue when I am in battles. It occurs every 10-15 battles where I will enter a battle and it will glitch. It will move my mouse and will not allow me to chat or select any battle options. Sometimes this will happen mid battle, but most often it will occur at the beginning of the battle. Today this has happened atleast 3-4 times so far. The only way to exit the glitched battle is to have a staff member/endbattle, or to close out of the game.

**Comment by duckmangamer124** [comment]
There is a command called /endbattle and it'll end the battle with your pokemon being injured and not getting any sort of reward given by that you never beat the pokemon

**Comment by matiera** [comment]
It will not allow me to end battle for myself when this glitch is happening.

**Comment by Soshisen** [comment]
This is a Pixelmon bug, you need to report it them them, not the server
