### ISSUE TITLE
Blast from the Past

### ISSUE THREAD

**Issue by Blitzmentalist** [ObliqueNET/Server#510]
The initial text prompt for the quest repeats the prior two text boxes condensed into a single quote at the end. It should just be removed to fix it.

**Comment by Blitzmentalist** [comment]
Upon talking to Cornelius Polluting, the player doesn't actually receive a physical journal. I had the command to fire for the journal in the original document, so we should be able to fix that.

Also, at Step 7, the hint gives the coordinates of the First Subject, not the second.

**Comment by Blitzmentalist** [comment]
At Stage 9, the quest still refers to Cornelius Polluting as "Dr. Crichton." This is left over from earlier draft and was probably copied when the quest was coded.

**Comment by Blitzmentalist** [comment]
small grammar area in Stage 13 where two words should have a space in between them.

**Comment by BlitzAsogi** [comment]
All issues should be fixed
