### ISSUE TITLE
Debug - The Electric Demon [#2] [On behalf of Tinemither]

### ISSUE THREAD

**Issue by CenizaRey** [ObliqueNET/Server#513]
<img width="583" alt="Screenshot 2020-04-21 at 21 09 05" src="https://user-images.githubusercontent.com/42212238/79909185-71b32680-8414-11ea-9075-651adf7b17dc.png">

**Comment by BlitzAsogi** [comment]
I'm not exactly sure why you're experiencing this issue, but any QD should be able to set your progress back to the right stage.
