### ISSUE TITLE
As the Ground Quakes and Enter Zones

### ISSUE THREAD

**Issue by Blitzmentalist** [ObliqueNET/Server#514]
Cen___ had repeated issues with all enter zones in the latter part of As the Ground Quakes, and a section of the final cave at the end was outside of its territory, causing his progress to be reset. This leads me to believe that the enter zones associated with the area under Agni have been altered in some way, preventing it from working.

**Comment by BlitzAsogi** [comment]
Turns out when the server first started up, some of the gamerules werent set in place, such as doFireTick.
Combine that with the place being made of coal block alongside lava, you can make a guess what happened.
