### ISSUE TITLE
The Arbiter's Downfall Zapdos Loop Issues

### ISSUE THREAD

**Issue by Blitzmentalist** [ObliqueNET/Server#515]
And now I encounter an issue of my own.

If you accidentally defeat Zapdos at the statue when you're meant to catch it, you get reset to room with Menma below the power plant where he reveals that he has recaptured Zapdos and you'll need to fight him again to free it. 

This already feels odd from a lore perspective considering he somewhat repented for his actions during his initial defeat, but it doesn't even work mechanically as the player cannot fight Menma again and is instead told to leave via warp pads. These warp pads are no longer there, and leaving the chamber in any other way causes the player to reset to the beginning of the maze sequence.

I recommend removing this loop entirely and simply allowing the player to attempt to catch Zapdos again.

**Comment by CenizaRey** [comment]
Arbiter's Downfall was originally written by Matt, who was told that the loop was weird and unnatural from the get-go, I guess he just never listened. /shrug

**Comment by BlitzAsogi** [comment]
I'm surprised this wasn't complained about earlier.

I've removed stage 17 for the re-fighting of Menma altogether, the capture Zapdos part is now its own loop.
