### ISSUE TITLE
Silk Touch prevents gaining rpg exp with the Woodcutting skill

### ISSUE THREAD

**Issue by Somerandomguy910** [ObliqueNET/Server#516]
Chopping Trees with a Silk Touch Axe prevents you from gaining exp for the Woodcutting skill

**Comment by Vohras2** [comment]
This is intentional. All silk touch tools do not give RPG bonuses due to being able to place/farm ores and wood.

**Comment by CenizaRey** [comment]
Can we not go back to when placing ores was blocked?

**Comment by Somerandomguy910** [comment]
Can't currently place ores right now
