### ISSUE TITLE
Ban Appeal 

### ISSUE THREAD

**Issue by NukingLizards** [ObliqueNET/Server#517]
I was Banned on 27/04/2020 For attempting to sell Shop Vouchers which i didn't know was not allowed. I never Received a warning from a staff member (that is known my game has been bugging out and some chat wont show) If I knew selling Shop Vouchers is a bannable offense i wouldn't of offered to do so. I'm hoping to receive a pardon for my mistake on the trust that it will not happen again! I love the Server Hence the reason of donation its to show my gratitude to the server and the staff. I hope you'll take my Ban Appeal into Consideration. Any further questions or inquires please reach me on discord Nuking_Lizards#4702  

IGN: NUKING_Lizards 

Attached: Ban Notice and proof that my text doesn't show properly 

*Note i am using a texture pack however in default texture i have the same chat error* 

![2020-04-27_15 29 04](https://user-images.githubusercontent.com/64395766/80337070-48731a00-889c-11ea-87c7-70f9516a58c7.png)
![image](https://user-images.githubusercontent.com/64395766/80337211-adc70b00-889c-11ea-86df-064f034a1a20.png)

**Comment by NukingLizards** [comment]
*Please note i made a mistake of asking staff to have a look at my appeal so you may want to take this into consideration as well.*

Attached is the chat logs between me and Blitz:

![image](https://user-images.githubusercontent.com/64395766/80374415-f9e47080-88d9-11ea-9b72-cb79ff7648fb.png)
![image](https://user-images.githubusercontent.com/64395766/80374540-25fff180-88da-11ea-989f-90e4134782ea.png)

**Comment by Rasgnarok** [comment]
This will be reviewed and the ban appeal updated. We are on it.

**Comment by Rasgnarok** [comment]
Ban has been revoked. While not against the rules, we would prefer not to advertise the trading or selling of Store vouchers. Unban has now been applied.
