### ISSUE TITLE
Evo stone canceling

### ISSUE THREAD

**Issue by Crofto** [ObliqueNET/Server#518]
Hi,

I was doing the quest "a pure heart", I thought I should evolve my mons (through an evo stone) but I was taken by doubt while I was evolving it, so I cancelled the evolution but didn't get the evo stone back. 
I'm not sure this is supposed to work this way so i post this...

-Crofto

**Comment by BlitzAsogi** [comment]
Just tested this in singleplayer and it seems to be the case.
When you right click the pokemon with the stone, it consumes the stone and triggers the evolution. Even if you cancel the evolution, the stone was already consumed to start the evolution.
