### ISSUE TITLE
An Unexpected Delivery, Issues Starting

### ISSUE THREAD

**Issue by Blitzmentalist** [ObliqueNET/Server#519]
Both Quadehar97 and myself have had issues starting the Guild Quest "An Unexpected Delivery." We are speaking with the correct person, are in the Vulpe guild, and have empty space in the quest book to take on another quest.

I'd like to request a QD with coding ability examine the quest file and see if there is a reason it isn't activating at the beginning. Putting this issue here so it isn't lost in QD Chat.

**Comment by PrimalCyndaquil** [comment]
Guild required is apparently Oxus, so may be a wiki issue.

**Comment by PrimalCyndaquil** [comment]
Woops! as it turns out this was a previous QD issue. Meant to be Vulpe, you were correct and the quest was broken to say Oxus. Has now been fixed.
