### ISSUE TITLE
Debug - An Ideal World

### ISSUE THREAD

**Issue by CenizaRey** [ObliqueNET/Server#520]
<img width="584" alt="Screenshot 2020-04-30 at 16 10 43" src="https://user-images.githubusercontent.com/42212238/80752392-51295180-8b23-11ea-98a3-553f156eb6c3.png">

Justine* is missing its J

<img width="508" alt="Screenshot 2020-04-30 at 16 11 02" src="https://user-images.githubusercontent.com/42212238/80752428-60100400-8b23-11ea-8095-37c513a07795.png">

"Answers" doesn't need an apostrophe.

<img width="558" alt="Screenshot 2020-04-30 at 16 31 20" src="https://user-images.githubusercontent.com/42212238/80752476-75852e00-8b23-11ea-8e91-ce30a1ef9ed9.png">

Is it intended to be corruptor or computer?

**Comment by Soshisen** [comment]
This is not a bug, it is a grammatical error. Please label your input as such

**Comment by CenizaRey** [comment]
With respect, the semantics of the label don't matter as long as the issue is conveyed.

**Comment by Vohras2** [comment]
Closed, since fixed.
