### ISSUE TITLE
Discord Appeal

### ISSUE THREAD

**Issue by Stega01** [ObliqueNET/Server#523]
I was just notified I was removed from the discord because "You are being removed from the Oblique Discord because I'm pretty sure you're one of the raid bots. If this is in error, say so" Im not one of these "raid bots" idk what they even are ive just been playing focusing on legendary quests the past few days currently working on the articuno quest

**Comment by AdmiralCrunch56** [comment]
Apologies for the late reply, I've unbanned you. Here's a discord link: https://discord.gg/B3XcYcR
Thanks for letting us know.
