### ISSUE TITLE
Music Under The Mountain

### ISSUE THREAD

**Issue by ZackieKun** [ObliqueNET/Server#524]
So I was doing the quest, got close to the end and received the text attached below. Went to Cyril and nothing happened. Apparently the quest is marked as complete according to BlitzMentalist. Problem is, I got no rewards, not even a questpoint. I was 91qp before and after this quest.
![Music Under The Mountain](https://user-images.githubusercontent.com/56382047/81489832-1a002200-9240-11ea-99fd-c2b64f333e39.png)

**Comment by PrimalCyndaquil** [comment]
This has since been fixed and should now work. If you are still concerned about this ask in #support for a refund of 1 QP and 5000$.

**Comment by Vohras2** [comment]
Closing since fixed.
