### ISSUE TITLE
[Sponge] Master ticket on mobs and Heill

### ISSUE THREAD

**Issue by Christodynamics** [ObliqueNET/Server#526]
Around Heill, you cant attack mobs... that works for passive mobs like cows, but you cant attack some hostile mobs as well. Some notable mentions are Shulkers and Zombie Villagers. While regular old Bow equipped skeleton and zombie can be attacked, these mobs although hostile, cannot be damaged. (Instead they vanish but still hit you).

**Comment by Rasgnarok** [comment]
Should be fixed for next restart, we are adding interacts to the mobs. Ideally, they should not be spawning at all in the Heill admin claim, @Hiroku .

**Comment by Rasgnarok** [comment]
Couple of issues with mobs in Heill:
- Interact for damage not applying properly to hostile mobs within landlord admin claim (https://github.com/ObliqueNET/Server/issues/828 and this)
- Mob spawning in Heill continues to be patchy (EndSpawning plugin), likely related to Sponge/ObliqueCore overrides on the world (https://github.com/ObliqueNET/Server/issues/852).

**Comment by Vohras2** [comment]
Closing as this will be addressed by future updates.
