### ISSUE TITLE
Lost Market Money

### ISSUE THREAD

**Issue by fatyg5** [ObliqueNET/Server#528]

**Comment by WickedShadow498** [comment]
Lost 30k to selling a Ditto on the market

**Comment by Krothesis** [comment]
Krothesis -Solosis 10000,  Ferroseed 8500, Riolu 13000

**Comment by TheTunzo** [comment]
Lost Buneary, worth 7500, IGN: TheTunzo

**Comment by MoloCreator** [comment]
IGN: MoloCreator - UnBreed 5x31 Timid Rotom, worth 34 000

**Comment by ZackieKun** [comment]
IGN - ZackieKun Lost two mon.  Textured Mew priced at 45k. Textured Groudon priced at 50k. Both were quest mon I was selling. Had pretty good ivs too.

**Comment by atnaom** [comment]
IGN - Aliskiren Lost unbreed ferroseed worth 10k

**Comment by Kary334** [comment]
I lost breedable Mimikyu for 25k and breedable Raltz for 10k IGN: kary33

**Comment by Kirikoz** [comment]
IGN - Kirikoz Lost unbreed chansey worth 10k

**Comment by AriannaShirogane** [comment]
my friend TheBestGirl_WGF lost her quilava that yesterday she put in the market for 8.000

**Comment by dsdsdsdsdsdsdsdsds** [comment]
IGN - dsdsdsdsds Wailmer put on market for 9.5k disappered while I was not logged in, no usual message on Discord noting sale, unsure if I got the money or not.

**Comment by PrimalCyndaquil** [comment]
IGN- PrimalCyndaquil. Was an eevee for roughly 10k, not sure exactly.

**Comment by Draisaitl** [comment]
IGN- Draisaitl_

HA timid eevee 5.5k unbreedable
HA calm eevee 5.5k unbreedable
bold HA HP-fire eevee 12.5k unbreedable

recieved no funds for any of these and none are on the market anymore.

**Comment by Hikaritokage** [comment]
IGN- Hikaritokage
It looks like I lost my ferroseed, mareanie, and chansey I put on the market yesterday. I have not gotten any messages about them being sold, but it looks like 1 of them was sold cause my money went up. They were all 3 around 13,000.
