### ISSUE TITLE
Paul is dead and broken

### ISSUE THREAD

**Issue by freddypwner** [ObliqueNET/Server#530]
In the Ice Cream quest in Agni, Paul the Ice Cream man wouldn't accept the ice cream shipment. Also he was literally dead for a little bit but he's undead now.
![image](https://user-images.githubusercontent.com/65520757/82169101-6544b100-988e-11ea-9b81-2fd25f9a7fe1.png)
![image](https://user-images.githubusercontent.com/65520757/82169115-6f66af80-988e-11ea-9e78-8bdc1e145790.png)

**Comment by starwarschamp4** [comment]
They completed the quest, so no issue?
