### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by BloodR3dReap3r** [ObliqueNET/Server#533]
I was believe I was wrongly banned as I had only gotten on for about 5 minutes some day after the reset and I had never gone out of spawn yet it says I was banned for use of X-ray. My IGN is BloodR3dReap3r.

**Comment by ElementalMP** [comment]
Were you previously banned for xray on any of our servers previously for the same reason? When we first went live, the old banlist was not being enforced, and had to be added back in manually.

**Comment by BloodR3dReap3r** [comment]
I wasn't banned previously, I was able to play the day/days before the reset and after

**Comment by ElementalMP** [comment]
Hmm, okay. Looks like you were banned for having xray installed to your client. Xray isn't allowed on our servers, which is why you were banned.

**Comment by ElementalMP** [comment]
Since I have not received an answer here (and since you mouthed off about it on discord), I will assume this to be resolved. If this is not the case, please make another ticket.
