### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by freddypwner** [ObliqueNET/Server#534]
I  made an AFK fish farmer, not to use AFK, but because I'm really REALLY bad at fishing, and someone said I couldn't use it for that either, so I disabled it and asked if that was ok. They said the framework was bad so I then just made it hoppers and a chest, with zero aspects of an automatic one. I literally asked in chat if it was ok what I was doing because I didn't want to break the rules. I got banned after the machine was dismantled to just hoppers.
![image](https://user-images.githubusercontent.com/65520757/82967123-2f907e00-9f9a-11ea-9e74-f7fca8e6bb6c.png)
https://media.discordapp.net/attachments/416760296053538840/715016007022018610/unknown.png?width=1204&height=677
Also the ban message is ambiguous?

**Comment by ElementalMP** [comment]
Unfortunately, fishing machines are banned on this server. Whether you claim to use it while AFK or not doesn't matter, as we used to allow the use as long as the player was not AFK, and that privilege was abused. As such, they are banned entirely. It would seem clear to me that you already knew this; why else would you put a sign on it saying that it's decorative if you planned to use it? 
The penalty for using an AFK fishing machine is usually permanent, however in your case, you have been given benefit of the doubt and are only banned for 3 days, which is almost over. I think it would be best for you to just wait out the remaining 24 hours.
