### ISSUE TITLE
Pokeload not working

### ISSUE THREAD

**Issue by BlakeSol** [ObliqueNET/Server#535]
Hello I saved a nidoking called Blue Bully before the reset and it seems the loadpoke command says i didnt save one or a error occurred. Ive asked in discord support if the command still works just in case, since it has been a good time ive been on last. Only got a it should when i asked. I have screenshots of the info tabs for the mon. Took them after i saved it. Thought id try the github as a last possible way. If its not possible to get him back itll suck but oh well. Thank you for your time.

**Comment by BlitzAsogi** [comment]
Did you see the confirmation for the save pop up? We had a thing where if the pokemon was already saved by someone else, the command to save the pokemon would fail and tell you to try another.

**Comment by BlakeSol** [comment]
Yes the confirmation did pop up. Since its been some time dont remember the wording of it but i typed in the pokesave command with which slot to save. Then it asked to confirm the selection. I placed all mons in the pc except for Blue Bully which was in my first slot before doing the pokesave command.

**Comment by Hiroku** [comment]
I've fixed this, use the command again and you'll get your Pokémon back

**Comment by BlakeSol** [comment]
Thank you very much

**Comment by Hiroku** [comment]
You're welcome; I'm sorry for the bug.
