### ISSUE TITLE
Fossil machine interactable in claims

### ISSUE THREAD

**Issue by Christodynamics** [ObliqueNET/Server#537]
Fossil machines with Pokemon already in them and the pokeball already on are interactable even in claimed areas (by players who are not the owners of the Pokemon or the claim)

**Comment by Soshisen** [comment]
Was the player trusted to your claim? Or apart of your town?

**Comment by Christodynamics** [comment]
It was the other way around. I was not trusted in their claim but was able to get the lileep out of the fossil machine. Had to get Kara's help to get the name of the player whose Pokemon it was.

**Comment by Hiroku** [comment]
Please retest to confirm my fix is working in town claims

**Comment by Rasgnarok** [comment]
Closing the ticket as it seems to be fixed, but please re-open if it's not the case.
