### ISSUE TITLE
I somehow took Kiris shroomish off the market, and now my magnemites gone

### ISSUE THREAD

**Issue by OrangeSodaPop** [ObliqueNET/Server#538]
![image](https://user-images.githubusercontent.com/57567713/83929053-fb6a4980-a75f-11ea-8ad0-61bafcd281ad.png)
so basically I somehow took kiris shroomish off the market, we both got the same error (in kiris pov)
![image](https://user-images.githubusercontent.com/57567713/83929158-6ae03900-a760-11ea-9b4e-881c0e87f264.png)
the shroomish was returned to kiri, exept the magnemite disappeared, I cant remove my other pokemon from the market (first image error). the magnemite was 31/30/31/30/7/30, with magnetpull ability.

**Comment by ElementalMP** [comment]
Has this been dealt with
