### ISSUE TITLE
Read me.

### ISSUE THREAD

**Issue by Ras-is-a-Slut** [ObliqueNET/Server#539]
Rasgnarok is a slut.
MeghanClover is a lonely baby who can't get any friends and kills her cats. CALL 911
That is all.
FUCK OBLIQUE

**Comment by Ras-is-a-Slut** [comment]
Btw my name is ElementalMP

**Comment by Hiroku** [comment]
Awh did Ras turn you down for a date? Keep trying man, there's a woman out there for you provided depending on what you can pay per hour

**Comment by Ras-is-a-Slut** [comment]
no I just really hate Ras and Meghan

**Comment by Hiroku** [comment]
Yeah 10 year olds usually say nasty things about the girls they like, it's cute but you just need to say how you really feel man

**Comment by Ras-is-a-Slut** [comment]
Meghan can go suck two dicks

**Comment by Hiroku** [comment]
She could but we know it won't include yours

**Comment by Ras-is-a-Slut** [comment]
Who would touch a herpe mouth like hers XD

**Comment by Ras-is-a-Slut** [comment]
oh yea btw Meghan legit steals from people. She sucked dick on a daily in class

**Comment by Hiroku** [comment]
Seems like you gave it a try, but I don't blame you. Lifetime of virginity can be tough, just keep at it, I believe in you
