### ISSUE TITLE
Suggestion:Scoreboard Timers and Inventory Shulker Boxes

### ISSUE THREAD

**Issue by benb25504** [ObliqueNET/Server#540]
![262907BD-CCB3-42A1-9FC6-D2C8506ED406](https://user-images.githubusercontent.com/66764835/84344619-44176d80-ab79-11ea-924f-8811b53e02a2.png)

**Comment by Rasgnarok** [comment]
Alright, breaking this down:
- Scoreboard events: Scoreboard is too light in server-side to allow for the display of commands (unless using universal, client-required mods). However, can be implemented in an inventory gui 'server menu' (https://github.com/ObliqueNET/Server/issues/950)
- Wondertrade client utilities: https://www.pixelmonmod.com/tracker.php?p=8&t=15452
- Shulker box open inventory: Likely not possible with current Sponge implementation of inventory. Unsafe until we move to Spigot.
