### ISSUE TITLE
Moonlit Memories Starting Location

### ISSUE THREAD

**Issue by ProfAwesome100** [ObliqueNET/Server#542]
On wiki, Moonlit Memories NPC is said to start at "393 69 -1288" when documentation says "-393 69 -1288". Pic below is of current location listed.
![2020-06-13_18 11 32](https://user-images.githubusercontent.com/60492306/84580265-5248d200-ada3-11ea-98f4-cf218c03bbae.png)

**Comment by Vohras2** [comment]
Updated wiki.
