### ISSUE TITLE
Gen 8 pokemon don't have drops

### ISSUE THREAD

**Issue by plasmarob** [ObliqueNET/Server#544]
no drops when you defeat them

**Comment by starwarschamp4** [comment]
Yes they do? I spawned several mons and they drops things for me. Can you list the ones that don't?

**Comment by Hiroku** [comment]
I think he's correct that all the generation 8 Pokemon won't drop anything. The drop configuration is a single file listing all Pokemon, and we use a custom one. Vohras or whoever will need to add balanced drops for the new Pokemon.

**Comment by starwarschamp4** [comment]
Oh, gotcha

**Comment by Vohras2** [comment]
Fixed.
