### ISSUE TITLE
throwing a Primal Groudon in a park ball crashes your connection

### ISSUE THREAD

**Issue by plasmarob** [ObliqueNET/Server#545]
I have a groudon with the red orb.
I can use it in combat, but if i throw the park ball at a wild pokemon, i get crashed/kicked :

"A fatal error has occurred, this connection is terminated"

this is throwing it at any pokemon, boss or not.
any other pokemon seems to work so far, and it works if it's switched in just fine.

it will also crash if in first slot and you are attacked by a rustle, etc.
you can't start a battle with groudon with red orb.

update:
i assume it's a red orb bug.
no error happens without a red orb on

**Comment by ElementalMP** [comment]
This is a pixelmon bug, and needs to be added to their tracker https://pixelmonmod.com/tracker.php
