### ISSUE TITLE
Doubles Battle Weirdness

### ISSUE THREAD

**Issue by Soshisen** [ObliqueNET/Server#546]
After finding a rustling block I entered a doubles battle. I defeated one of the pokes and was trying to catch the second when I got the waiting bug. So I used endbattle. That’s when it got weird. The second poke as well as both of my battling pokes were still out. I was able to start the battle again and catch the second pokemon.

**Comment by Rasgnarok** [comment]
This should be reported directly to the PixelmonMod, https://pixelmonmod.com/tracker.php?p=2.
