### ISSUE TITLE
I was wrongly banned

### ISSUE THREAD

**Issue by Hadoouuken** [ObliqueNET/Server#547]
about 2-3 weeks ago I advertised about Oblique on other servers. I admit I was wrong, but I didn't know that at the time. a few days after I did it, a server admin PM'd me telling me what I did was bannable but since it was a FIRST offence, he would let me go. I didn't do anything wrong afterwards and kind of stopped playing for a bit for work reasons. however, when I come back to play it says I'm banned for advertising on a different server. This is unfair as i literally didnt do anything wrong after i was warned. My IGN : Hadoouuken
i hope this gets resolved

**Comment by ElementalMP** [comment]
I will need to look into this, because the report that was made to me came very recently, the day before your ban in fact. I will need to cross check with other server owners, to ensure everything fits this timeline, and get back to you.

**Comment by Hadoouuken** [comment]
Are there any updates about the situation


________________________________

**Comment by ElementalMP** [comment]
I have unbanned your account, however please be careful in future.
