### ISSUE TITLE
Galarian Yamask Evolution

### ISSUE THREAD

**Issue by matts421** [ObliqueNET/Server#550]
After troubleshooting with several staff/knowledgeable members of the community, I have been asked to come here to document this problem I'm having. Galarian Yamask does not evolve under both the /wiki evolution conditions and the pixelmon wiki evolution conditions. As for the /wiki conditions, it says level up Galarian Yamask in one of the desert biomes. This, of course, did not work.

The evolution conditions that are posted on the pixelmon wiki (level up in a desert temple when 49 hp of damage has been taken, but yamask has not fainted) were then tried as well. This was tested with both exactly 49hp damage taken, and _over_ 49 hp damage taken. Again, to no avail.

I'm not sure if this is a server problem with the custom world gen not recognizing the desert temples as "authentic"  minecraft temples, or if there is a problem with the pixelmon mod in general (like how scorbunny would not evolve into raboot until level 35).

**Comment by Vohras2** [comment]
I -think- this was fixed with the backend refresh of the stats. Let us know if this is still an issue.
