### ISSUE TITLE
Forage is removed

### ISSUE THREAD

**Issue by plasmarob** [ObliqueNET/Server#551]
Forage is no longer possible.
I hear it may be a server side config option that needs to be updated.

**Comment by Christodynamics** [comment]
Works in singleplayer. Tried on multiple pokemon caught before and after 8.0.2. last tested to **not** be working in Oblique on 8.0.2. cannot confirm if it was working in 8.0.1 or 8.0.0.

**Comment by Vohras2** [comment]
This was done after the update as a quick fix to remove mints. I'll ask Ras to re-enable it when she is available.
