### ISSUE TITLE
Plot Command Issues

### ISSUE THREAD

**Issue by xHellohumans** [ObliqueNET/Server#554]
The plots commands are having issues, when I create a plot and try to do the trusting or claiming commands it tells me that I’m not standing on a plot and a open plot that is supposedly able to allow people outside my town doesn’t work either because when someone tried to claim the open plot I set it says that they can’t claim it because they are not a part of my town

**Comment by Vohras2** [comment]
Are you still having these issues, or did you get it sorted out?

**Comment by Hiroku** [comment]
I think the open plot claiming was a mistake and they meant to use /buyplot

**Comment by Hiroku** [comment]
I'm also thinking you might have created shallow plots and weren't standing within the y boundaries, I need someone to test this some more
