### ISSUE TITLE
[Ban Appeal] Twinblader

### ISSUE THREAD

**Issue by Nurob** [ObliqueNET/Server#556]
hey,
I just got banned for using the schematica mod... it is a mod which allows you to see some schematics in order to rebuild them.
Its no hackclient or anything else. Please see for yourself.

If this mod is forbidden, I am sorry, I will deinstall it.

Kinds regards

Twinblader

**Comment by fatyg5** [comment]
We can clearly see all of your mods when you join our server. The hack client "Forgewurst" is clearly listed when you join.

**Comment by fatyg5** [comment]
Closing due to over a week with no reply.
