### ISSUE TITLE
Quest "Static" Softlock

### ISSUE THREAD

**Issue by lolsikinz** [ObliqueNET/Server#558]
Found an issue with the quest "Static"
If you lose to the Eelektross you get the "do you wanna start this quest now?" prompt and if you hit start quest later you get locked to stage 3 and cannot start it/complete without qd help

**Comment by PrimalCyndaquil** [comment]
Fixed by sending the player to stage 2 instead of stage 1. Should now work correctly.

**Comment by Vohras2** [comment]
Closing, since new file has fix.
