### ISSUE TITLE
Breeding bug 

### ISSUE THREAD

**Issue by Saltypeper** [ObliqueNET/Server#559]
So if you breed Flapple you get a Flapple instead of an Applin, I also tested this in a singleplayer and the results are the same.

**Comment by Blokus12** [comment]
This is something that needs to be reported to pixelmon.

**Comment by Rasgnarok** [comment]
Please report to the Reforged bug tracker as it's not something the server can fix, https://www.pixelmonmod.com/tracker.php?p=2

**Comment by Vohras2** [comment]
Fixed for next update in Pixelmon.
