### ISSUE TITLE
Close this

### ISSUE THREAD

**Issue by BootyHadMeLike** [ObliqueNET/Server#560]
Feel free to close this. I no longer have an interest in getting back on the server after the events of the last week. Closing this appeal would give me no more reason to think about it.

If you'd care for some constructive feedback that I have, feel free to hmu on Discord, Julian#6969 
Otherwise, cy@

**Comment by BootyHadMeLike** [comment]
^

**Comment by Rasgnarok** [comment]
We were actually going to discuss this, Ele and I. I'll contact you directly since I am always willing to face feedback.

**Comment by Rasgnarok** [comment]
Ban appeal sorted, has been unbanned.
