### ISSUE TITLE
Pokemon with pre evo ability

### ISSUE THREAD

**Issue by ZodiacMate** [ObliqueNET/Server#561]
my corviknight has its pre evolution, rookidee's, hidden ability (big pecks) still when it should of changed to mirror armour.
![2020-06-28_19 47 13](https://user-images.githubusercontent.com/67540745/85944189-3d119d00-b978-11ea-9615-532bed07879e.png)
just wondering what can be done about this and just to let you know that corviknight seems kinda bugged
my ign is ZodiacMate

**Comment by fatyg5** [comment]
Looking at the stat files for Pixelmon, I see no way this is actually possible unless it's a bug within the mod itself. I'll leave this open until I confirm if it's something we can fix or not, but I'm doubtful.

**Comment by fatyg5** [comment]
Turns out the ability is not implemented by Pixelmon yet, so that's why it's not showing up. Closing this ticket
