### ISSUE TITLE
/rules command needs updating

### ISSUE THREAD

**Issue by JellyBlade** [ObliqueNET/Server#562]
- Rule 6 still mentions Terra, and alludes to other servers (i.e. Stratos) inside the oblique network, even though now it's just Oblique
- No mention of AFK machines being prohibited
- The lead listing at the end is a bit outdated, as Owski retired.

As a sidenote, the discord invite link on /rules doesn't immediately work because the link picks up the period at the end of the sentence, but that's minor.
![image](https://user-images.githubusercontent.com/4555773/85958873-2fe3b680-b956-11ea-9971-7821b44cb121.png)

**Comment by Rasgnarok** [comment]
Updated, AFK machines are not prohibited until we announce it so. I've passed the message to the rest of the mod team.
