### ISSUE TITLE
Ultra Space Issue

### ISSUE THREAD

**Issue by Vohras2** [ObliqueNET/Server#563]
Pokemon in Ultra Space currently zoom off into the sky when you approach them. I've tested this in singleplayer, and it doesn't seem to happen at all. That leads me to believe that -something- in our setup is causing the issue. The areas that I tested in were unclaimed as well, in case that matters.

**Comment by CenizaRey** [comment]
Interestingly, this bug seemed to get worse with 8.0, pokemon began flying into the air faster.

**Comment by RudolfShmitler** [comment]
An add on to this, it started as soon as the server reset I believe.

**Comment by Vohras2** [comment]
Get rekt nerd. Is fixed.

**Comment by Rasgnarok** [comment]
Fixed on July 5th, should have been closed then.
