### ISSUE TITLE
lost homes outposts and claims

### ISSUE THREAD

**Issue by ducky107** [ObliqueNET/Server#564]
Prior to the reset, I had set several homes including a townhome and an outpost, but now I don't seem to have any left. how can I get them back?

IGN:ducky107
Town:pogged

**Comment by Rasgnarok** [comment]
I assume your town was recreated as soon as the server came back up, but you'll have to reset your townhomes/outposts manually. Do you need any town claims?

**Comment by ducky107** [comment]
> I assume your town was recreated as soon as the server came back up, but you'll have to reset your townhomes/outposts manually. Do you need any town claims?

no but i dont knwo how to get back to my outpost where i had several item and chests

**Comment by Rasgnarok** [comment]
Do you have the coordinates to that location? or have done a /sethome on there? Otherwise you'll have to fly around sadly :/

**Comment by ducky107** [comment]
> Do you have the coordinates to that location? or have done a /sethome on there? Otherwise you'll have to fly around sadly :/

oh damn ok

**Comment by ducky107** [comment]
>

**Comment by ducky107** [comment]
oh damn ok
