### ISSUE TITLE
about town claims

### ISSUE THREAD

**Issue by ikaro72** [ObliqueNET/Server#565]
from stratos town, we dont have enough claims to cover the town and prevent people from taking stuff from chests which arent theirs, this could be fixed as more people join the town but as the warp to the shop is still active, we would prefer that atleast the shops are not lootable from strangers

**Comment by Rasgnarok** [comment]
I've just awareded 32 claims to Stratos. Please let me know if this is enough.

**Comment by ikaro72** [comment]
for the shops it is, but we dont have nearly enough for the entire town, though i think this will fixed whenever our members return; though we also have claims we won from events

**Comment by Rasgnarok** [comment]
If you can get me a list, I'll add whatever's next as extra. Adding now an extra 68 for a total of 100, since I really do want your town claimed too.

**Comment by ikaro72** [comment]
the claims we won from an event totals up to 50 claims, these were won from town tourney number 1

**Comment by Rasgnarok** [comment]
Added back 50 for the event ones you've lost! If there's nothing else, can I close the ticket?

**Comment by ikaro72** [comment]
that should be all, thank you a lot
