### ISSUE TITLE
Inactive Town Members

### ISSUE THREAD

**Issue by PrinceLokiii** [ObliqueNET/Server#566]
So it has kind of turned into a meme at this point about how my town (Galactic) has so many inactive players, but they enabled me to have all my claims and such so I never bothered kicking them. Now the problem is my town has no outposts so many of my active players do not have safe homes. I had used about 200 claims and had about 400 total, and 3 outposts. I had 46 members before the wipe. The chances of me getting all the members that had once been in my town before to all rejoin is very slim as I have no way of contacting some of them. Please restore my claims, thanks. :D

**Comment by Rasgnarok** [comment]
If they were that inactive, how much would you actually need? Sounds like I can restore about 250 and it should be fine, but let me know how much you need with your friends.

**Comment by PrinceLokiii** [comment]
250 should be fine. Yes I know the shame of having that many inactive players but hey, They allowed me to build up many structures. We also need 4 outposts please.

**Comment by Rasgnarok** [comment]
I think you should be able to add outposts on your own already, but correct me if I am wrong. I've added your 250 claims aleady though.

**Comment by pepperonipizza1** [comment]
Loki is busy at the moment so I will update what is going on, we seem to only have one outpost that we can claim Loki requested 4 and we can only create 1

**Comment by Vohras2** [comment]
Closing since refunded.
