### ISSUE TITLE
Missing Iv Vouchers

### ISSUE THREAD

**Issue by Deathboy5480** [ObliqueNET/Server#567]
Before the whole corruption thing went down, I had bought 10 iv vouchers from sgtsuperhockey for 50k. I used the vouchers on my poipole, and after the server was back up, the speed  ivs I added to my poipole were gone. If I could just get the iv vouchers refunded, that'd be great.

**Comment by Rasgnarok** [comment]
Just refunded your 10 IV vouchers! Sorry for that corruption, hope it's alright like this. If there's nothing else, please close the ticket <3
