### ISSUE TITLE
Magma's claims

### ISSUE THREAD

**Issue by TheTunzo** [ObliqueNET/Server#569]
I'll cut it short, magma might regain most of the claims we need in the following days (we need about 550 total to cover all we have built), but i don't want to risk having houses exposed since i have to wait for people to log in. So, can i get a refund of like 400 claims that, as soon as all the active people come back, you can take back? Also i probably won't be able to get my last outpost (the one you get with city at 50 members) so can i get that back too?

**Comment by Rasgnarok** [comment]
Refunded 400 claims to cover back your land, keep me updated in this ticket once you are back to your usual playercount in your town. Thanks!

**Comment by TheTunzo** [comment]
Ok, the town now has enough claims to survive without the temporary ones. However, in these days i've been reminded about some additional things lost in the corruption, such as the 25 extra claims won in the Town Tournament, the 25 bought claims and 70-75k (don't remember the exact amount, but my members can testify this is not a lie) that were in the town balance. So i ask if, instead of retrieving the 400 claims you gave us, you could only take back 350 (or in alternative 375 and give us 13k for buying back the claims) + the town balance money that was lost. Thanks in advance for your time.

**Comment by Vohras2** [comment]
Fixed, so closing.
