### ISSUE TITLE
Missing Items & Voucher

### ISSUE THREAD

**Issue by Tikitaco** [ObliqueNET/Server#570]
Hello Staff of Oblique!

I lost 1x Park Ball and 1x Gender Voucher when the server imploded and rolled back my inventory/data. The Voucher was bought off of Christo I think? (Not 100% sure) for 8K right before things got wonky. I've also lost ~10 claim chunks I purchased from the salesman for my waiting-for-approval shop. If you have the time, can you please replace these items and claims? Thanks!

IGN: Tikitaco627
Discord: Tikitaco#5613

**Comment by Rasgnarok** [comment]
Added back 1 Park Ball (sent to your inventory), your 15 claim blocks to your town, and 1 gender voucher (sent to your /vouchers). If there's nothing else, feel free to close the ticket ;)

**Comment by Tikitaco** [comment]
Thank you!
