### ISSUE TITLE
Missing homes

### ISSUE THREAD

**Issue by pie642** [ObliqueNET/Server#571]
Once the server came back up today, I logged on and a welcome message displayed, along with this all of the homes that I had set where no where to be found. It isn't too big of an issue if it cannot be fixed, but it would be appreciated if it could.

**Comment by Rasgnarok** [comment]
Heya! Sounds like you were one of the handful that had their full data wiped. You've no idea how sorry I am, it sadly happened to you and a handful of others whose data was most affected by the leak. I wouldn't be able to set back your homes without having coordinates. 

However, I can refund any inventory/money/pokemon as well as make back your loss with other rewards considering you likely lost a lot. Please let me know how to make it right!

**Comment by pie642** [comment]
I don't think I lost any Pokemon, Items, or money, so it isn't too big of a problem, since I all of my stuff at my town I didn't actually lose anything other than some quick ways to teleport to certain biomes. Overall, it isn't a big deal, and I should be able to replace the homes I once had.

**Comment by Vohras2** [comment]
Closing since this seems to be a non-issue. Thank you for being so understanding, pie642.
