### ISSUE TITLE
Town Lost: NewKing (Need More Chunks & Don't Know If Any Other Outposts Were Claimed)

### ISSUE THREAD

**Issue by LaterXavier** [ObliqueNET/Server#573]
I believe there were 30-40 chunks claimed in total before. I am LaterXavier who was previously a member of the town only a week or so ago but after reset I am now mayor. Newking_Lizards was the previous mayor and I haven't seen any of the members on since I have joined.

**Comment by Vohras2** [comment]
I've refunded you 50 chunks to reclaim the town and areas. Unfortunately, we can't refund outposts, so you will need to claim those. I think the town should have one by defualt.

**Comment by Vohras2** [comment]
Closing this for now. Comment more if you have other issues.
