### ISSUE TITLE
VibES' Claims

### ISSUE THREAD

**Issue by Matchichondria** [ObliqueNET/Server#574]
I'm not entirely sure on the exact amount of claims my town had since I was expanding and hadn't used them all yet, so I'm going to underestimate and say 30 claims. I only had one other member in my town, and we had a balance of 10,000. I also had an outpost, however, I wasn't there often because of the expansion of the main town area, so I think a refund of the 10000 and 30 claims is about right. Sorry for being so unsure of how many claims I had

**Comment by Vohras2** [comment]
Need your IGN please.

**Comment by Matchichondria** [comment]
My ign is Matchichondria

**Comment by Vohras2** [comment]
I've refunded your claims and I added the money to your balance. Feel free to comment if something else comes up.

**Comment by Matchichondria** [comment]
Awesome, thank you so much.
