### ISSUE TITLE
Missing loot

### ISSUE THREAD

**Issue by CptTCovenant** [ObliqueNET/Server#576]
After one of the recent downtimes on the server, the Uwu Lair town got corrupt. Most the members were removed form the town, and all the land was unclaimed. Because the land was unclaimed people raided our area. 
Here is a list of stuff I am missing. 
____________________________________________________
5 diamond blocks
29 diamonds
90 iron ingots
3 park balls
2 master balls
15 Beast Balls
2 stacks of speed balls
Full set of team rocket armor
Full set of team magma armor
Full set of team plasma gear
6 blocks of Ruby
5 blocks of Saphire
5 blocks of Crystal
6 blocks of Amethyst 

 A ton of other stuff I could care less about.
_________________________________________________
*the people who took my stuff has 4 of my Minecraft heads too*

**Comment by Vohras2** [comment]
Refunded so closing.
