### ISSUE TITLE
Rhyolite's Claims + Chunk Error

### ISSUE THREAD

**Issue by yraf** [ObliqueNET/Server#577]
IGN: yraf

My town, Rhyolite, had 175 total claims before the error. I had 4 town members in it that helped me get that number, all of whom are now inactive. I don't know if all 175 claims are necessary but it would be helpful

Some chunk error also occurred during the data corruption, and a chunk from my town got seemingly replaced with a nearby chunk, which also happened to be my main chest room. The imgur link has the screenshots

https://imgur.com/a/CgQwixy

The first screenshot was before the server went down, the other two were after. Coords are 5280 66 7735

**Comment by Vohras2** [comment]
I've refunded the claims. We'll deal with the error this weekend.

**Comment by Vohras2** [comment]
Closing since refunded.
