### ISSUE TITLE
Quests Issue

### ISSUE THREAD

**Issue by matts421** [ObliqueNET/Server#578]
All of my quest progress was reset. I'm not sure if you have any data on what quests I did, but if need be I can try and detail up to what point I finished in the quests. My IGN is Smithsonite_.

**Comment by BlitzAsogi** [comment]
If you can list the quests that you've completed, any online QD can help you set their progress to complete

**Comment by matts421** [comment]
PrimalCyndaquil manually went over all of the quests with me and reverted my progress. Thank you to all those involved in helping me. Closing ticket now.
