### ISSUE TITLE
Village claim erase + someone claim over it 

### ISSUE THREAD

**Issue by lovetodead** [ObliqueNET/Server#579]
IGN: lovetodead

My town, Village, had a base before the error (the error occur between the server restart and when i make the ticket , i don't know why my base was unclaim itself ). I had 2 town members and we are active.  But now someone just stole our claim base and i can prove it , last day my girlfriend work on the front window so i have some screen , anyways , so the guy stole our stuff and claim over our base and i don't know how to get back all my stuff and my base . The name of who claim over it and actually stole our base and stuff is TinyBananas ( btw he use our ressouces and pixelmon item for only god and moderator know )
Ps: TinyBananas is the name of the town ,i think 
Coords are -61 63 -7675

i give you some screen of my base .
![claim stole](https://user-images.githubusercontent.com/1359965/86442829-a85bc600-bd0e-11ea-9449-94913f318c09.png)
![girlfriend who work on the base](https://user-images.githubusercontent.com/1359965/86443140-1ef8c380-bd0f-11ea-829a-5e2840cdacdf.png)

ps: one more proof the sign are ritten in french and we are french ( by the way sorry if i make something strange with the grammar ) 

PS: i just see the mayor change ( not a big threat but well ^^' )

**Comment by BlitzAsogi** [comment]
their claim has been deleted, issue resolved.
