### ISSUE TITLE
Quests Issue: Bigger problems

### ISSUE THREAD

**Issue by Christodynamics** [ObliqueNET/Server#580]
The bigger issue with this whole quest reset fiasco is that only **some** people have lost their entire quest book progress and not everyone. For people who have gotten this, its a boon or a bane depending on the person having the issue. You can legally do all the quests again and get 2x rewards, 2x money, 2x legendaries (https://github.com/ObliqueNET/Server/issues/575), or you can just not tell people that you have been reset. Or u can just ask for the quest progress to be reinstated (i haven't seen this being given yet, only asked). These people have the option. But what if u had the shorter end of the stick? What if your quests did not get reset? You dont even get the opportunity to gain the 2x rewards, 2x money, 2x opportunities.

In my opinion this isn't fair.

EDIT: language

**Comment by Hiroku** [comment]
Whether or not the situation is unfair seems to ignore the fact that it's the result of a random and destructive server issue that was not in any way planned or desired. And let's not forget that people lost more than just quest progress, and even if they were to get everything refunded it's still extraordinarily inconvenient not only for them but for the staff that have to orchestrate this. I get the sense that you're angling for everyone to be able to just reset their quests so they can get the x2 rewards, but that's an enormous pile of work to add on to what is already a painfully large pile of stuff to do for staff.

**Comment by Christodynamics** [comment]
i get what you're saying. closing this issue from my end
