### ISSUE TITLE
Pokemon Issue

### ISSUE THREAD

**Issue by Thepigmaster99** [ObliqueNET/Server#581]
Hi,

Yesterday I lost the half of the pokemon that I have and I don’t know why. I started playing yesterday and I done the first quest but when I enter again I lost almost the half of the pokemon I had. If I could recover all those pokemon it would be fantastic, thx for all.

**Comment by BlitzAsogi** [comment]
We had a couple issues with the server and data corruption, if you could provide your username and a list of the important pokemon you lost, we can refund them.

**Comment by Thepigmaster99** [comment]
Ok, my username is Thepigmaster99, and the pokemon I lost were: Kadabra, Zorua, Luvdisc, Larvitar and Geodude. They are not really important but I lost them and I don’t have really better pokemon, thx for all.

**Comment by Vohras2** [comment]
Refunded.
