### ISSUE TITLE
My town pikatown

### ISSUE THREAD

**Issue by Snipseyy** [ObliqueNET/Server#582]
Hi ras you have to give me back mayor as well as our claims + money we had 12k and like 6 different plots and now we have nothing my town can't get them claims back
![Screen Shot 2020-07-03 at 10 28 14](https://user-images.githubusercontent.com/67781249/86449101-f628fc00-bd17-11ea-891f-2dacdf5c1952.png)

**Comment by Snipseyy** [comment]
look in the bottom right corner

**Comment by Blokus12** [comment]
I have added 100 claims for now

**Comment by Vohras2** [comment]
Closing since this was refunded.
