### ISSUE TITLE
Pokemon deleted by market

### ISSUE THREAD

**Issue by TheTunzo** [ObliqueNET/Server#584]
Yesterday the market reset and i lost my 3 unbreedable mons:
Riolu 5 iv missing sp.att, jolly prankster (listed for 9k)
Beldum 4 iv missing sp.att and defense, jolly clear body (listed for 15000)
Corphish 5 iv missing sp.att, adamant adaptability (listed for 9k)

my ign is TheTunzo

**Comment by Vohras2** [comment]
Refunded.
