### ISSUE TITLE
NukingLizards Town Delete 

### ISSUE THREAD

**Issue by NukingLizards** [ObliqueNET/Server#585]
I've lost over 100 purchased claims and all my town members except for LaterXavier who became the new mayor. I am the original mayor of NewKing (Named after my name Nuking). I lost my outposts and about 5k in town bank. I need this to be fixed ASAP so i can reclaim my town and restore all plots for my town members
![image](https://user-images.githubusercontent.com/64395766/86469168-37eb8e00-bd7c-11ea-8705-11c605af6c04.png)
Xavier took screenshots of chest so if players loose any items they can be reclaimed 

****What i want to get out of this?

- My town Back (me as mayor)
- My Outposts Back (2)
- My Purchased Claims (100/150)****

Please help asap

Kind Regards
Nuking_Lizards

Discord:
Nuking_Lizards#4702

**Comment by NukingLizards** [comment]
**Update** im now mayor again

**Comment by Vohras2** [comment]
Refunded.
