### ISSUE TITLE
Claims gone

### ISSUE THREAD

**Issue by ToothlessOblique** [ObliqueNET/Server#587]
I don’t remember the exact amount of claims I had but I know I had at least 50 that are now gone and would just like to be able to have them back or the money for them, whatever is easiest..?

**Comment by Vohras2** [comment]
What's your IGN?

**Comment by ToothlessOblique** [comment]
__Toothless__

**Comment by ToothlessOblique** [comment]
Didn’t show up right.. it’s Toothless with 2 underscores before and after.. 

 ..Toothless.. 
replace periods with underscores

**Comment by Vohras2** [comment]
I've given you 50 claims. Let us know if you have any more issues.
