### ISSUE TITLE
items from shop gone - item frames

### ISSUE THREAD

**Issue by BootyHadMeLike** [ObliqueNET/Server#588]
When my shop was shut down and filled with barrier blocks, all the item frames and items within those frames were removed, as they are not considered a full block, If a rollback is possible, that'd be ideal because I also had pictures for each of my pokemon breeds tagged and I'm kinda low on film lol. If a rollback isn't possible, I'd be okay with just receiving some of the harder to obtain/expensive items that were in the shop such as destiny knots, everstones, master balls, battle items, etc. and I can handle the rest. It'd probably be annoying having to spawn in one of each item lol. Losing one of each item is quite a bit of value, but losing 1 Pokeball, block, or berry, or something like that isn't a big deal. Someone left a chest with stacks of the item frames, so Canary started placing them back already and we filled in some items already. Either solution would be good with me.

![itemframes](https://user-images.githubusercontent.com/48974203/86492855-5716fb00-bd3d-11ea-8c8c-94b6b4a3a869.png)
![itemframes2](https://user-images.githubusercontent.com/48974203/86492857-58e0be80-bd3d-11ea-8c84-6987b41f0f13.png)
(The item frames were above chests btw)

ALSOOOO, Can I please get my Darkrai c: Canary and I both had the letters ready before this all abruptly happened and it was still June (is my fav legend cmon man).

ALSOOOOOOOO (pt2.) My shop warp is not working currently! (Probably shouldn't be if it is to be rolled back tho)

Oki that's all I think, appreciate it!

**Comment by Vohras2** [comment]
Refunded.
