### ISSUE TITLE
Back to Poke, and no claims

### ISSUE THREAD

**Issue by Gorion92** [ObliqueNET/Server#589]
I was "great" rank, and I'm back to poke. Now I can't warp to any homes because I have 7, and poke rank only allows you to have 6.
I also have no claims in my town. Please help me! I used to have about to 59 claims.

**Comment by Gorion92** [comment]
I also need my 30 quest points.

**Comment by Vohras2** [comment]
Dealt with, aside from the quest issues. Please see a QD about those.
