### ISSUE TITLE
Town was griefed 

### ISSUE THREAD

**Issue by MrSparxxx** [ObliqueNET/Server#594]
My town was griefed after the corruption and i lost a bunch of things. Dogi the mod got all my items from my chests back into them. But he was unable to pick up the shulker boxes that were in my base. One of the shulker boxes had 40 diamonds, 64 stack of aluminum ingots, 64 stack and 32 stack of iron blocks, 20 gold blocks. Another shulker had all the power items for EV training. Also the town was 6 claims but i reclaimed so no one stole the items i got back from Dogi.

Pc and healer aswell.

IGN: GoogleMySkiIlZ

**Comment by Vohras2** [comment]
Closing, since I think Dogi refunded. If not, please let us know.

**Comment by Rasgnarok** [comment]
Awarded back 10 claims to cover the 6 lost in the unclaim data corruption. Thanks!
