### ISSUE TITLE
items stolen from chests in pikatown

### ISSUE THREAD

**Issue by rappersjon** [ObliqueNET/Server#595]
ive noticed some pretty valuable items were missing from my chests after the town system got fcked up things like rare candy's etc.
username : rappersjon 
town : pikatown

**Comment by Rasgnarok** [comment]
Has this been addressed yet? I'll forward it to moderation.

**Comment by rappersjon** [comment]
No it has not been adressed yet :D

Op di 14 jul. 2020 20:30 schreef Rasgnarok <notifications@github.com>:

**Comment by Vohras2** [comment]
Refunded.
