### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by SaeedBon** [ObliqueNET/Server#596]
I got banned for Looting an outpost post-corruption. I don't know what this means but I didn't loot anything.

**Comment by ElementalMP** [comment]
So you did not go to an unclaimed outpost and steal items and blocks from inside the home?

**Comment by SaeedBon** [comment]
Do you mean an unclaimed base, because if so I did, but did not know it was against the rules

**Comment by ElementalMP** [comment]
Since you have only joined today, I will give you a second chance. I suggest you read our server rules, and follow them so this does not happen again. Your account has been unbanned.
