### ISSUE TITLE
/t setcolour rgb problem

### ISSUE THREAD

**Issue by Katadreme** [ObliqueNET/Server#597]
Apparently a well known problem, but seems like no one ever made a ticket about it. The cmd /t setcolor which uses rgb values, makes the colours yellow, pink, purple, black, white, grey, cyan and some others unobtainable. We deduced that, any green value below 85 doesn't exist, any blue below 86 doesn't exist, and any red value that's not dark_red doesn't exist, and refuses to influence the rest of the colours. For example, the values for pink is 255 192 203, whoever in game it gives:
![Screen Shot 2020-07-08 at 6 55 35 pm](https://user-images.githubusercontent.com/50907133/86899045-cf6e2980-c14c-11ea-96c2-17d50e1dc322.png)

**Comment by Vohras2** [comment]
Going to close this, because we have an older feature request for this on the github.
