### ISSUE TITLE
Server crash last week

### ISSUE THREAD

**Issue by Snipseyy** [ObliqueNET/Server#598]
This week i also realised stuff from my chest was missing. I have looked through them and some scarf items as well as 2 mballs are gone. Not only that i am also missing a full doublechest of megastones thats around 200k pokedollars worth of quicksell value. Could you please help, i don't need all the mega stones back if money is easier.
![Screen Shot 2020-07-10 at 20 59 47](https://user-images.githubusercontent.com/67781249/87189089-53144b80-c2f0-11ea-8bfe-fe80788f689c.png)

On this screenshot the 2 mega stones are ones that i have found

**Comment by OrangeSodaPop** [comment]
Resolved
