### ISSUE TITLE
Issue - Wailmer Pail not working

### ISSUE THREAD

**Issue by byuiwriter** [ObliqueNET/Server#599]
I use a wailmer pail on my apricorns and the last couple times it has not worked properly in advancing the apricorn to the next level. I initially noticed the issue when there was a lot of lag which sometimes causes problems with the apricorn farming and i left it thinking it would work later, 
I tried it again about a day later and there was still some lag (this is around when Ras turned off rustles to try to help with lag), and i left it again.
I am trying now when there is not a lot of lag and like before the apricorns are not advancing.
Our apricorn farm is below ground and unaccessable to players not within our town and I verified each time that my town members have not harvested them

**Comment by Rasgnarok** [comment]
Do you think you could try to reproduce in singleplayer? Yes server latency affects crops, but it should not be causing it still. Keep me updated!

**Comment by byuiwriter** [comment]
The same thing happens in a singleplayer world. The wailmer pail does not advance the apricorn.

**Comment by Quadehar97** [comment]
I can confirm that this works on the server with no issues on my end

**Comment by Rasgnarok** [comment]
This should be reported to https://www.pixelmonmod.com/tracker.php?p=2, as it's a Pixelmon mod bug, so the Reforged team has to address it.

**Comment by byuiwriter** [comment]
Trying again today, the wailmer pail is working, should i still make a ticket for Pixelmon?

**Comment by Rasgnarok** [comment]
If it works now, then we should be good to go. Closing as it's been fixed.
