### ISSUE TITLE
Breeding glitch

### ISSUE THREAD

**Issue by Snipseyy** [ObliqueNET/Server#600]
Rn there is a breeding glitch which prevents you from breeding your pokemon if you leave the chunk i togheter with katadreme has tested many different areas and pokemon with no succes please look into the issue. I believe whats happening is that the pokemons names turn into "uknown" but we don't know.

**Comment by Snipseyy** [comment]
forgot to give a screenshot so here
![Screen_Shot_2020-07-14_at_8 45 03_pm](https://user-images.githubusercontent.com/67781249/87417111-ff478200-c5cf-11ea-9a7a-d43c34f55395.png)

**Comment by Rasgnarok** [comment]
This is a Pixelmon bug, please report to the Reforged bug tracker: https://www.pixelmonmod.com/tracker.php?p=2
