### ISSUE TITLE
/market add improvement suggestion

### ISSUE THREAD

**Issue by CenizaRey** [ObliqueNET/Server#602]
A proposal to add a safety net to the /market add command by requiring the player to input the name of the pokemon they're trying to sell at the end of the string.

Example:

/market add 4 7500 pikachu

This will prevent ricebrains like myself accidentally naming the wrong slot and listing an unintended pokemon on the market

**Comment by Hiroku** [comment]
Added dialogue confirmation screen for ricebrains like Cen ready for next restart
