### ISSUE TITLE
Suspected Alt

### ISSUE THREAD

**Issue by Bewwee** [ObliqueNET/Server#604]
Hello staff,
My brothers / family minecraft account (the username was Cumbrus now its Fqxxx) was banned because it was supposedly an alt of mine.
Is there any way to undo it (he's 8 and playing on my pc because he's too young to get his own.) he really wants to play Pixelmon.

Regards
Bewwe,

**Comment by fatyg5** [comment]
You personally admitted to a staff member that you were using that account yourself and knew it was against the rules. 
![unknown-17](https://user-images.githubusercontent.com/8277657/88494976-6c6ef600-cf86-11ea-9220-ada9d84a2949.png)

**Comment by Bewwee** [comment]
Yes thats true, i called it my alt because i bought it for my brother to play with me so i call it alt or family account.
I started playing on the account because i wanted my brother to get a fresh start.
I gifted myself my froakie because its my favorite pokemon and if staff wouldnt ask me if its my alt i wouldnt use / abuse it to get items , pokes.

**Comment by Bewwee** [comment]
Me and my brother wouldnt mind a stats/starter reset, cuz he rlly wants to play.
I have the Froakie (evolved into a greninja) in an seperate PC box.

**Comment by fatyg5** [comment]
You're unbanned. If this happens again, expect an indefinite ban.
