### ISSUE TITLE
Ban Appeal 

### ISSUE THREAD

**Issue by oxsei** [ObliqueNET/Server#605]
I reinstalled the ATLauncher with intentions to play on your Oblique pixelmon server with my friends, however upon joining I was greeted with a ban message stating: Racism/spam upon joining? I don't remember committing these offences as the last time I played was most likely over a year ago. I would like to apologise for any hateful or unnecessary messages which I may have said in the past. I'm hoping that you can forgive me, and enable me to play on your server as I have since matured and realised how childish I must've been to say/spam such things. As I stated before, I'm extremely apologetic for anything that may have been said previously and hope we can overcome this issue.  (the ban has no date stated so I presume its perma)

IGN: oxsei

**Comment by fatyg5** [comment]
This ban was issued a year ago, actually, so I don't have any evidence anymore. You will be unbanned, but if you cause any immediate trouble, your ban will be quickly reinstated.
