### ISSUE TITLE
Lucario breeding bug

### ISSUE THREAD

**Issue by lexjo** [ObliqueNET/Server#607]
![lucariobreed](https://user-images.githubusercontent.com/17412315/89134388-b3c42c00-d51c-11ea-886e-6623c2e5c3db.PNG)
Lucario will not breed on steel type breeding blocks (iron blocks), yet mawile is able to.

**Comment by Rasgnarok** [comment]
Is it still the case? It's not reproducible for me, so please a new ticket if it's a continuing issue. I know that a lot of visual, sync bugs happen with Pixelmon, and that's something that only the mod can address https://www.pixelmonmod.com/tracker.php?p=2
