### ISSUE TITLE
Get stats command (/gs) is broken? 

### ISSUE THREAD

**Issue by matts421** [ObliqueNET/Server#608]
Not really sure why, but /gs brings an error now when executing it.

**Comment by Rasgnarok** [comment]
![image](https://user-images.githubusercontent.com/18584380/91361999-796e4780-e7c7-11ea-95e1-c36c74554756.png)
error from EMPC, has to be updated

**Comment by Rasgnarok** [comment]
Fixed, plugin has been updated for next restart.
