### ISSUE TITLE
ban appeal igivelfurfre

### ISSUE THREAD

**Issue by billy420blazeit** [ObliqueNET/Server#609]
ign: igivelfurfre
reason for ban: harrassing multiple players and being offensive

I was only talking to one person in private messages and used mild language. Nothing i said was offensive.  sorry i wont say bad words anymore. this server is fun and i have a mewtwo.

**Comment by ElementalMP** [comment]
Normally I would accept an appeal such as this, however I don't believe that "Mild Language" and "Nothing i said was offensive." are entirely accurate. 
You told a player to, and I quote: "Suck your fat cock" and called them a pussy, before telling them that noone would want to help them out. 
It was clear to you that the other player was uncomfortable, and you continued anyway. This shows me that you had no respect for our rules, of the wellbeing of other players on our server. As such, I will not be unbanning your account.
