### ISSUE TITLE
Ban appeal Discord

### ISSUE THREAD

**Issue by MKFusionn** [ObliqueNET/Server#610]
Nick: Fusion#5752 
Reason: Posting an +18 image

i got banned like 2/3 years ago and honnestly i dont know why i posted that picture on the discord chat... i guess i was just beeing a child, but now im a new person im not a child anymore so if you coud forgive me i would be apprecieated

**Comment by fatyg5** [comment]
Generally, we do not issue Discord bans, but since this happened long ago, you will be unbanned. Breaking any Discord rules will immediately re-implement this ban.
