### ISSUE TITLE
Permaban

### ISSUE THREAD

**Issue by BoXLiGhTeR226** [ObliqueNET/Server#612]
I'm sorry, I insulted someone because they stole my glowstone 3 times that I had hard to recover in the nether, because I'm trying to build a pokemon arena for me and my friends, yes I would have of the claim but I already had a claim, every time I connected to the server the guy had stolen all my glowstone and after the 3rd time, like a retard i insult the guy instead of reporting it to the staff

**Comment by Rasgnarok** [comment]
Hello Box, 
I reviewed your ban, and though we do not condone the usage of the word 'faggot', it clearly was out of anger and should not have warranted a permanent ban. You have now been unbanned. Please DM me directly to sort out your grief, as I know that staff was looking into the grief. Please accept my apologies on the preemptive ban, my bot knows no discrimination when it comes to trigger words.
-Owner, Ras
