### ISSUE TITLE
I was permabanned cuz I was accused of duplicating when I didn't, i opened an unclaimed a chest full of stuff which to me and my friend (aquatic76) seemed like a giftbox so we took stuff from it and both got banned 

### ISSUE THREAD

**Issue by Epicfinley1** [ObliqueNET/Server#613]

**Comment by ElementalMP** [comment]
Can I get an IGN here? Seems you have added your friends, but not your own.

**Comment by Rasgnarok** [comment]
Closing, no response for over two weeks. Please open a new ticket if you are still interested in applying to your ban, @Epicfinley1 .
