### ISSUE TITLE
Xray Permaban

### ISSUE THREAD

**Issue by ChunkyCheeseRat** [ObliqueNET/Server#614]
Dear Oblique team,
I have been permanently banned because i stupidly used xray. I used it to get a good start and after realising that it was cheating i deleted it. I used it i think 2 days ago and just got banned today. I am sorry for using a banned modification of the game and i have learned to not do it again. I whould really enjoy playing on your server again. Of course the ban was rightfull, but i think its a little to harsh to instantly permanently ban don't you think? Anyways i whould be really happy if it was something like a Week ban, or even a month. I am again sorry for cheating on your network and it wont happen again.
With big regards 
ChunkyCheeseRat

**Comment by ElementalMP** [comment]
I would think that usage of an unfair modification such as xray would be something you would assume to be banned on a server, not something you would find out to be banned later on. As such, I stand by the notion that a permanent ban is warranted for a situation such as the one you have put yourself in. 
That being said, it would appear to me that you realize now the severity of the issue, and will ensure nothing like it happens again. 
I've unbanned your account. 
Please read our rules, and make sure to use your second chance for good <3
