### ISSUE TITLE
Betrayer's Oubillette warp not working

### ISSUE THREAD

**Issue by ZackieKun** [ObliqueNET/Server#615]
So, for a while I was stuck on trying to complete quest. (Boss mon hurt). I decided to give it a try today, but I keep in a never ending loop of: Click the bed, don't get warped, blue text pops up anyways. Rinse and repeat.

**Comment by ZackieKun** [comment]
Excuse my spelling. Oubliette

**Comment by menno516** [comment]
this has been fixed and should not happen again.

thanks for letting us know 
<3
