### ISSUE TITLE
[IGN: mmoneypenny] Crash on Load - Corrupted Pokemon?

### ISSUE THREAD

**Issue by mrjalalo** [ObliqueNET/Server#616]
so i messed up, i alt + f4'd when i was evolving my oddish because i forgot to press cancel evolution, and now my screen turns blue and crashes whenever i join the server. if it makes it easier i dont really need the oddish ill just catch a new one if it needs to be deleted.

**Comment by Hiroku** [comment]
Wow that is pretty messed up. Do you know how to find errors in your logs? I'd be interested to know what sort of corruption it is before we yeet the Oddish

**Comment by mrjalalo** [comment]
[2020-08-20-3.log](https://github.com/ObliqueNET/Server/files/5101051/2020-08-20-3.log)

I think i did that right, i tried skimming through it but i dont really know much about programming

**Comment by mrjalalo** [comment]
im not sure if anyone fixed it, but i was able to load in after several attempts. thank you for your time

**Comment by Hiroku** [comment]
You did indeed, that's a very interesting error. I didn't do anything to fix it, but based on the error it was something you were looking at ingame that caused it. I noticed there was some spam from Pixelmon itself saying "Oricorio". It might not actually be related to the Oddish and instead something you were looking at ingame. I've contacted a Pixelmon developer with that error in case it's that.
