### ISSUE TITLE
Dawn Wings Necrozma turned into Dusk Mane Necrozma

### ISSUE THREAD

**Issue by HyunAe13** [ObliqueNET/Server#617]
When I was doing the Brimstone Battles quest fighting the boss I did the ultra z move for necrozma and instead of turning into ultra necrozma, it turned into dusk mane necrozma. I need help to change it back with pokedit or something. I cant split the Necrozma and solgaleo apart because i only did the Lunala quest.

**Comment by HyunAe13** [comment]
my ign is Hyun_Ae

**Comment by Rasgnarok** [comment]
Has been resolved, the quest is no longer active. Please repost a new ticket if it hasn't been solved for you!
