### ISSUE TITLE
My dono rank isn't activatting.

### ISSUE THREAD

**Issue by LofiBear** [ObliqueNET/Server#618]
For some reason my dono rank won't activate, idk if i messed it or the sever is being big dumb dumb.
Here is the email to show i did buy it.

**Comment by LofiBear** [comment]
i didnt know the screenshot was gonna be that big, mybad

**Comment by Rasgnarok** [comment]
Removed the image because it has sensitive information. Can you please DM me on Discord directly so we can sort it? According to your payment method, eChecks can take up to 7 business days to activate.
