### ISSUE TITLE
Quest soft lock 

### ISSUE THREAD

**Issue by menno516** [ObliqueNET/Server#620]
When doing certain quests and fighting a boss mon, like xerneas, and you get disconected by some reason (bad connection or kick) you will get soft locked.

The quest will just say _"defeat xxx"_ while thinking you are still in a battle with it and not moving you back a stage.
the only way is for a quest designer to set you back a stage so you can go do it again.

![image](https://user-images.githubusercontent.com/63118334/90992246-c1665200-e5ae-11ea-9d4a-33b5d6ab0e66.png)

**Comment by starwarschamp4** [comment]
Does the quest have a log_off stage? If it doesn't then that should fix that issue.

**Comment by PrimalCyndaquil** [comment]
Life and Destruction now has Log-Off objectives for each of these battles in the case of a crash.
