### ISSUE TITLE
Milestone Vote Rewards

### ISSUE THREAD

**Issue by Vohras2** [ObliqueNET/Server#621]
Players have been reporting that they didn't receive milestone vote rewards after the crash from a few days ago. I personally was able to get mine before that crash, but I don't know about the general population. Ras set me a couple of days ahead to test, and I did indeed receive them.

**Comment by Hellblox** [comment]
Hi, how are you doing? i am doing pretty bad today. I was baned on mindecraft

**Comment by Rasgnarok** [comment]
Closing as milestones are completely broken. Apologies for the lack of refund at the present time, but I will need to change plugins and reset everyone's milestones. For now, I will be closing all tickets to be fair to everyone else that lost their milestone rewards between Oct 2020 to Jan 2021.
