### ISSUE TITLE
ElCampro - Stealing Ban appeal

### ISSUE THREAD

**Issue by ElCampro** [ObliqueNET/Server#749]
So today in the morning i was banned witouth the bennefit of the doubt but as also because i stole stuff from a neighboor house, wich i didnt know he was going to come back, of course i told the lead of the town, that i grabbed items from the other house and kept it as mine, didnt used his items if i can remember and i can recompose the damage done (for the items, like giving them back and more), im very sorry for what i did earlier, i hope i can be forgiven for what i did and i can recompesate the items that i just stole if you give me the chance, i really like the server and i dedicate almost the entire days on it.

Thanks.
-ElCampro.

**Comment by ElementalMP** [comment]
Hi there! I am looking into some background information on your ban, so as long as there is nothing else you would like to add, I will get back to you within a few days.

**Comment by ElCampro** [comment]
well, i just wanted to add, that indeed im guilty from stoling stuff from a neighbor's house, and i can give the items back to compensate the damages done, i want to deeply apologise for disrespecting the server rules, that im so sorry and it will never happen again, as im also in love in the way the server works, but on the precise part that i unfollowed the rule#3, i deeply regret doing that, as the major of the town told me that i managed to loot it and get the stuff because a kindda time ago there was like a global bug or something that made town and chets unprotected, as again, im sorry for what i did, i hope i get the admins and everyone's pardon and never do that again.

**Comment by ElementalMP** [comment]
As much as I would like to unban your account, I cannot do so in good faith. You have been warned to read the server rules on 2 separate occasions. Once on Aug 19th, and again on the 21st. You knew the server rules, and went ahead and did it anyway. The town's owner has told me that he had nothing to do with the act itself. I am just confused as to why you would go ahead and do something like this. You clearly enjoyed the server, and you knew the rules when you did it, and  you knew we'd catch you. So, why?

**Comment by ElCampro** [comment]
The first warn was because i sayed the N word in public chat knowing the rules, but i deeply apologised with everyone in the public chat after i did that, i beg for a pardon not only for you, but for the entyre server staff and community, i dont know what to say for all of those idiotic acts, but as also i broke those 2 important rules of the server _(dont get me wrong, all the rules are important to follow to keep an order)_  ,im so sorry for all of this, and i know its getting repetitive but i beg you to please forgive my attitude, i can give the items  back or something else, i can make an apology video or more, eventough it sounds crazy, i was in love with the server and the way it worked, it is a literal "NO P2W" and there are no other servers like this, im so sorry, im sorry with everyone , community and staff.. im sorry, i will become a better person, i promise.

**Comment by ElCampro** [comment]
This is gonna take a while.

**Comment by imsorryguys321** [comment]
yeah ele is a lazy as bitch
