### ISSUE TITLE
LevelLock Abandonware and Quality of Life

### ISSUE THREAD

**Issue by ThirstyMichael** [ObliqueNET/Server#764]
Feature Request to update the LevelLock plug-in used on Oblique to expand on the base mod mechanic of evolving eligible Pixelmon via Rare Candy at level cap to reduce strain on staff caused by the evolution bug, and to add more flexibility in player choice/mistakes.

Cross-Posted on the Mod Forum here: https://www.pixelmonmod.com/viewtopic.php?f=146&t=27877

Thank you for your consideration.

**Comment by Hiroku** [comment]
Resolved on next restart, it's an Oblique specific issue and while I do hate touching the level lock code, I was able to make a fix
