### ISSUE TITLE
I am sorry elemental for being a bad person. Lets just pretend i didn't say anything in the last 3 weeks. ples unban.im sorry

### ISSUE THREAD

**Issue by imsorryelemental321** [ObliqueNET/Server#765]
im sorry elemental I have no friends now. my mom beats me and my dad left me. please lemme play agen i wont do bad things.

**Comment by imsorryelemental321** [comment]
As I lay here in my bed recalling all that I've learned, I am thinking about all that you and I have experienced and been through together (good and bad) and my actions of the past.

I am incredibly embarrassed and ashamed for all the bad that I've said and done, all the arguing and yelling, more importantly the embarrassment and unequivocal hurt and sadness I have caused you. It's so hard to think of the tremendous damage I have caused to break apart every good thing you were trying to build for us, for our future.

I was feeling hurt and lost in our relationship, with the arguing and disagreeing and was feeling threatened by mention of Marlon and other worries on my mind. And not knowing exactly how to reach out to you and talk to you made me feel lost.

Those are just my feelings and not excuses or blame. I take full responsibility for what I have done, and do truly want what is best for the entirety of you.

You are right, I do have high emotions and where we were concerned I wasn't strong enough. My insecurities and inability to effectively manage how I was feeling at times has caused me to lose my best friend, my confidant, my partner and the woman whom I was surely going to marry.

I wasn't there for you the way I should have been, the way you needed me to be there for you, for our relationship. You must have felt so alone and so sad and so hurt. I feel alone and sad and hurt now because of my own thoughtless actions.

I have been focusing and working a lot on myself in that area. I have learned a great deal on how to manage and effectively communicate what I am feeling. I really want to thank you for helping me to identify that. There was a lot that I didn't realize and experience until you came into my life. You have helped me grow and learn so much.

These are my words which probably don't mean a thing to you now, but I needed to let you know the truth about how I feel and the truth about what is and always has been. Every mean, deep cutting, cruel, hurtful, and horrid thing I ever said to you, I want you to know, need you to know, that those are not my true feelings.

You are such a wonderful person. You are phenomenal, and magnificent and brilliant, you have effected me so profoundly. You must know that every mean thing I ever said was said out of pain, a lot of hard, deep, undiluted pain.

You will say that I've said these things before but the difference now is that I've done it. I have corrected and changed the faults within myself that caused the rift between us and I am continuing to take advantage of the help that I've found.

I didn't take these steps and make these changes because of some manipulative ploy or plot to get you back, because I have accepted the breakup, and have come to terms with it, and I understand why you chose to discontinue and why you feel the way you do towards me.

I also understand why and how you could think I am manipulative, because I have made apologies before but I didn't hold long to the promises I made or the things I expressed in those apologies and I know that it seemed that when things were back to normal I would revert back to the actions and attitude I had before I apologized.

I also want to add that any guy would be so lucky to have you, I was so lucky to have you, and I will continue my efforts in bettering myself as I am becoming a much better person. I can't thank you enough for all your efforts and all the care and attention you put into me and our relationship.

I had felt lost and in the dark and didn't see that I had all that I needed in you to help me get through anything.

And now, I want to say that I am sorry. I imagine that this means nothing to you anymore and no longer holds any weight but I feel a universe of remorse for all that I have said and done to cause you to feel the way you do. You have given me so much and shown me so much and I will forever be thankful for the profound effect you've had on me and in my life.

I know I didn't show you the appreciation I should have, but I must inform you now, that although I said things and did things to the contrary, I did appreciate you, so much.

I know there are no words that can make up for the sadness and pain that I've caused you and while I pray for your forgiveness I do not and cannot expect it. I am prepared and willing to accept that you will not forgive me. I just wanted you to know the truth about how I feel. I have learned to effectively use the experiences of the past to help with my efforts in making myself and my life better.

I've thought about writing this for a long time. It was not easy in the least. I thought to myself "how in Gods name can I make peace with her after that last email that I sent her? How, in all Gods creation will she ever be able to move past that?" This is where that emotional counseling comes in.

I was shown that we cannot allow our fears of rejection to discourage us from making a sincere and honest effort in trying to correct our mistakes of the past or make peace with people that we've hurt, we cannot allow that dread to prevent what could be a positive outcome. But instead to acknowledge and accept that rejection is a possibility and to utilize that as a deeper lesson as to the harm that our thoughtlessness and not being in control of our emotions can inflict on the ones we love as well as ourselves.

This was one of the steps taught, to attempt to make peace with people in our past whom we've hurt or hurt us or had a misunderstanding or falling out with etc. And whether the result is positive or negative, whether they accept or reject our apology is up to them, and is ok because we at least tried and we can use that towards self betterment.

No matter the reaction of the person or people we try to make peace with we can use it as a positive dose to our efforts.

I have asked God to forgive me for hurting one of his angels. I know I will have to answer to him some day. I have made peace with myself and with God, now I want to make peace with you. Once more I want, need, to say, with every iota of sincerity and feeling and with every beat of my heart, I am sorry. I will take that to my grave and into the afterlife.

**Comment by imsorryelemental321** [comment]
I have asked God to forgive me for hurting one of his angels. I know I will have to answer to him some day. I have made peace with myself and with God, now I want to make peace with you.

**Comment by ElementalMP** [comment]
Let me make this very clear. What you have done to this server cannot be forgiven. You have caused me many hours of stressful, wasted time banning you from the server, discord and tracke, over and over again, the constant threats on my life, and the slew of insults.
 I will not forgive you, and neither will the players, who want you around even less than I do. They will not forgive you.

 You will NEVER be unbanned. 

If you continue this, I will ensure you are banned en masse from the majority of pixelmon servers you visit. I suggest you think wisely about your next actions.

**Comment by imsorryelemental321** [comment]
cmon elemetal

**Comment by imsorryelemental321** [comment]
danny forgave me

**Comment by AdmiralCrunch56** [comment]
https://m.facebook.com/RHB.stuposwto/posts/1678795822389895

Weak copypasta. 

This isn't my job to say anything but if it hasn't been made clear enough, you're not getting unbanned. Flooding our github with such a plethora of racial slurs to make the confederate cringe is quite appalling to say the least. I'd recommend joining a different pixelmon server and actually try making a name for yourself. Give yourself a year and consider making an actual ban appeal here. If you ever want a pipe dream of a chance to get unbanned, that should be your plan right their.

**Comment by imsorryelemental321** [comment]
ok thank you admiral
