### ISSUE TITLE
Teleportal doctor stole my egg

### ISSUE THREAD

**Issue by Likecheckers** [ObliqueNET/Server#767]
I'm doing teleportal quest and breeding abras at the same time. I brought the doctor an abra as he asked and he took my abra egg instead of my actual abra. oof :( I was asked to post this here by staff

**Comment by PrimalCyndaquil** [comment]
This issue has now been fixed by modifying the Quest to only accept Abras that are not in 
eggs. Speak to a mod/lead to talk about getting a refund on your egg.
