### ISSUE TITLE
Lucario doesn't register as a steel type.

### ISSUE THREAD

**Issue by Bluespider20** [ObliqueNET/Server#772]
Unlike other steel types, lucario is hit by poison moves and doesn't "respond" to steel type breeding blocks. I tried testing it in Singleplayer and it worked fine so seems to be an issue with oblique.

**Comment by Vohras2** [comment]
Which pokemon were oyu using to test poison moves?

**Comment by lolsikinz** [comment]
I can confirm, lucario does not take super effecctive damage from fire punch. I believe this to be a pixelmon bug

**Comment by Bluespider20** [comment]
I used sludge wave from a gengar.

**Comment by lolsikinz** [comment]
Just tested this in a creative singleplayer world and it seems to be a server side issue since pyro ball was super effective on my test

**Comment by fatyg5** [comment]
![image](https://user-images.githubusercontent.com/8277657/92983892-37562e80-f474-11ea-8133-d5218f8ada0a.png)
Unsure what the problem is. Lucario is defined as a steel type in our stat files.

**Comment by EverSnaxolotl** [comment]
I can confirm that this is an existing bug, I saw a Scizor get poisoned by a Chansey's Toxic.

**Comment by fatyg5** [comment]
Fixed as of Wednesday.
