### ISSUE TITLE
Help with quest "The Sand Must Flow"

### ISSUE THREAD

**Issue by IHasToes1234** [ObliqueNET/Server#773]
I can't get it to register me finding the trail. I am 33% complete with the quest. I already asked multiple staff and they tried to help but none of them could figure it out. I am not sure if I am going to the wrong trail or what. Also I already put this in the discord but there was no response, and this seems to have a quicker response time. Sorry for bugging the staff so much with all my questions. Thanks for the Help!

**Comment by starwarschamp4** [comment]
When you follow the road to the dig site, the path is made of slabs behind it.

**Comment by IHasToes1234** [comment]
How far behind? And which direction is behind? Away from road 3?
Thanks for the help!

**Comment by IHasToes1234** [comment]
> When you follow the road to the dig site, the path is made of slabs behind it.

Sorry if you see this twice, as I am not sure how GitHub works. I thought it might only notify you if I reply. Which direction is behind, and how far is it?
