### ISSUE TITLE
i am very sorry why cant  i be unbanned i did nothing wrong

### ISSUE THREAD

**Issue by imsorryguys321** [ObliqueNET/Server#775]
d

**Comment by Soshisen** [comment]
The fact that you haven't learned from your past mistakes. The ones that originally got you banned is why. You cursed out, insulted, and whined to everyone on this server to the point that no one wants you here. Remember when when I said actions speak louder than words? Your actions scream that you do not deserve to be unbanned. How can you say your sorry about what you've done when you've spammed us countless times with vulgar profanities and racist terms? The only thing you're sorry about is that you were caught being a bully.
