### ISSUE TITLE
Quests that require Minecraft mobs spawning

### ISSUE THREAD

**Issue by starwarschamp4** [ObliqueNET/Server#780]
This is a reminder for Hiroku.

Adding something to the claim plugin that allows chunks to be marked as only Minecraft mob spawning areas, either for every mob or just to have spawners in the chunk. Also possibly an area when no mobs or Pokemon can spawn for certain quest spots.

**Comment by Hellblox** [comment]
Hi, do you want to play valorent with me?

**Comment by Hiroku** [comment]
Mob spawners now function in Heill. Preventing pokemon from spawning in certain quest spots can be done using the better spawner config (will require an owner to upload that though)
