### ISSUE TITLE
/t isn't working

### ISSUE THREAD

**Issue by lolsikinz** [ObliqueNET/Server#788]
As the title says, /t assumes the role of /msg instead of the usual /town
![image](https://user-images.githubusercontent.com/9399603/94952936-0acb8a80-04e7-11eb-83ea-20b5b5c4b1e6.png)

**Comment by Hiroku** [comment]
This is just a simple alias problem that'll be resolved with the next restart, keeping the ticket open so it doesn't get reported again

**Comment by Hiroku** [comment]
Turns out it isn't that, it was in the plugin itself. Next restart will fix it for real this time
