### ISSUE TITLE
Buy/Sell signs breaking

### ISSUE THREAD

**Issue by BootyHadMeLike** [ObliqueNET/Server#793]
I'm not completely sure WHEN this issue began, though it has been known for at least a week now among players. The problem is about recently placed buy/sell signs. If I place and activate any buy/sell sign, it will work fine, but roughly after a few hours, they just stop working entirely. The reasoning for this is unclear to me so far. I have tried logging, checking after periods of time, and I have not found anything to support how or when they stop working exactly. Perhaps it just stops after a certain time, I don't know. The signs will APPEAR to be working, as they will have the blue [Buy] or [Sell] indicating they are active, but left or right-clicking them will result in nothing happening. A majority of my signs are fine, as they have been there for a long time and have no issues, however, I have come across this problem with all of the shop signs that I have placed within the past week or two. As far as I know, the problem is isolated to newly placed signs. 

In my shop, there are quite a few signs that have experienced this, as I have created them recently, but the best example I could point you to is Dadofall's shop (/warp tpdadofall), where each and every sign in his shop just stopped working. They are all blue, indicating they are active, but nothing happens when you left or right-click the signs (EDIT: it appears he fixed his signs atm). I went through a few of the newer shops, and some of them also had signs that were not working.

I would record more, but my internet is extremely slow and this video alone took like 15 minutes to upload, so I tried to give a brief demonstration just to make it a bit more clear and give the general idea of what's happening here.

https://youtu.be/nol1C1ryMYY

In this video, I left and right click active signs, showing that some are working and some are not. I can verify that the ones not working, sun stone and park ball, were initially placed within the last week(ish), whereas the master ball and dawn stone signs have been there for much longer. I have also replaced the sun stone and park ball signs at least once each due to them breaking recently. They would work for a while after replacement, then just stop working again, as I have suggested. EVERY sign that I know of that has recently been placed has had this occur, so it's not really a "sometimes it happens, sometimes it doesn't" to new signs.

**Comment by BootyHadMeLike** [comment]
Update: I fixed the park ball sign about a day ago and it's still active, so maybe the problem is fixed, I'll let you know!

**Comment by BootyHadMeLike** [comment]
I woke up today and those 2 signs are no longer working again, so the issue is still happening.

**Comment by BootyHadMeLike** [comment]
Hey, I have recently discovered a key bit of information to understand what is going on here. So, the issue has persisted since I made this post, but I made a discovery within the last 2 days that I have confirmed through multiple signs in the shop, but I will demonstrate one example through a video, and I can show more ingame, if you'd like.

https://www.youtube.com/watch?v=xe_3Na_XfB0

In this video, you can see that the bottom sign is a [buy] sign for the false swipe TM, the middle sign is a [buy] sign for the energy ball TM, and the top sign is a [sell] sign for the false swipe TM again. The [buy] signs are not an issue, as they have been there for months and have not been edited. The [sell] sign on the other hand is telling. The sign says it is [sell] false swipe for $869, but when clicking it, it says energy ball tm for $1500. Granted the name on the sign doesn't matter, but the price does. I have determined that what is going on is that these signs are being rolled back to a previous state everytime they are fixed. I used to have a [sell] sign for the energy ball in that exact spot at that exact price, but I switched it out to false swipe recently. When it comes to the signs not working AT ALL, this is because there was never a sign there to begin with, so it is being rolled back to a previous state of nothing.

(btw the reason the sign is red is because I filled up the energy ball chest with blocks https://prnt.sc/v85y3j to prevent people selling the TM)

If you need more evidence of how this works, come to my shop to the block area where I have rubies, sapphires, diamonds, etc. and left click all the signs. I rearranged that whole entire wall recently before I knew of how this worked, and now everything over there is just a mess. I thought I would just have to reconnect the signs every few days, but all the signs appear fine, just how I made them, but when left-clicking, they link back to how they were before the change. (Ex. Sign says [Buy] iron ingot 16x $290, but left-clicking says Buy Emerald x16 $320, which is the sign that was previously there).

Not sure what is causing this issue, but I would guess it may be occurring during server restarts, but that is pure speculation based on my previous server experience. That's most of the information I have, if you need anything, let me know.

**Comment by Rasgnarok** [comment]
Interesting, this might be an issue with how CarrotShop is caching the current sign data. I might need to make an entirely new plugin for this, lol. Can you confirm if this works when you place it in an entirely different, never-used location?

A dirty fix would be to force an update to the cached sign data at more aggressive intervals. If this is possible, then signs across restarts should work fine (aka breaking a sign, server restarts, placing it back down with different data).

**Comment by BootyHadMeLike** [comment]
If placed in an entirely new area, the sign will just become useless after a while and not do anything anymore. It can still be reconnected with redstone without needing to break the sign, though.

**Comment by BootyHadMeLike** [comment]
Oh, I made the guess before, but we have since learned that this issue always occurs after the server restarts.

**Comment by Rasgnarok** [comment]
Closing in favour of the initial issue mentioned, duplicate https://github.com/ObliqueNET/Server/issues/878.
