### ISSUE TITLE
NPC Trainers Negating Mega Evolution and Z-Moves

### ISSUE THREAD

**Issue by Blitzmentalist** [ObliqueNET/Server#795]
This issue affects all NPC Trainers. If the player selects that their Pokemon Mega Evolves or uses a Z-Move, the button will glow in rainbow colors as normal. However, neither feature activates during the battle itself. The battle will proceed as if the button had not been pressed, and the button for both features remains in place. This effectively removes Mega Evolution and Z-Moves from use in NPC Trainer battles.

Dynamax still functions as normal, however.

**Comment by Soshisen** [comment]
Did you test this in single player?

**Comment by UnknownFlash** [comment]
Tested And Mega Evolving And Z-Moves work in single-player, this is a server issue.

**Comment by Rasgnarok** [comment]
Already known issue with Pixelmon, will be fixed in an upcoming version, https://pixelmonmod.com/tracker.php?p=2&t=15165.
