### ISSUE TITLE
Life and Destruction Quest error

### ISSUE THREAD

**Issue by kohath217** [ObliqueNET/Server#797]
Upon fighting the three pokemon to get the clues at the lake, I chose to check a random spawn's ability to see if it was HA. This was just after defeating the second battle. I used "run" to leave the battle since it wasn't HA. The game triggered this run as if I ran from a quest objective and it sent me back to highrift pokecenter. 

Is there a way for the quest to differentiate between random pokemon battle and quest boss battle?

Kohath

**Comment by Soshisen** [comment]
Unfortunately there is not a way to differ this when you are certain stages. If the quest has a "Flee" option it doesn't know what you are fleeing from.
