### ISSUE TITLE
appeal for unbanned 

### ISSUE THREAD

**Issue by NoahBert** [ObliqueNET/Server#802]
hey admin admin
I have already put in an appeal to get unbanned I'm sorry for my behaver and ill make sure that I won't be stupid if you unbanned me
my username is Noahbert_420
thanks

**Comment by starwarschamp4** [comment]
Repeated spam of our Github begging to be unbanned will only hurt your chances of being unbanned. Please wait for the lead moderator to look at your ban and determine the next course of action.
