### ISSUE TITLE
Not getting vote rewards

### ISSUE THREAD

**Issue by HomieGroge** [ObliqueNET/Server#804]
Ive voted on day 30 and 31 and all it gave me where the standard vote crate and 1000. Ive reset game and redownloaded browser so idk what to do. My Username in game is Rogan_D it wouldnt let me use that as a username on here tho

**Comment by Rasgnarok** [comment]
Closing as milestones are completely broken. Apologies for the lack of refund at the present time, but I will need to change plugins and reset everyone's milestones. For now, I will be closing all tickets to be fair to everyone else that lost their milestone rewards between Oct 2020 to Jan 2021.
