### ISSUE TITLE
Opt in Town Tags

### ISSUE THREAD

**Issue by BlitzAsogi** [ObliqueNET/Server#808]
Request for town tags to be shown as a chosen abbreviated form via a towny command.
![image](https://user-images.githubusercontent.com/24644181/95943101-7da60100-0e17-11eb-98c9-df4a50b04013.png)

**Comment by Rasgnarok** [comment]
Since town chat tags are now under a hover, this is likely not needed. Clutters chat less (sorry rainbow-chat lovers!) Closing.
