### ISSUE TITLE
Daily Votes

### ISSUE THREAD

**Issue by Kreestian02** [ObliqueNET/Server#809]
I reached the 30 votes milestone but the day after it didn't reset back to one.
![Cattura](https://user-images.githubusercontent.com/67237522/95977620-5ea86e80-0e19-11eb-9c69-473e540f8a2d.PNG)

**Comment by Rasgnarok** [comment]
It's extremely late for this, but I might be able to set you back down to 1 if you give me your username. Reply as needed, unless this is no longer an issue.

**Comment by Kreestian02** [comment]
Hey Ras, it's alright. My ign is Kreestian02.. the problem wasn't solved so it's appreciated

**Comment by Rasgnarok** [comment]
Closing as milestones are completely broken. Apologies for the lack of refund at the present time, but I will need to change plugins and reset everyone's milestones. For now, I will be closing all tickets to be fair to everyone else that lost their milestone rewards between Oct 2020 to Jan 2021.
