### ISSUE TITLE
7 day vote reward

### ISSUE THREAD

**Issue by Gwizz111** [ObliqueNET/Server#810]
Hi,

Today I voted for the 7th time, and didn't recieve my reward for doing so. My IGN is Gwizz11.
![pixelmon](https://user-images.githubusercontent.com/72882473/96020747-c9c06800-0e4e-11eb-982a-aedbd8f61fe2.PNG)

**Comment by Rasgnarok** [comment]
It's extremely late for this, but I might be able to set you back down to 1, thereby triggering your reward stage as well. Reply as needed, unless this is no longer an issue.
