### ISSUE TITLE
Voting Rewards not received

### ISSUE THREAD

**Issue by RudolfShmitler** [ObliqueNET/Server#811]
I have recently voted for 14 days, however I have not received any milestone rewards.

**Comment by Rasgnarok** [comment]
It's extremely late for this, but I might be able to set you back down to the reward stage if you give me your username. Reply as needed, unless this is no longer an issue.

**Comment by RudolfShmitler** [comment]
My IGN is RudolfShmitler, discord is Sunday15th#5744.

**Comment by Rasgnarok** [comment]
Closing as milestones are completely broken. Apologies for the lack of refund at the present time, but I will need to change plugins and reset everyone's milestones. For now, I will be closing all tickets to be fair to everyone else that lost their milestone rewards between Oct 2020 to Jan 2021.
