### ISSUE TITLE
All badges in badgecase gone

### ISSUE THREAD

**Issue by RapidFlamingos** [ObliqueNET/Server#812]
So i obtained an event move voucher from a crate... I went to put this in my badge case and it wouldn't work.  I check my case and everything is gone. I had all of the gym badges, around 50 mind badges, 4 event move vouchers, and 2 portal vouchers. My IGN is RapidFlames.

**Comment by fatyg5** [comment]
Sorry for the late reply! Is this still an issue? I left a note in your inventory if you see that, just DM me on Discord!

**Comment by lolsikinz** [comment]
This actually happened to me the other day and luckily nothing of (great) value was lost but it is still annoying that it happened. I lost a lot of badges from the vanha gyms but nothing else, I was also unregistered so there might be something in that

**Comment by Katadreme** [comment]
Refunded
