### ISSUE TITLE
'A Vigilante's Tale' Stage 7 not progressing

### ISSUE THREAD

**Issue by RudolfShmitler** [ObliqueNET/Server#813]
'A Vigilante's Tale' stage 7 - 'Return to Xuman's Hideout' would not trigger when tested.

**Comment by Rasgnarok** [comment]
If this is related to https://github.com/ObliqueNET/Server/issues/847 , please confirm and close this ticket, leaving only https://github.com/ObliqueNET/Server/issues/847 open. Make sure to test separately, could be just a mistype in 'A Vigilante's Tale'.

**Comment by Lieren-HuntGhosts** [comment]
"A Vigilante's Tale" doesn't make you return to Xuman's Hideout. Either you're talking about step 17 of "Vengeance at its Finest", or "For the Greater Good" 's step 13. Both work perfectly.
