### ISSUE TITLE
Voting Milestone Issues

### ISSUE THREAD

**Issue by BnannerMan** [ObliqueNET/Server#814]
I've seen this issue going around a lot, but I also didn't get my vote crates upon hitting my 7 day milestone.

**Comment by Rasgnarok** [comment]
Closing as milestones are completely broken. Apologies for the lack of refund at the present time, but I will need to change plugins and reset everyone's milestones. For now, I will be closing all tickets to be fair to everyone else that lost their milestone rewards between Oct 2020 to Jan 2021.
