### ISSUE TITLE
Ode to Destruction Bugged

### ISSUE THREAD

**Issue by OrangeSodaPop** [ObliqueNET/Server#815]
Whenever you complete the "ode to destruction" quest, it doesn't fully complete and leaves the progress uncompleted. what also happens is that if you happen to fail another quest, it sets you back to where you can get another solgaleo.

**Comment by PrimalCyndaquil** [comment]
This should now be fixed, turned out I had mispelled the name of the quest when uploading which resulted in this duplicated effect.
