### ISSUE TITLE
Apex Pixelmon Modpack not working on Technic Launcher

### ISSUE THREAD

**Issue by dadijo2002** [ObliqueNET/Server#816]
When pixelmon mod was updated to 8.1.2, the modpack updated and deleted the pixelmon mod when I launched it. I tried to restart the update but since then it has been impossibly slow and seems to restart or start decreasing in progress after about 15% installation.

**Comment by Soshisen** [comment]
We are aware and are looking into the problem. For now you can download the newest Pixelmon file here https://reforged.gg/ and replace the file in the mod pack. If you need further instructions on this please ask in #support after downloading the file. We can talk you through it.

**Comment by fatyg5** [comment]
Should be fixed at the time of posting. Please reopen this ticket if there are still issues!
