### ISSUE TITLE
Ban Appeal Request

### ISSUE THREAD

**Issue by freddypwner** [ObliqueNET/Server#818]
I got rightfully banned a few months ago for X-ray. I want to be unbanned because this was my childhood server and probably my objective favorite Minecraft server. I won't X-ray again. I don't really have any proof for that, is there some way I can prove it? Most of my money was gained through X-raying fossils, and so was my leaf armor. My water armor I gained legit through using my Swampert. If mods can take away most of my money down to like 6K because I sold a Mudkip for about that much and my leaf stone armor, then that's most of what I had X-ray'd for. Also I insulted Bluespider20 and called him absolute trash at the game after I beat the ground gym with basically 2 mons, and I regret saying that too. My Minecraft username is Freddypwner and my Discord is @SoYeah,ImAGamer# I forget the tag. This was really badly written, so sorry for that too.

**Comment by Katadreme** [comment]
You are not currently banned on Oblique. I'm not sure why you believed so. You were only tempbanned for creating and using a afk fishing machine.
