### ISSUE TITLE
Double Ultra Beast Spawning

### ISSUE THREAD

**Issue by UnknownFlash** [ObliqueNET/Server#820]
When Hunting Ultra Beasts I found that when one spawns, another spawns very near it around 20 seconds after, I have tested this 3 times in a row and each time 2 of them spawned, first time it was 2 Kartana, Then 2 Pheromosa, and another 2 Pheromosa and all this happened within 3-4 days.

**Comment by Rasgnarok** [comment]
As much as this is technically not an unwanted bug (yay for linking UB spawns!), you might want to report this to the Pixelmon tracker. We don't use any custom methods to spawning Ultra Beasts, and so this seems to be an unwanted effect directly from the native Pixelmon spawner. https://pixelmonmod.com/tracker.php?p=2
