### ISSUE TITLE
Quest Error : No longer have access to activating quests

### ISSUE THREAD

**Issue by Bakakov** [ObliqueNET/Server#821]
Currently, I do not have access to starting a quest. I've tried multiple "things" that could possibly help with my issue, but nothing worked. Overall, consider all of my quests locked.. 

PS: I have the requirements for the quests I've tried to begin, etc.

**Comment by Soshisen** [comment]
Can you please post a picture of your quest book here

**Comment by menno516** [comment]
its flipside arcade, 88%, its blank page. it needs to be Talk to ras at /warp nyr
![image](https://user-images.githubusercontent.com/63118334/96661027-70bf6b00-134b-11eb-9de2-8babcb58f52e.png)

![image](https://user-images.githubusercontent.com/63118334/96660935-35bd3780-134b-11eb-8455-dacd8e43396c.png)

**Comment by Rasgnarok** [comment]
@Bakakov It's extremely late for a reply, but I know of a manual way to do this. Can I please have your username?

**Comment by Bakakov** [comment]
This issue was resolved, I believe. My ign is theloler007
