### ISSUE TITLE
(っ◔◡◔)っ ♥ 𝐵𝒶𝓃 𝒜𝓅𝓅𝑒𝒶𝓁♥

### ISSUE THREAD

**Issue by Hellblox** [ObliqueNET/Server#822]
A few days ago, maybe a few weeks ago now. I have been banned on the Oblique Pixelmon Mod Server for not listening to the moderation team or listening to KataScREEm, I apologize. I have written a draft of my appeal and my mother to peer review it, but I ultimately scrapped it. I have been contemplating about I have done and said, and I sincerely regret what I have done. I do not care about the iron or coal or my enchanted diamond pickaxe anymore – I just want to see my cute pixelmons, I just want to play.

**Comment by Hellblox** [comment]
I have also been banned on the discord.

**Comment by Hellblox** [comment]
Leave a comment

**Comment by Katadreme** [comment]
You've already appealed once and the same answer still stands.  You've been declined.
