### ISSUE TITLE
A Whale of a Tale soft lock

### ISSUE THREAD

**Issue by menno516** [ObliqueNET/Server#823]
On stage 5 of the quest you need to have the fishing rod you get from the fisherman in kuanti.

The quest will not let you progress if you use split the 2 fishing rods from 1 spot to  2 spots.

2 on each other in 1 inventory slot = works
1 in 2 different inventory slots = doesnt works

no picture since it might spoil the quests starting location

**Comment by Soshisen** [comment]
You also need 10 Dive Balls, did you, or the player, have those?

**Comment by menno516** [comment]
yes

**Comment by Soshisen** [comment]
So if the rods are not stacked the quest can't move on? So what we do is edit a warning into the clue. That's all we can do since it's a fundamental coding problem here. Gonna tag Hiro in on this to see if he can do anything about it

**Comment by Hiroku** [comment]
Probably some bad logic in that condition type, I'll need to take a look at it

**Comment by starwarschamp4** [comment]
I can just remove the condition to have both rods, since they only need to give one to the sailor.
