### ISSUE TITLE
isle of spirits quest incompletable

### ISSUE THREAD

**Issue by killerdom733** [ObliqueNET/Server#824]
if you do the quest at the end it gives the popup on your screen that fades in and fades out and it says quest complete but then i check my quest book and its still there can someone help

**Comment by the4bestgame** [comment]
I also have the issues. Possibly related is I fought the secret boss first, and the teapot I got doesn't have the special texture

**Comment by Rasgnarok** [comment]
Should be fixed as of latest changes on the 29th of October for this quest, but please re-open a ticket if your personal quest progression is stuck. Make sure to include your username and a screenshot of your questbook.
