### ISSUE TITLE
Tm Tr moves

### ISSUE THREAD

**Issue by iiprayfordayz** [ObliqueNET/Server#825]
I have tried to teach my Slowbro Psychic and it says it cant learn it. Ive used tr and tm and neither of them will work. Ive spent money on moves and none of them work. BurritoHuskey has spent some of his money trying to help.

**Comment by fatyg5** [comment]
![image](https://user-images.githubusercontent.com/8277657/97822385-b9e4b880-1c83-11eb-8891-0d7d3ae8427f.png)

I'm unsure what your issue is. TR11 worked fine for me.
