### ISSUE TITLE
[Landlord] Merchant for claim blocks doesn't complete transaction

### ISSUE THREAD

**Issue by Rasgnarok** [ObliqueNET/Server#827]
All interacts work fine, but it does not finalize the transaction after clicking 'yes'.

**Comment by fatyg5** [comment]
This isn't broken. You must have money in your town balance to buy from the merchant, not in your player balance. 

Only suggestion is to give an error command if the player can not afford it, something along the lines of "You do not have enough money in your town balance! Use /town deposit (amount) to deposit money."
![image](https://user-images.githubusercontent.com/8277657/97064096-b0679c00-1571-11eb-81b3-8ad256702cb5.png)

**Comment by Hiroku** [comment]
Actually it should be showing a dialog for both if you don't have money and if you buy it successfully. If it isn't then it is a bug

**Comment by Valjean42** [comment]
Fixed after next restart

**Comment by fatyg5** [comment]
Gonna assume fixed. Reopen if necessary.
