### ISSUE TITLE
Incorrect ban

### ISSUE THREAD

**Issue by Baugrems** [ObliqueNET/Server#829]
WhaleHell0There was banned for using Xray. Nothing of the sort is installed on the pc, she is a total newbie to minecraft and has no idea what it meant until I told her. She is my wife IRL and did nothing wrong. I even installed pixelmon on the pc for her so she could play with me. This is extremely infuriating and it feels like we've been stonewalled as "Guilty unless you prove innocent". No idea what else to say? I (scopenhagenmines) have been playing a few days with zero issues. If anyone was going to be using something it would be me not my wife who is a newbie. I put a lot of work in the server and hope this can be resolved as I enjoy it but this seems like a weird mistake.

**Comment by fatyg5** [comment]
A helper of ours received a message from a Discord username with the same as your in game name. I'm unsure why someone would go to impersonate you, but it seems someone has.

You have been unbanned.
