### ISSUE TITLE
ban appeal for killerdom733

### ISSUE THREAD

**Issue by killerdom733** [ObliqueNET/Server#830]
i have stolen been a dickhead to staff and i have greifed i realize looking back on my actions that they were completely in the wrong i have been given more chances that any should have been given and i thank the staff very much i killerdom733 will do my best to fix all my wronging's that i have done and i will help everyone who asks be more generous and be much kinder to people i killerdom733 will fix everything i have done and i will apologize and repay all the people i have wronged i am sorry server people i did a bad and now i am paying the price

**Comment by fatyg5** [comment]
You have broken our rules multiple times. You were warned about breaking rules multiple times. You only are being apologetic after the fact, not for any of your past issues. For this reason, plus the numerous notes your account has received for breaking our server rules, you will not be unbanned.
