### ISSUE TITLE
Ban appel for Paolopizza

### ISSUE THREAD

**Issue by paolopizza** [ObliqueNET/Server#832]
I know I did wrong stuff looking back but I will change but all I need is for the sever to give me another chance.

**Comment by fatyg5** [comment]
Looking at your notes, I see you have 3 of them. The first one involves you stealing from your town members and selling the items, which was already your final warning. You also made an inappropriate image out of player heads. Then, you were caught stealing again. All of this, coupled by the fact that you don't seem apologetic at all in this appeal means you will not be unbanned.

**Comment by paolopizza** [comment]
Can I please have a last chance I wont do anything that would make the staff mad or annoyed but can I have a second chance  Sent from Mail for Windows 10 From: fatyg5Sent: Tuesday, November 3, 2020 1:29 PMTo: ObliqueNET/ServerCc: paolopizza; AuthorSubject: Re: [ObliqueNET/Server] Ban appel for Paolopizza (#832) Looking at your notes, I see you have 3 of them. The first one involves you stealing from your town members and selling the items, which was already your final warning. You also made an inappropriate image out of player heads. Then, you were caught stealing again. All of this, coupled by the fact that you don't seem apologetic at all in this appeal means you will not be unbanned.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
