### ISSUE TITLE
Poliwrath not able to learn tm moves

### ISSUE THREAD

**Issue by NyutaA** [ObliqueNET/Server#833]
I worked on a poliwrath for like 2 days to get a 93 % one and then I found out it cant learn tm or tr moves . I have checked with the staff bluespider20 and he confirmed that it cant learn tm or tr moves he said it could be a glitch but he also thinks poliwrath may not learn tm moves. Bluespider also checked /wiki poliwrath tmmoves and it said it cant learn tm moves but if you search it up in google and search up poliwrath tm moves it says it can learn waterfall and earthquake. Poliwrath also doesn't learn a physical water move by level so I'm hoping you can fix this.
![2020-10-25_22 09 59](https://user-images.githubusercontent.com/73457608/97136004-310fcf00-170f-11eb-9027-198589f195f2.png)
![2020-10-25_22 11 42](https://user-images.githubusercontent.com/73457608/97136016-340abf80-170f-11eb-9bad-0f7b06a4feb3.png)
![2020-10-25_22 11 59](https://user-images.githubusercontent.com/73457608/97136018-3705b000-170f-11eb-8821-9b9d7a917d16.png)
(Look in chat)

**Comment by fatyg5** [comment]
This is a Pixelmon issue which they will address, not a server issue.
