### ISSUE TITLE
iv vouchers no worky

### ISSUE THREAD

**Issue by CuteCanary** [ObliqueNET/Server#836]
hai so I think iv vouchers are broke ): unless they work differently than I thought xd I always assumed they increased or decreased the ivs, as well as the actual stats (in summary) ? if that's how they're suppose to work, then they're not working properly rn. 
a lead confirmed that they are suppose to work like this ^ 
I used iv vouchers on my ash greninja the other night and it increased the ivs, but not the actual stats in summary. I thought the issue might have been that it was a battle bond greninja, so I tested it on my torterra as well, but the same thing happened. Both the greninja and torterra were level 100, so that's not the issue here. 
I waited a few days to post this bc I figured it might just take a while for the stats to update, but they never did. The server has also been restarted since I vouchered it and that didn't fix it either xd
anyway, here's some screenshots so u can see what I'm saying incase I didn't explain it well xd
![greninja ivs](https://user-images.githubusercontent.com/48975028/97641600-a6361980-1a19-11eb-9a45-96010a959a75.png)
![greninja stats](https://user-images.githubusercontent.com/48975028/97641610-ab936400-1a19-11eb-94d5-6ef2236b4c54.png)
if I'm correct, when I set the the defense ivs to 31, the stat should've been raised to 170, and that's if it didn't have any evs trained in defense. I think it had like 6 defense evs before I vouchered it ? the rest are in sp atk and speed
ok das all xd if u have any questions lemme know

**Comment by fatyg5** [comment]
After doing some testing this seems to be a Pixelmon issue. Will report to them!

**Comment by Rasgnarok** [comment]
Forwarded to Pixelmon, bug within internal stat calculation. Will be fixed as of next Reforged update. Closing, open a new ticket if the issue persists after the next version.
