### ISSUE TITLE
[Quest] The Mailman 

### ISSUE THREAD

**Issue by DiddyTheKid** [ObliqueNET/Server#837]
I watched a player who was having an issue with The Mailman quest, but they couldn't hit any of the skeletons that were spawning. Unsure of what the issue was because I could hit them fine. I asked them to relog, and that didn't work either. Any ideas?

**Comment by purifiedrabbits** [comment]
I am not able to hit them either, but I am able to kill them with bows. There is also another ticket for this already open labeled "Immortal Skeletons"

**Comment by starwarschamp4** [comment]
I was able to kill them with a sword the same way a player would with ignore claims off and gm 0. If this still doesn't work for you bows can kill them.

**Comment by starwarschamp4** [comment]
Removed the skeleton killing objective as you still can't kill skeletons in admin claims for some reason. Also removed the spawners for them for this same issue.
