### ISSUE TITLE
Ode to Destruction Looping

### ISSUE THREAD

**Issue by Blitzmentalist** [ObliqueNET/Server#838]
This issue happened with the quest "Ode to Destruction" to the user "suicidaltrash_". After catching Solgaleo and returning to the tomb in Ner-Gal to finish the quest, the quest apparently ended as normal before looping back to the point of entering the final point and combating Solgaleo. The player was able to catch Solgaleo and claim the rewards a second time, at which point they brought it to my attention. 

I asked them to finish the quest one last time so I could track their progress with /questdebug and attempt to see what was causing the loop. After catching Solgaleo a third time and gaining the rewards, the quest ended permanently and did not reappear in the player's quest book. 

All excess rewards were turned in and destroyed, and we'll keep an eye out in case it reappears in suicidaltrash_'s quest book. I'm making a note here so we know to look into the code and figure out why this happened.

**Comment by Rasgnarok** [comment]
Closing the issue as it is technically solved. Please open a new one and link this old one if it happens again.
