### ISSUE TITLE
Remember to exercise bug

### ISSUE THREAD

**Issue by UnknownFlash** [ObliqueNET/Server#839]
Starting the quest through /quests puts you in the floor under the house in Ione, and the next step involves going to old Ione making a lot of players confused (including myself). quest can still be completed though. might wanna fill in he hole in the floor.

**Comment by Soshisen** [comment]
This is the teleporting system picking a nearby spot that is safe to teleport to. The4bestgame filled in the area below the house so this shouldn't happen again.
