### ISSUE TITLE
Gym Badge Disappeared From Case

### ISSUE THREAD

**Issue by freddypwner** [ObliqueNET/Server#840]
I was looking at the badge in my gym case and double clicked on it. It went poof. It was a ground gym badge. IGN: freddypwner Discord: Soyeah,ImAGamer#3115

**Comment by fatyg5** [comment]
It didn't enter your inventory? I believe double clicking removes the badge from the case

**Comment by freddypwner** [comment]
> It didn't enter your inventory? I believe double clicking removes the badge from the case

It did not enter my inventory.

**Comment by Rasgnarok** [comment]
Refunded, known issue with Pixelmon. Please report to their tracker (https://pixelmonmod.com/tracker.php?p=2) if you find a way to reproduce it.
