### ISSUE TITLE
Appeal foe a ban 

### ISSUE THREAD

**Issue by uppys** [ObliqueNET/Server#841]
Minecraft Username : uppys
Reason For Ban: Slurs, offensive terms

I typed out the words, "What's up my *Nathans." (remove "athans" and place down the funny words)
Turns out I'm not funny! I would like to play the actual game if I'm given a second chance! I'm an avid pokemon enjoyer. I LOVE PIKACHU!

**Comment by Katadreme** [comment]
I will unban you to give you a second chance, but will not tolerate any semblance of the behaviour that got banned you in the first place. If anything similar is seen, the ban will be quickly be reinstated.

**Comment by uppys** [comment]
Mashallah brother! Appreciate it :O
