### ISSUE TITLE
ban appeal

### ISSUE THREAD

**Issue by eggrollman** [ObliqueNET/Server#844]
I wrote the n word in the all chat instead of msg message to a man who called me with it first, so I thought we would be even. I was in a big anger and I really want to apologise for that, and I swear I will improve myself. I am really sorry. nick egg_roll_man

**Comment by eggrollman** [comment]
soo, what's the result?

**Comment by Katadreme** [comment]
Sorry for the delay. I will say you get a second chance, but know we won't tolerate anymore of the same behaviour and the ban will be placed again if it does happen again.
