### ISSUE TITLE
has_completed condition in Questbuilder

### ISSUE THREAD

**Issue by PrimalCyndaquil** [ObliqueNET/Server#847]
The has_completed condition currently does not detect the completion of individual objectives that are part of a stage that has been marked complete. This does work for checking objectives of the same stage that is not complete, as it currently works for "Life and Destruction".

As an example, I made a short test quest to see how this worked. It is as follows:

Stage 0- Chat Npc w/ a Show Options trigger
Stage 1- Choose Option (Yes) & Choose Option (No)
Stage 2- 3 Chat Npc objectives w/ has_completed conditions, "Yes", "No", and "Both". For yes and no, the opposite option is marked flipped.

The quest returns "both", indicating that both Yes and No were marked as complete, even when I had only picked yes. This is a rather niche issue, but it would cut the possible need for small quests out of various scenarios. It'd be especially useful for more "Open World" stuff.

**Comment by Vohras2** [comment]
Closing to merge into quest master thread.
