### ISSUE TITLE
Mobs won't spawn in Heill

### ISSUE THREAD

**Issue by freddypwner** [ObliqueNET/Server#852]
Back when I played on the server a few months ago, I accidentally accepted the quest Resurgence. For it, you have to kill about 15 Zombies and Skeletons. I went to /warp Heill, used /rtp, then checked the light level (it was 0.) I ran back and forth on an island on multiple occasions, and on only the first ocassion (months ago) did mobs actually spawn. The time I've spent waiting for mobs only for nothing to spawn except for 2 pigs has probably totalled over an hour at this point. Can you either make mobs spawn again or remove the quest from my quests? IGN is freddypwner Discord is @SoYeah,ImAGamer#3115 .

**Comment by UnknownFlash** [comment]
There is a skele spawner to my understanding and most likely a Zombie spawner.

**Comment by Rasgnarok** [comment]
Closing in favour of a more completed ticket, will be looked at all together. https://github.com/ObliqueNET/Server/issues/526
