### ISSUE TITLE
Ban Appeal  

### ISSUE THREAD

**Issue by gameing0448** [ObliqueNET/Server#855]
I don't know if I am banned on the actual server but I am banned on the discord server

Discord name
gameing#0448
Mc IGN
notgamershot

I Apologize for advertising and would like to be unbanned.

**Comment by Katadreme** [comment]
You have been unbanned on the discord, but anymore further advertising or anything similar will quickly have this ban reinstated

**Comment by gameing0448** [comment]
thank you
