### ISSUE TITLE
Quest with invisible stage, can't start new quests when only 2 are active because of it

### ISSUE THREAD

**Issue by RudolfShmitler** [ObliqueNET/Server#858]
^

**Comment by Soshisen** [comment]
What's your in game name?

**Comment by RudolfShmitler** [comment]
RudolfShmitler

**Comment by Soshisen** [comment]
I received your quest file, I will be looking it over to see if there are any quests that say complete but are not on the correct stage. If you have anymore info on which quests this could be please state them below. This can take some time as the file is large and I have to go through it manually

**Comment by Rasgnarok** [comment]
Closing this ticket as it is a few months old, please make a new one if the issue persists.
