### ISSUE TITLE
Mai does not respond to DMs

### ISSUE THREAD

**Issue by Soshisen** [ObliqueNET/Server#860]
Before the great Mia implosion we could DM Mia with commands and she would respond. This is no longer the case.

**Comment by menno516** [comment]
this issue is still going on.
!profile and things like "mia who is online" don't work in dms.
(Replied on this because Ras requested it)

![image](https://user-images.githubusercontent.com/63118334/102793166-ccd55880-43a9-11eb-8698-21f12d0082c6.png)

**Comment by Rasgnarok** [comment]
Duplicate, closing this ticket in favour of the main one.
