### ISSUE TITLE
Mia got alzheimers

### ISSUE THREAD

**Issue by RudolfShmitler** [ObliqueNET/Server#861]
Mia is replying to chat commands like 'Mia oblique wiki' several times over across a short duration of time. This is also happening in #market, where listings appear several times over. 
![Screenshot_20201119_060304_com discord](https://user-images.githubusercontent.com/55514946/99576345-f78c6400-2a2d-11eb-82d8-3e1b3f5618f8.jpg)

**Comment by Hiroku** [comment]
It's the beta server's mia instance being online, she's since been turned off
