### ISSUE TITLE
Ban Appeal (HUGE MISTAKE)

### ISSUE THREAD

**Issue by KachowGod** [ObliqueNET/Server#863]
IGN: Kachowgod
discord: GodTheSequel#8639

okay so i was testing out a macro on my mac on a different server a couple days ago. it had worked fine with no issues. i wanted to buy a bunch of diamond crates and i realized that i could use the macro from those couple days ago and just do the diamond crate key command. i thought i had deleted the old preset but aparently it was bugged or maybe i just didnt do it right. it did end up doing the buy key command, but also spamming those slurs. i don’t use those words ever and overall i really regret this happening as it was my own fault for not looking deep enough into it. i really hope this clears things up and i can play again.

**Comment by Katadreme** [comment]
Although you are genuine about your apology, I'm going to be declining your ban appeal as you contradict yourself when you say 'i dont use those words ever' and yet you had it on a macro to use for malicious intent on a separate server, which even still speaks to your capabilities here. I can't in good faith, unban you and have it seem like that having the slur on a macro would it seem acceptable / tolerable in anyway.
