### ISSUE TITLE
Ban Appeal 

### ISSUE THREAD

**Issue by OpTime21** [ObliqueNET/Server#864]
I was banned on the server for spamming but I did not realize I was spamming, I was trying to send a tp request to my friend. I did it multiple times because I was worried he was not getting the notification, then one second later I saw I was banned. Hopefuly you can forgive my mistake and unban me. :)

**Comment by ElementalMP** [comment]
You've been unbanned, as it is evident that this was a mistake, and not malicious intent. Please be mindful of your contributions to public chat in the future.
