### ISSUE TITLE
Treecko wont evolve

### ISSUE THREAD

**Issue by moistmanbuns** [ObliqueNET/Server#865]
No matter all the fixes I try, suicide then candy it just won't evolve but keeps leveling up.
![Screenshot 2020-11-24 085756](https://user-images.githubusercontent.com/74971858/100103658-2db55380-2e33-11eb-836a-c93321fdf719.png)

**Comment by Hiroku** [comment]
Where did you get the treecko?

**Comment by PJLesure** [comment]
Hi moist, the next time you are online if you still have this issue feel free to contact anyone that is a moderator or higher, they will be able to force evolve it.

**Comment by Rasgnarok** [comment]
Closing as it's necessary for the player to come online. Please tag us in #support, on https://discord.gg/B3XcYcR  for quick support issues, like this one!
