### ISSUE TITLE
Paean of Affliction bug

### ISSUE THREAD

**Issue by OrangeSodaPop** [ObliqueNET/Server#866]
When losing to lunala, it keeps you on stage 9 instead of setting you back to stage 8, also it doesn't set you back If you leave the lunala quest area.

**Comment by Rasgnarok** [comment]
If this is part of a bigger pattern of tickets with all 'abnormal end' issues, please test and confirm, and link all tickets together. Close all doubled tickets. Keep one master ticket up, and ping me so I can assign it to a dev.

**Comment by Soshisen** [comment]
Did you lose as in you ran out of pokemon? Or did you remove yourself from the battle?

**Comment by Soshisen** [comment]
This has been tested and seems to be working fine. Please make a new ticket if this occurses again
