### ISSUE TITLE
Unban

### ISSUE THREAD

**Issue by CoachTrump** [ObliqueNET/Server#867]
Hello, I used to play on this server for a while with a lot of my friends and got banned because they gave me their money before they quit and got banned for using alts to funnel money into one acc, i would like to get unbanned so i could comeback and play with some new friends since oblique is like the only good non ptw server with amazing quests and stuff. ty very much

**Comment by Katadreme** [comment]
What is your ign?

**Comment by CoachTrump** [comment]
> What is your ign?

CoachTrump

**Comment by Katadreme** [comment]
I can't seem to find any record of your ban. I will unban you, however any further server rule-breaking will quickly have this ban reinstated.
