### ISSUE TITLE
Battle Blacephalon Quest Issue

### ISSUE THREAD

**Issue by SyCoAir** [ObliqueNET/Server#868]
Epicman's Game crashed and the quest did not let him fight blacephalon. He was on stage 1. Had to set him back to 0 to restart the quest.

**Comment by PrimalCyndaquil** [comment]
This quest has since been removed as the event regarding it has concluded. However, the quest _did_ have a log-off objective and a battle-end-abnromal objective, so I may try and test to see how those objectives interact with crashes.
