### ISSUE TITLE
Breath of a Dragon Invisible Quest Issue

### ISSUE THREAD

**Issue by Blitzmentalist** [ObliqueNET/Server#869]
The quest "Breath of a Dragon" has an invisible Quest issue, remaining incomplete even after being done and taking up a slot in the person's quest book.

**Comment by Soshisen** [comment]
Stage 9 is a copy of stage 8, this may be causing the problem. Will assign to Primal once he accepts the invite to the GitHub

**Comment by PrimalCyndaquil** [comment]
Should now be fixed! Stage 5 was invisible and stage 8 and 9 had the same lose-to-trainer UUIDs.
