### ISSUE TITLE
Weird Endbattle bug

### ISSUE THREAD

**Issue by Soshisen** [ObliqueNET/Server#871]
In the quest Fallen but Not Forgotten, the player was in the middle of catching Rayquaza. However the waiting bug happened. When they ended the battle they did not catch Rayquaza, however the quest believed they had. Which moved them on to ending the quest.

**Comment by Rasgnarok** [comment]
If this is part of a bigger pattern of tickets with all 'abnormal end' issues, please test and confirm, and link all tickets together. Close all doubled tickets. Keep one master ticket up, and ping me so I can assign it to a dev.

**Comment by Rasgnarok** [comment]
Closing in favour of master ticket. Quest battle loop is not working as expected, warp trigger will be fixed.
