### ISSUE TITLE
Quest: A soul for A Soul (soft lock) 

### ISSUE THREAD

**Issue by menno516** [ObliqueNET/Server#872]
When you leave the question screen on stage 37 in this quest twice in a row it wont show up anymore and just look like the picture below.

So after leaving the screen for a second time the quest wont work anymore. 
However, I do not know how this will work when the server restarts/crashes. 

![image](https://user-images.githubusercontent.com/63118334/100285960-29dc1b00-2f72-11eb-91bb-8b2181c23f0b.png)

**Comment by PrimalCyndaquil** [comment]
This was fixed on the 30th of November. Sorry for not closing the issue back then.
