### ISSUE TITLE
Avenging Flames Abnormal Battle Issue

### ISSUE THREAD

**Issue by Blitzmentalist** [ObliqueNET/Server#873]
This is a repeat of a prior noted issue. 

In the quest Avenging Flames, the player "ghvsts" crashed due to trying to wait out the waiting glitch, and battle_end_abnormal did not account for them crashing, resulting in the quest not entering the intended reset loop. This appears to be a repeat of the issue in which a player was kicked from the server due to restart in the middle of fighting Moltres, resulting in a similar issue.

It appears that crashing and getting kicked will consistently cancel out a battle without triggering battle_end_abnormal.

**Comment by Rasgnarok** [comment]
If this is part of a bigger pattern of tickets with all 'abnormal end' issues, please test and confirm, and link all tickets together. Close all doubled tickets. Keep one master ticket up, and ping me so I can assign it to a dev.

**Comment by Rasgnarok** [comment]
Closing in favour of master ticket. Quest battle loop is not working as expected, warp trigger will be fixed.
