### ISSUE TITLE
Claimed Land Not Reverting After 2 Months

### ISSUE THREAD

**Issue by Aeliouz** [ObliqueNET/Server#876]
Hi, I am currently having issues with a town located next to mine. It is my understanding that claims are supposed to revert to unclaimed land after 2 months of inactivity. However, the town next to mine named "Gekkemannen" has 2 members, one of which hasn't been on in 74 days, and the other has not been on for 127 days. With that being said the claim is still active and it is now getting in the way of me expanding my town. I would like to know if someone could either forcibly delete or unclaim the town area.

**Comment by Rasgnarok** [comment]
Duplicate, will have to be tested. Closing in favour of more completed, main ticket.
