### ISSUE TITLE
Ban Appeal admin

### ISSUE THREAD

**Issue by TheCrazyGame2** [ObliqueNET/Server#877]
Hello guys i'm TheCrazyGame2 please unban me i'm sorry for the afk machine, I will not do it again. I'm lost without minecraft.

**Comment by Katadreme** [comment]
Gotta put some effort in your ban appeal. And this is a Pixelmon server, not Minecraft so you can still play Minecraft to your hearts content. In-case it wasn't obvious already, Im declining your ban appeal.
