### ISSUE TITLE
/outpost list is broken

### ISSUE THREAD

**Issue by thunder1231223** [ObliqueNET/Server#880]
outpost list has usually been broken in the last few days, it works sometimes but most of the time it gives an error
![Screenshot_118](https://user-images.githubusercontent.com/50634888/100498882-cc68e980-317e-11eb-8717-c8a1c49471bf.png)

**Comment by Hiroku** [comment]
Note to myself in the future: Best guess is outposts in other worlds that are being unloaded by Sponge, might be linked back to our world unloading issue

**Comment by Rasgnarok** [comment]
Duplicate, closing in favour of the main ticket. Workaround is warping to the world first, then executing the outpost command.
