### ISSUE TITLE
Egg move vouchers not working on older mons with gen 8 movesets

### ISSUE THREAD

**Issue by lexjo** [ObliqueNET/Server#881]
Egg move vouchers do not give any options to learn moves when used on an older pokemon with a gen 8 moveset, 
![image](https://user-images.githubusercontent.com/17412315/100514772-55782480-316f-11eb-87e3-0583189fbbdd.png)
^Ribombee
![image](https://user-images.githubusercontent.com/17412315/100514790-70e32f80-316f-11eb-878e-dbf8587ccbd4.png)
^Gallade
![image](https://user-images.githubusercontent.com/17412315/100514824-aa1b9f80-316f-11eb-89fe-50e718a5b112.png)
^Applin
![image](https://user-images.githubusercontent.com/17412315/100514838-cf101280-316f-11eb-9bcd-0dce33d12bfb.png)
^Girafarig

**Comment by Rasgnarok** [comment]
This is actually part of the move issues introduced in the latest Reforged updates. It will be fixed for next update, but for now, egg move issues (that aren't from the plugin in actuality, but the stat files in Reforged) should be reported to the Pixelmon tracker, https://pixelmonmod.com/tracker.php?p=2.
