### ISSUE TITLE
Rotom Farming Glitch

### ISSUE THREAD

**Issue by uwupeach** [ObliqueNET/Server#882]
During the process of completing the Ghostbusters! legendary quest I found that you can restart after catching the Rotom that is not in a form at lvl 50. After accidentally killing Marshadow I used /home for more pokeballs and it reset my quest progress to "Enter the Mansion" allowing me to recatch the Rotom in order to get back to the legend fight. 

I provided a screenshot of the Marshadow received and the two Rotoms earned in the process.
![19b97f6dc1556d059219081edaa51c17](https://user-images.githubusercontent.com/72329594/100538282-ce718d80-31fc-11eb-982a-e020482f3114.png)

**Comment by Soshisen** [comment]
Thank you for informing us of this error. It has been fixed and that pokemon has been made uncatchable
