### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by pedrothetech** [ObliqueNET/Server#886]
Hello, I would like to apologize for any and all issues that may have been caused and ill get a clean download of the modpack but I would very much appreciate a second chance and more in-depth explanation of the situation my discord ign is pedro#7132 , and I didn't plan on ruining my future on this server since I quite enjoy it and drop a rank Friday since I planned to stick around the community for a while. 
thank you for taking the time to read this, have a good day

-Pedro

**Comment by Katadreme** [comment]
You seem very genuine with your appeal,
