### ISSUE TITLE
ban appeal 

### ISSUE THREAD

**Issue by biojory** [ObliqueNET/Server#887]
I was banned for using x-ray and I would like to ask for a second chance since when I used it it was for diamonds at the beginning that they did not help me since it does not make sense to have full diamond on this server and I forgot to uninstall it, I really apologize since I played a lot and I don't want to lose my progress.

**Comment by biojory** [comment]
ign: Biojory

**Comment by Katadreme** [comment]
I'll give you another chance but know xray mods are strictly forbidden so this ban will quickly be reimplemented if we find you logging in with xray mods again.
