### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by TheCrazyGame2** [ObliqueNET/Server#888]
I'm apologize for broke the rules of this server and i never insulted the admins. This is the best server for pixelmon. I really enjoy play this server with my other friends. I have understood my mistake if you can give me another chance to improve myself i would be very glad if you accept my request. 

Hoping to see you soon on the server.

TheCrazyGame2

**Comment by Katadreme** [comment]
Sorry to say, I think you're out of chances. You were told by **4** separate staff members that making / using an afk machines is against the server rules, and which you made multiple machines, and even after they were removed by staff, you re-built the afk machines in front of staff and immediately start using it (shown below). This all shows how you aren't genuine about apologising about these 'mistakes'. Your appeal has been declined.

![Screen Shot 2020-12-07 at 3 15 13 pm](https://user-images.githubusercontent.com/50907133/101308927-22384280-389f-11eb-9c91-1faadbfd42ba.png)
