### ISSUE TITLE
Lunala quest issue

### ISSUE THREAD

**Issue by SyCoAir** [ObliqueNET/Server#892]
999way could not fight lunala due to abnormal end and it would not let him fight lunala again

**Comment by menno516** [comment]
just tested disconnecting with turning wifi off, getting kicked and just normally ending the battle.
Couldnt find a problem with the end battle abnormal in the lunula battles

these battles are stage 9 and 11.

**Comment by Rasgnarok** [comment]
If this is part of a bigger pattern of tickets with all 'abnormal end' issues, please test and confirm, and link all tickets together. Close all doubled tickets. Keep one master ticket up, and ping me so I can assign it to a dev.

**Comment by Rasgnarok** [comment]
Closing in favour of master ticket. Quest battle loop is working as expected, warp trigger will be fixed.
