### ISSUE TITLE
Lunala end battle stage.

### ISSUE THREAD

**Issue by menno516** [ObliqueNET/Server#893]
When you are in lunalas den to fight it for the last time **before** capturing it, if you get kicked/disconected mid battle you will be set back to enter the portal and still be in the den when you reconnect. 
Stage 9 this is :)

![image](https://user-images.githubusercontent.com/63118334/100825008-6c609480-3457-11eb-8f04-065c710b6568.png)

**Comment by Rasgnarok** [comment]
If this is part of a bigger pattern of tickets with all 'abnormal end' issues, please test and confirm, and link all tickets together. Close all doubled tickets. Keep one master ticket up, and ping me so I can assign it to a dev.

**Comment by Rasgnarok** [comment]
Closing in favour of master ticket. Quest battle loop is working as expected, warp trigger will be fixed.
