### ISSUE TITLE
A Soul for a Soul quest missing npc

### ISSUE THREAD

**Issue by menno516** [ObliqueNET/Server#894]
on stage 20, 25 and stage 31 of this quest, the player needs to talk to a npc called niko... ehm Nikolaos, yeah Nikolaos.

But now the funny part is, he aint there. Guess he went to play hide and seek.

Nikolaos aint on his location where he needs to be for the quest, so when a player tries the oxus part they can proceed the quest.
location it needed to be on: -716 79 -1088

(4th day in a row on tracker, i am building a streak rn)

**Comment by Soshisen** [comment]
Has been fixed for awhile. Just forgot to close this ticket
