### ISSUE TITLE
Sudowoodo quest issue

### ISSUE THREAD

**Issue by SyCoAir** [ObliqueNET/Server#895]
Player was"in battle" with sudowoodo but he said he was not. he was on stage 3 hidden twice.
<img width="262" alt="Screen Shot 2020-12-02 at 1 50 05 PM" src="https://user-images.githubusercontent.com/74997268/100935932-a193d380-34a5-11eb-89c0-4638f5e4ce6f.png">

**Comment by Rasgnarok** [comment]
If this is part of a bigger pattern of tickets with all 'abnormal end' issues, please test and confirm, and link all tickets together. Close all doubled tickets. Keep one master ticket up, and ping me so I can assign it to a dev.

**Comment by Lieren-HuntGhosts** [comment]
Tested it. This only seems to happen when disconnecting

**Comment by Rasgnarok** [comment]
Closing in favour of master ticket. Quest battle loop is not working as expected, warp trigger will be fixed.
