### ISSUE TITLE
BAn appeal

### ISSUE THREAD

**Issue by diocancro666** [ObliqueNET/Server#902]
Is not my fault if this site flagged my account 3 time and no one know why!!!!!!
i went on discord just for ask this and i get banned all the time ; 
it was the only thing I could do! I was no longer on the site or on the server how could I make my appeal?
only 2 days ago i'm been able to write my appeal thanks to a staff who answered me in private...

as for the spam on this site I was actually wrong, I have a very old computer and when I pressed on new issue it did not load on my screen but in reality it published many; that's why I removed them I know I wanted to spam I didn't remove them ... sorry!

in the end since the apologies are not enough, I ask one last time to be unbanned and the only thing I can still promise is to NEVER write again.
sorry for my attitude please review the ban and change it with a temporary one.

**Comment by diocancro666** [comment]
I just wanted to add that given my playing time on the server I can also help out with the silly quest questions (which I have asked every now and then) without other players disturbing you

**Comment by diocancro666** [comment]
@Katadreme @ElementalMP 
![screenn](https://user-images.githubusercontent.com/75269257/101043127-408bfe80-357e-11eb-85c7-d39cb44e86eb.png)

**Comment by ElementalMP** [comment]
Multiple staff members have communicated to you result and reasoning as per your ban appeal. Re-hashing the previous appeal will not grant you an unban, nor does it help your case. Please do not post further issues to this tracker, your appeal has been declined.
