### ISSUE TITLE
Murmurs hidden stage 8

### ISSUE THREAD

**Issue by menno516** [ObliqueNET/Server#903]
on stage 8 of Murmurs you need to go back to the village, but when you check your quests it is invisible and doesn't give you the objective. 

because of this, it doesn't show up at the front page.
![image](https://user-images.githubusercontent.com/63118334/101078485-8a88da80-35a6-11eb-97b9-456fd2db9c8a.png)

**Comment by Soshisen** [comment]
This has been corrected
