### ISSUE TITLE
Stuck During Choosing Wisely Quest

### ISSUE THREAD

**Issue by BigBamShazam** [ObliqueNET/Server#904]
Hi there. 
I was doing the guild selection quest ("Choosing Wisely") and got to the part where you enter the guild hut and choose one of the three guilds. I talked to the Vulpe recruiter first, but clicked too many times and got teleported to their base. Then I got a message confirming whether I wanted to choose Vulpe as my guild. I decided to decline and check out the other two choices, so I went back to the hut but the quest info was telling me to go inside the Vulpe base. I tried to talk to the other two recruiter NPCs, but they wouldn't let me join either of their respective guilds. I then tried to go in the Vulpe base to advance the quest, but nothing happened. I tried to walk around the base more, in and out, die, re-log, but nothing changed. I don't know of any way to reset the quest, and it's a requirement for other quests, so I would appreciate help. 
Thank you.

**Comment by UnknownFlash** [comment]
Try /guild join vulpe if you haven't already.

**Comment by BigBamShazam** [comment]
> 
> 
> Try /guild join vulpe if you haven't already.

Thank you very much! This worked, I can progress now.
