### ISSUE TITLE
Ban appeal 

### ISSUE THREAD

**Issue by TheCrazyGame2** [ObliqueNET/Server#905]
Staff you are all a bunch of clowns you unban people after they apologize for using xray, me for using the stupid afk machine no, ok just because I'm fucking you. Think about doing the quests well that surely the one I had bugged is still so since you are morons and out of three quests two get bugged. Nice mentality keep it up. @ElementalMP @Katadreme

**Comment by Katadreme** [comment]
Thank you for further proving my point about your disingenuity, you chances of being unbanned just clearly got higher.
