### ISSUE TITLE
Problem with  Avenging flames quest

### ISSUE THREAD

**Issue by StampedGoblin29** [ObliqueNET/Server#906]
The quest avenging flames is showing up yellow and complete on my quest book, before that happen I i was trying to get moltres but the server was laggying and it glitch me out

**Comment by menno516** [comment]
what is your ign my friend?
ill see what kind of magic i could use to help you

**Comment by StampedGoblin29** [comment]
It's STampedGoblin29

**Comment by Rasgnarok** [comment]
Closing as this should be solved. Likely related to a latent abnormal end bug. There's already a ticket open about that.
