### ISSUE TITLE
[Mia] Doesn't answer to DMs

### ISSUE THREAD

**Issue by Doughnutchickenishot** [ObliqueNET/Server#907]
when asking mia how much money I have. I got this in return 

https://gyazo.com/f45589fc7ce5ea3b417e138c19ba4aec

**Comment by Rasgnarok** [comment]
Fixed in #bots-spam, but she still doesn't answer to DMs. Update was applied. Any ideas @Hiroku ?

**Comment by Rasgnarok** [comment]
![image](https://user-images.githubusercontent.com/18584380/104493710-7079e900-55a3-11eb-9f5f-1df6e84a154e.png)

**Comment by Rasgnarok** [comment]
https://github.com/ObliqueNET/Server/issues/860

**Comment by Vohras2** [comment]
Ix fixed now, I believe.
