### ISSUE TITLE
#908 quest legend solgaleo not having its unique texture

### ISSUE THREAD

**Issue by xTwilly** [ObliqueNET/Server#908]

**Comment by Rasgnarok** [comment]
If this is related and confirmed to be a bug with https://github.com/ObliqueNET/Server/issues/919, keep one ticket and close the doubled one. Confirm no special texture is working properly. Otherwise, test these two quests individually, and ping me back.

**Comment by PrimalCyndaquil** [comment]
This issue should be fixed as of the latest pack update, which changed the previous solgaleo.png texture file to solgale-normal.png. Please contact a staff member ingame about getting your Solgaleo textured, if it still needs to be.
