### ISSUE TITLE
Toxapex unable to relearn an egg move

### ISSUE THREAD

**Issue by Jackquaman** [ObliqueNET/Server#909]
My Toxapex knew Haze at one point, but the move was accidentally forgotten. The move re-learner will not list it as a move that can be relearned. I gave the Toxapex to a differnt player, who attempted to use an egg move token on it, and it told the player that Toxapex cannot learn any egg moves.

**Comment by Rasgnarok** [comment]
This should be reported directly to the PixelmonMod, https://pixelmonmod.com/tracker.php?p=2.
