### ISSUE TITLE
ban appeal

### ISSUE THREAD

**Issue by swaggercakes** [ObliqueNET/Server#910]
im confused i know the only other modpack i have installed is fullbright pack it makes it so i don't have darkness but idk how that happened 

![image](https://user-images.githubusercontent.com/75719784/101597301-64e74100-39ab-11eb-8ef8-c25b24edc6e1.png)

**Comment by swaggercakes** [comment]
i didnt mean to close it

**Comment by meepro27** [comment]
Hello, I'm RareFraction
I'm here to say that I was warning 2nd times about the afk I was doing, I didn't now the 3rd one why I was banned and  I wasn't informed about the 3rd one. I Joined to the server about 2 mins and I was talking to my town leader suddenly I was banned and I have no idea.

**Comment by DiddyTheKid** [comment]
Hello RareFraction,
Please make a new post for your ban appeal. Do not post on previous ban appeals. To make a new issue you should see a button to click that says new issue and you can title it "ban appeal". Don't forget your IGN.
Thank ya!
