### ISSUE TITLE
Battle timer appears when leveling Pokémon with a rare candy

### ISSUE THREAD

**Issue by starwarschamp4** [ObliqueNET/Server#911]
Title says it all, I was leveling up a Pokémon with my rare candies and the battle timer appears in the top right of my screen. Doesn't count down or anything, it's just there. Goes away after level up GUI.

**Comment by Rasgnarok** [comment]
This should be reported directly to the PixelmonMod, https://pixelmonmod.com/tracker.php?p=2.
