### ISSUE TITLE
Queue button goes away if too many gym leaders are on

### ISSUE THREAD

**Issue by starwarschamp4** [ObliqueNET/Server#912]
So where the join queue button is in the /aquagyms command, if there are too many gym leaders for that gym online it gets covered up by a gym leader's head. Menu needs editing to stop this from happening.

[https://imgur.com/a/ePCLXnx](url)

**Comment by Rasgnarok** [comment]
Reported to the developer, that's a nifty bug alright 
![image](https://user-images.githubusercontent.com/18584380/103230667-fccdb000-4903-11eb-8af8-7fdc1b0916e8.png)

**Comment by Rasgnarok** [comment]
WaterdudeToday at 12:07 PM
There's a setting to make the UI bigger
I'll add an autosize option as well
And pages perhaps too
And perhaps only show online as an option too

**Comment by ElementalMP** [comment]
Resolved.
