### ISSUE TITLE
fuck you guys i did nothing wrong 

### ISSUE THREAD

**Issue by fatboomer69** [ObliqueNET/Server#914]
i literally got permabanned for calling someone a pussy. wtf. I don't get it.

**Comment by ElementalMP** [comment]
Can we get an IGN

**Comment by fatboomer69** [comment]
yeah its drericeto

**Comment by ElementalMP** [comment]
Unfortunately a ban appeal for that player has already been declined. Have a nice day!

**Comment by fatboomer69** [comment]
fuck you and suck my cock
you ruined my day with your retardation
