### ISSUE TITLE
Cinccino unable to learn Triple Axel

### ISSUE THREAD

**Issue by Epix120** [ObliqueNET/Server#915]
Cinccino is unable to learn Triple Axel despite being able to learn it in Gen 8.

**Comment by Soshisen** [comment]
Is this a problem in single player?

**Comment by Epix120** [comment]
yeah

I'm assuming that means that I shouldn't have left a ticket for something that is not server related

**Comment by Soshisen** [comment]
Yes and no, please report it here: https://pixelmonmod.com/tracker.php?p=2
That's the Pixelmon bug tracker. They need to address it
