### ISSUE TITLE
Shop signs not charging

### ISSUE THREAD

**Issue by BootyHadMeLike** [ObliqueNET/Server#916]
So I have refrained from making this post because the amount of information on the issue has not been sufficient for me to fully understand what is going on and explain it. That being said, the issue has occurred quite a bit to the point it needs to be brought up. The best I can do is explain what happens in detail. While I do not have actual evidence of how or why this happens, I, along with some others have experienced it first hand and can attest to it.

The issue occurs when a player attempts to buy something from a shop sign. What will happen is, the player will receive the item for free, and there will be no actual transaction. So, if I were the buy an Exp. All from a shop, this is how it would happen. I right-click the sign, I receive the item. There is no prompt in the chat of making the purchase for either the buyer or the seller. There are no logs in the carrotreport. The player is not charged and the seller is not paid. In the case that the item taken from the shop is the last item in the chest, the shop sign will actually remain blue, wherein the instance of buying the last item in a chest would typically turn the blue to red, indicating the chest as empty. This has been a major factor in us recognizing when this has actually happened.

I have tried quite a bit, and I can not find a way to replicate this happening. It really seems random and I cannot draw a correlation to what causes it. It happened to Canary in front of me with no special circumstances that I can remember. It also happened to mc5303 right in front of me, and again there was nothing special about the instance. I asked him if there was a specific way he did it, a specific item he was holding maybe, but nothing stood out. Whatever is going on here, there are instances of this happening unintentionally.

The first time this was drawn to our attention was on accident about 2 months ago, when Canary right-clicked my Exp. All sign while running around the shop. She got the item for free and neither of us had any transaction. Over time, it has happened well over 20 times that we KNOW OF. Canary has a much smaller amount of shop chests, so she tends to notice it much more than me, as well as she has access to carrotreport (my carrotreport doesn't work anymore for some reason, but that is another issue). She has come to me about this happening a multitude of times, so it needs to be brought up.

Now there is something I have noticed about every instance that we know of. Everytime we have noticed this happening, it has always been with items that do not stack. Examples that this has occurred with is Exp. All, Elytra, Armor sets, Mending books, and arcade vouchers (pixel sprites). It could be the case that perhaps this is a factor, or maybe it's just more noticeable because these items are much easier to notice if they are displaced. Either way, Canary has lost too many armor sets and books to count at this point, so it is a real bother, on top of the other outstanding issue.

Feel free to reach out to me if there are any questions.

**Comment by Rasgnarok** [comment]
Duplicate, part of the bigger caching issue detailed in https://github.com/ObliqueNET/Server/issues/878.
