### ISSUE TITLE
ban appeal

### ISSUE THREAD

**Issue by swaggercakes** [ObliqueNET/Server#918]
i use a texture pack called fullbright and it fucks up with my optifine even though it says it works well with optifine but it basically allows me to see through blocks sometimes and i took full advantage of that and i am sorry but i cant say that ill delete because i can just say that but if you guys gave me the chance to stop using it i will

**Comment by Katadreme** [comment]
I apologise for the long delay in responding to your appeals. I will unban you under the condition like you stated, that you have deleted any of the hacks / mods /packs that you were using before that resulted in your ban. If we find you still have them enabled, the ban will be reinstated.
