### ISSUE TITLE
Quest: Ode of destruction

### ISSUE THREAD

**Issue by menno516** [ObliqueNET/Server#919]
oops, accidently posted without anything in it.

The quest does not give you a beautiful quest textured solgaleo but a normal 1, The capture stage is on stage 14/15.
I have checked this myself.

**Comment by Rasgnarok** [comment]
If this happens to all quests with special textures, please make sure that we can have a master ticket. If this only happens with this quest, please edit the title accordingly to clarify. Testing this is necessary.

**Comment by PrimalCyndaquil** [comment]
Issue same as #908 , should also be fixed. Closing.
