### ISSUE TITLE
[LoginMessages] /logmessages Broke ;-;

### ISSUE THREAD

**Issue by UnknownFlash** [ObliqueNET/Server#920]
after setting a login/logout message it works for the first logout and the first login then resets itself after that, meaning you have to set it all again.

**Comment by Hiroku** [comment]
I looked into it, I suspect you actually died. I've fixed it so it saves into persisted player data, meaning player death won't wipe your settings. People with existing log messages should see their messages remain saved properly

**Comment by Rasgnarok** [comment]
Fixed for next restart.
