### ISSUE TITLE
[Questlore] Kyogre and Giratina Questlore not unlockable

### ISSUE THREAD

**Issue by Blitzmentalist** [ObliqueNET/Server#924]
It is currently not possible to unlock Giratina and Kyogre's entries in the legendary quest information in /questlore.

**Comment by Rasgnarok** [comment]
Ticket doubled, closing duplicate. https://github.com/ObliqueNET/Server/issues/884

**Comment by Rasgnarok** [comment]
After testing, looks like autounlocked doesn't work at all. That said `/givelore Rasgnarok lore.quests.legendaries.kyogre` works as expected. Files are normal.

**Comment by Rasgnarok** [comment]
![image](https://user-images.githubusercontent.com/18584380/105114394-cdd6d400-5a94-11eb-909c-cdca23cb7665.png)
autounlocked=true doesn't work still however

**Comment by Rasgnarok** [comment]
![image](https://user-images.githubusercontent.com/18584380/105114519-08d90780-5a95-11eb-8a6f-0ad30147cc0d.png)

**Comment by Hiroku** [comment]
This is all now confirmed fixed. The issue with Kyogre and Giratina is their lore files were encoded as UTF-8-BOM instead of UTF-8.
