### ISSUE TITLE
Incorrect Start Location on Heill Quests

### ISSUE THREAD

**Issue by purifiedrabbits** [ObliqueNET/Server#925]
**I have compiled this into one ticket with several posts because they all have the same issue :)**

**Start location for "Iron Maiden" need to be changed to -22 98 -68 on both Oblique Wiki and /questlore**

Oblique Wiki: ![image](https://user-images.githubusercontent.com/73670259/103257791-8e124600-4947-11eb-820f-f5715a3eaed5.png)
/questlore: ![image](https://user-images.githubusercontent.com/73670259/103257810-9b2f3500-4947-11eb-87fc-5addacd42198.png)
Where the chords take you: 
![image](https://user-images.githubusercontent.com/73670259/103257823-ab471480-4947-11eb-907f-1fb0f6363cd4.png)
Where the quest starts: 
![image](https://user-images.githubusercontent.com/73670259/103257836-b732d680-4947-11eb-9c26-3df3d490a099.png)

**Comment by purifiedrabbits** [comment]
**Start location for "War Effort" is incorrect. Have not found where it starts. Last photo is where I would think it starts, given there is no quest that starts from the NPC "General Angin," but it does not start here. Chords to this NPC are: -19, 116, -57**

Oblique Wiki: 
![image](https://user-images.githubusercontent.com/73670259/103335382-a195dd80-4a29-11eb-8345-f003ff1b4914.png)
Where it takes you: 
![image](https://user-images.githubusercontent.com/73670259/103335402-aeb2cc80-4a29-11eb-8dd3-1e7a452f139b.png)
Where I think it is supposed to start, but does not: 
![image](https://user-images.githubusercontent.com/73670259/103335512-fb96a300-4a29-11eb-972a-eaa6713e482d.png)

**Comment by purifiedrabbits** [comment]
**"Witch Hunt" start location chords need to be changed to -80 94 -36 and added to /questlore**

Oblique Wiki: 
![image](https://user-images.githubusercontent.com/73670259/103385486-81a8fd00-4aaf-11eb-875a-817cda1767e1.png)
/questlore: (doesn't even have it) 
![image](https://user-images.githubusercontent.com/73670259/103385500-96859080-4aaf-11eb-8014-bb1bbbc1a7ce.png)
Where the chords take you: 
![image](https://user-images.githubusercontent.com/73670259/103385538-b74de600-4aaf-11eb-8e86-0676a7882e2f.png)
Where the quest starts: 
![image](https://user-images.githubusercontent.com/73670259/103385545-c16fe480-4aaf-11eb-9954-9eb69df6f4b4.png)

**Comment by Soshisen** [comment]
I have already updated the wiki with these cords. Just need to update in game quest lore with them

**Comment by Soshisen** [comment]
Fixed, thank you for the information
