### ISSUE TITLE
Quest: Bugs in the System [Progress Error]

### ISSUE THREAD

**Issue by purifiedrabbits** [ObliqueNET/Server#926]
Step 7: Interact with the statue (enters you into battle with a gigalith)
Step 8: Capture the Gigalith

Issue: While in battle with the Gigalith, if you /endbattle, the quest does not get set back a step and leaves you to capture the Gigalith without allowing you to enter battle with it again.

**Comment by Rasgnarok** [comment]
If this is part of a bigger pattern of tickets with all 'abnormal end' issues, please test and confirm, and link all tickets together. Close all doubled tickets. Keep one master ticket up, and ping me so I can assign it to a dev.

**Comment by Rasgnarok** [comment]
Closing in favour of master ticket. Quest battle loop is working as expected, warp trigger will be fixed.
