### ISSUE TITLE
Got banned would like a seccond chance

### ISSUE THREAD

**Issue by BotchThetop** [ObliqueNET/Server#929]
got me with the x-ray i aint gon lie im kinda new to this whole minecraft server thing actualy bought minecraft to play pixelmon... pleaze give me a seccond chance ill be a good boy i swear  :)     BotchTheTop with all the love you want

**Comment by BotchThetop** [comment]
illl give back the money i made anything you wnat ;0 lol

**Comment by BotchThetop** [comment]
want*

**Comment by fatyg5** [comment]
You will be unbanned, but should you be caught on our server with any hack mods again, you will be permanently banned.

**Comment by BotchThetop** [comment]
thanks my guy appreceate it ill do your server right this time much love xoxo

**Comment by BotchThetop** [comment]
i didnt know how to uninstal it my friend did it for me now it is unistalled but i am still banned...

**Comment by BotchThetop** [comment]
![mods](https://user-images.githubusercontent.com/76893521/103491167-76c3d480-4def-11eb-8963-ca567c494db8.PNG)

**Comment by fatyg5** [comment]
Unbanned again. Don't let it happen anymore.
