### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by CalebD27** [ObliqueNET/Server#931]
Hey I've been playing on this server for several years probably since it was released. anyway I was banned the other day for "Grieving" an unclaimed area in the end dimension I'm totally okay with giving back what I took if I got unbanned. I love playing on this server with my friends and id prefer not to play on any other servers as I have a lot of great memories here and I hope it doesn't have to end like this.

**Comment by Katadreme** [comment]
I understand you have played on the server for a long while, which leads me to question, that you'd know that griefing of any kind is not tolerated on the server, as it is one of the biggest rules on this server, as well as others. You would've been aware of the server rules so unfortunately I going to be declining your request for appeal.
