### ISSUE TITLE
#market Broken

### ISSUE THREAD

**Issue by UnknownFlash** [ObliqueNET/Server#933]
In #market Mia has not added new listings which are on /market list since the 29th of december. thought this should go in here.

**Comment by UnknownFlash** [comment]
Edit: seems she actually removes them after 10 minutes or so when no one has removed them in game.

**Comment by Rasgnarok** [comment]
Market should be fixed now, forgot to comment on this issue. Thanks for the report!

**Comment by UnknownFlash** [comment]
It appears that #market has not been fixed and still removes the listings after a short period of time.
