### ISSUE TITLE
AceTalon21s Ban Appeal

### ISSUE THREAD

**Issue by AceTalon21** [ObliqueNET/Server#935]
YO LET ME BACK ON

**Comment by Katadreme** [comment]
Yeah no. Some sort of composure is needed for a ban appeal and this is exactly not that. Your appeal has been denied. Feel free to continue and i'll make your ban a permanent one.

**Comment by AceTalon21** [comment]
Asshole dumb ass muthafuckin BITCH! LET ME ON!

**Comment by Katadreme** [comment]
And theres your permaban.
