### ISSUE TITLE
A beggars appeal

### ISSUE THREAD

**Issue by AceTalon21** [ObliqueNET/Server#937]
YO Im sorry for the disrespect and the messed up pokemon names - I promise it wont happen again. Ims so sorry please unban me, Im asking for even the most microscopic amount of forgivness - Plese, PLEASE let me back on and youll never hear a single peep out of m, ill always vote, ill do ANYTHING to get back on. So please, plese forgive me, im sorry and desperatly wish for a nother chance

**Comment by Katadreme** [comment]
No. You should've dropped this act earlier. But you had your chances and they're gone.
