### ISSUE TITLE
[Support Request] leave me alone

### ISSUE THREAD

**Issue by JackDimonds** [ObliqueNET/Server#942]
I have copy and pasted all of the chats involved in the conversation. I do not want them to conduct communication with me. My troll nature is indeed is existent, but the love of focusing the attention on me is immaculate. They followed me during the entire trivia. I do not want them to do this every time I go to events. What I did was say that the trivia answer was wrong, but the trivia operator did it as a joke.  They did this for the last two questions of trivia, which in theory would have been 20% of the multiple choice section. I left the trivia for the question about next trivia because I felt it was best.

In an attempt to help my negative status in the eyes of those who matter, I am filing a ticket instead of pursing the issue in person. 

[♥][Master]Profkoz[★]: my man jack u gotta calm down
[Beast]JackDimonds: ProfAwesome100 mad
[Beast]JackDimonds: spend money on MC server because mad
[♥][Beast][Staff]KiriAwesome100[★][●]: lmao he didnt buy his rank
[♥][Master]Profkoz[★]: spending money?  I didn't buy the rank
[Beast]JackDimonds: color name = big knee
[♥][Master]Profkoz[★]: and u call me mad lol

At this time I do believe was when I left trivia. I did not say anything too them after this time. Everyone was doing /f (to flood the chat as a community) and I added a legend to the wondertrade pool, simply to get the "clout" of doing it in that instance, as some newer players were in the voice chat I was in. 

JackDimonds has added a legendary to the Wondertrade pool!
Try your luck at getting it with /wondertrade

[♥][Beast][Staff]KiriAwesome100[★][●]: lmao so mad he added legend to wt
[Beast]JackDimonds: Im mad
[♥][Beast][Staff]KiriAwesome100[★][●]: yeah i know
[♥][Beast][Staff]KiriAwesome100[★][●]: its obvious
[♥][Beast][Staff]KiriAwesome100[★][●]: stick to twitch buddy
[Beast]JackDimonds: Can KiriAwesome100 leave me alone
[Beast]JackDimonds: I will file ticket if not
[♥][Master]Profkoz[★]: do it

I do not have any pictures in game, other than this. The issue was taken out of discord server chat. The instance was at ~9:55? over the course of time

**Comment by Rasgnarok** [comment]
I apologize in advance for that snippet there. Staff know better than to antagonize. You will be contacted soon to discuss this further.

**Comment by Katadreme** [comment]
Since both parties have been spoken and warned an reprimanded, closing this ticket.
