### ISSUE TITLE
[Trivia] Pixelmon forms duplicating valid answers

### ISSUE THREAD

**Issue by fatyg5** [ObliqueNET/Server#943]
![Screenshot_20210112-232024_Discord](https://user-images.githubusercontent.com/8277657/104406248-dc6d3a80-552c-11eb-94c0-1d7988740139.jpg)

Too many Alcremie

**Comment by Rasgnarok** [comment]
What is likely happening here is simply Trivia running the possible answers based on valid, registered forms in Pixemon's entity form list. Not a bug on its own, but we can likely patch it to circumvent it. Low-priority.

**Comment by Rasgnarok** [comment]
Fixed for next restart.
