### ISSUE TITLE
Issue with kicking town members.

### ISSUE THREAD

**Issue by PJLesure** [ObliqueNET/Server#944]
When you try and kick a person from your town, it will not work if they have been inactive for a certain amount of time. For example, my town mayor was able to kick me from the town, but in the case of many players in our town (who were last on 18+ days ago) when attempting to kick them it tells us that it is an "Invalid user." We tested this several times even with Kata getting the results that if a player has been inactive for a certain amount of time, you cannot kick them from your town.   

<img width="384" alt="Screen Shot 2021-01-12 at 8 21 18 PM" src="https://user-images.githubusercontent.com/77369060/104407311-2ac30f00-5516-11eb-938e-fc6dfb53bc12.png">

**Comment by Rasgnarok** [comment]
Kicking offline (uncached) player. Will need to test the error in console first. Closing linked ticket in favour of masterticket.
