### ISSUE TITLE
Nidoking Texture Voucher Troubles

### ISSUE THREAD

**Issue by Treejan976** [ObliqueNET/Server#945]
I tried applying the Vohras 2 Texture to a Nidoran Male and it removed the texture voucher without giving the texture. I had spoken with Vohras in the past and he had mentioned about how one of the Nidoking line textures was supposed to be removed due to bloat.

It might be possible the actual texture was removed and the GUI isn't properly updated to reflect this. Furthermore, if you apply the Vohras 1 Texture to a Nidoking, it gives the sprite texture of a Vohras 1 Texture (black), but the actual model is a Vohras 2 Texture (red).

**Comment by Rasgnarok** [comment]
Will be fixed upon next restart. I just need your username to refund the texture voucher lost, pretty please!

**Comment by Rasgnarok** [comment]
Just refunded, username was Le_Tree. Closing the issue, will be fixed as of next restart.
