### ISSUE TITLE
I'm not able to take a picture of king dig on the path to nogrod

### ISSUE THREAD

**Issue by ThatCursedBre** [ObliqueNET/Server#947]

**Comment by Rasgnarok** [comment]
Can you explain a bit more?

**Comment by ThatCursedBre** [comment]
on route 4 going from agni to nogrod you are required to talk to a scientist then take a picture of the shiny diglett named king dig in the cave and bring it back to the scientist

**Comment by Soshisen** [comment]
Player had 3 active quest and couldn't start quest. Closing ticket
