### ISSUE TITLE
[Mia] Taking Down Unbought Pokemon From #market

### ISSUE THREAD

**Issue by ProfAwesome100** [ObliqueNET/Server#949]
<img width="354" alt="Put on Market" src="https://user-images.githubusercontent.com/60492306/104511303-7d560700-55ba-11eb-82db-819ccec3d12a.png">
Solosis put on market at 4:09 pm and was taken down from channel at 4:19 pm (E.S.T), mon still unbought.
<img width="505" alt="Unbought" src="https://user-images.githubusercontent.com/60492306/104511825-4d5b3380-55bb-11eb-99c1-62be0bee2e79.png">

Second attempt: Put another pokemon at 4:19 pm and a Larvitar at 4:27 pm, both cleared at 4:29 pm (10 mins from the original mon)

**Comment by Rasgnarok** [comment]
Not sure if related
![image](https://user-images.githubusercontent.com/18584380/104527550-fbbea300-55d2-11eb-9476-ba612ee053d7.png)

**Comment by Hiroku** [comment]
We're not gonna talk about what caused this one, fix will go live on the next restart though

**Comment by Rasgnarok** [comment]
Fixed for next restart.
