### ISSUE TITLE
Redeeming a texture voucher

### ISSUE THREAD

**Issue by Zoru-chan** [ObliqueNET/Server#951]
Redeemed a texture voucher on my dusk lycanroc and it consumed the voucher but didnt change my lycanroc. Texture is called Shapook.

**Comment by Vohras2** [comment]
The shapook texture isn't for dusk Lycanroc. It's for the mid-day form.

**Comment by Vohras2** [comment]
What's your IGN?

**Comment by Zoru-chan** [comment]
Oh! Zoru_chan XD sorry

**Comment by Vohras2** [comment]
Refunded.
