### ISSUE TITLE
[Quest] Objective Battle_End_Abnormal

### ISSUE THREAD

**Issue by Soshisen** [ObliqueNET/Server#956]
Using the /endbattle command does complete Battle_End_Abnormal. However any other way that should complete the objective does not work, or is not completing the whole set of triggers. These include logging off, /kick command, closing MineCraft, and Alt+F4. 

During my test I found a quest, Bugs in the System,  that did not have this objective written into it. After correcting this issue the trigger worked on all exit types. While not all the triggers set into that objective fired (most notably the Warp trigger) the Set_to_Stage trigger did work. With this in mind I set to testing other quests.

My main test subject was Avenging Flames. As stated before /endbattle worked correctly. However no other condition that should set off the objective worked. I looked at the delay timers to see if there was a difference . Bugs in the System had a delay of 2, while Avenging Flames had a delay of 5.So I set Avenging Flames’ delay to 2.Testing further still resulted in all conditions not completing the objective as they should. I then deleted the objective from the quest and built it again from scratch. This also did not work. 

From there I tested other quests to make sure the results were the same: 

The Woodworker has the same results as Avenging Flames. 

Fallen but Not Forgotten has the same results as Avenging Flames

Paean of Affliction would complete the Battle_End_Abnormal, however the warp trigger would not go off. Leaving the player stranded in an area they could not leave without commands.

These quests were used as they had current tickets in the tracker for this issue. 

General Battle_End_Abnormal https://github.com/ObliqueNET/Server/issues/913

Bugs in the System: https://github.com/ObliqueNET/Server/issues/926

Avenging Flames https://github.com/ObliqueNET/Server/issues/873

The Woodworker https://github.com/ObliqueNET/Server/issues/895

Fallen but Not Forgotten https://github.com/ObliqueNET/Server/issues/871

Paean of Affliction https://github.com/ObliqueNET/Server/issues/892
    https://github.com/ObliqueNET/Server/issues/893

Just today I had the same issue with a completely different quest Small Fry. Here are the screenshots explaining what happened.
![Untitled-1](https://user-images.githubusercontent.com/30008421/104786881-19127f00-5743-11eb-97ec-de870c3584bd.jpg)
![Untitled-2](https://user-images.githubusercontent.com/30008421/104786886-1b74d900-5743-11eb-8995-982cc5480415.jpg)

As you can see the player shut down their MineCraft and the error occurred.

**Comment by Rasgnarok** [comment]
(for me) tldr

1) #873 (Avenging Flames), #895 (The Woodworker) and #871 (Fallen but not Forgotten): /endbattle completes Battle_End_Abnormal, but a hard crash or /kick does not. Triggers do not fire.
2) #892 #893 (Paean of Affliction) and #926 (Bugs in the System): /endbattle completes Battle_End_Abnormal, and so does /kick. All triggers fire as expected.
3) The warp trigger should execute on offline, as /kick or a hard crash should complete Battle_End_Abnormal.

**Comment by menno516** [comment]
![image](https://user-images.githubusercontent.com/63118334/104838521-aaa4fc80-58bb-11eb-9a8f-5f8a729c8867.png)

I had to help this player today since he got the End_Battle_Abnormal issue. As said in the picture below he was on the catching state when his game crashed, I checked his quest to see what stage he was on and to tell if it was true. (stage 51)

Once I did that I checked for the best stage to put him on by setting myself on it first, after finding it I put him on the stage again in the right area. (stage 50)

**Comment by PrimalCyndaquil** [comment]
I've built a very short test quest in the QD Training area for testing the battle-end-abnormal and log-off objectives in a battle. Both of these objectives have a trigger which sends mail to me, to check if any other triggers (Such as skip-to-stage) activate.

What ended up happening was that closing minecraft during the battle did not activate either of these objectives or their triggers.

**Comment by PrimalCyndaquil** [comment]
Based on #984 It seems as though this issue is not regulated to just battles, either.

**Comment by Lieren-HuntGhosts** [comment]
Adding "Flute of the Pure Note" Stage 17 to the list

**Comment by Vohras2** [comment]
Closing to merge this with a more generalized quest bug composite thread.
