### ISSUE TITLE
./Warp tpwickedshadow498 signs "scamming" players

### ISSUE THREAD

**Issue by Bluespider20** [ObliqueNET/Server#957]
Multiple people today (Foshizel, FancyCroissant, and some others) have said that they were buying/selling something to a shop, specifically ./warp tpwickedshadow498 when either it costed them more or they were paid less than they were supposed to get. 
![Glitchy signs 1](https://user-images.githubusercontent.com/68312670/104797729-2e080600-5775-11eb-9ed3-2473b4a3f042.png)
![glitchy signs 2](https://user-images.githubusercontent.com/68312670/104797746-4a0ba780-5775-11eb-91ab-aa96a6934928.jpg)
I tried another shop but it wasn't happening so probably not the biiiiiiigggest concern, but I just thought I'd chuck it in here since I was already investigating it.

**Comment by Rasgnarok** [comment]
We will investigate, but I think this is related to https://github.com/ObliqueNET/Server/issues/878 , and not actually intended. If it's the case, this ticket can be closed after we check the place out.
