### ISSUE TITLE
Pokemon spawning like crazy

### ISSUE THREAD

**Issue by Doughnutchickenishot** [ObliqueNET/Server#958]
Pokemon after a bit of standing around start to over spawn and get crowded 
https://i.gyazo.com/thumb/1200/fc201eacfb87bab01b63a1437b4ba077-png.jpg
https://cdn.discordapp.com/attachments/151095626916954113/800051124705951754/unknown.png

**Comment by Rasgnarok** [comment]
50=["po fly 0.3",
       "po ground 0.8",
       "po underground 0.0",
       "po chunk 0.8",
       "po surf 0.4",
       "po entity 50",
       "po range 15",
       "po sf 50"
     ]
     
New optimizing config should prevent the wild spawning of flying entities whenever there's more to spawn elsewhere. Closes the ticket.
