### ISSUE TITLE
Quest 'Imprisoned' Stage 2 Hint bugged

### ISSUE THREAD

**Issue by RudolfShmitler** [ObliqueNET/Server#959]
The hint for stage 2 of 'Imprisoned' doesn't display properly, the riddle is cut off as shown in the screenshot below. 
![image](https://user-images.githubusercontent.com/55514946/104829385-599b0580-58c7-11eb-9ddf-b545d1dde3f8.png)

**Comment by Rasgnarok** [comment]
Fixed, there shouldn't be a prefix to the riddle itself. The riddle IS the hint. Fix applied.
