### ISSUE TITLE
Feature Suggestion | Villagers.

### ISSUE THREAD

**Issue by MJDeveloping** [ObliqueNET/Server#962]
When I decided to come back and play some more Pixelmon, I initially searched for "1.16.4 Pixelmon" and very quickly discovered that Pixelmon was still on 1.12.2... as a result, I took a peek at the Pixelmondiscord and discovered that they mentioned that creating a 1.15+ version was on the 2021 roadmap.. 

if that does happen, 1.14 was the "Village and Pillage" update. At that point, villagers became incredibly useful for survival players. If you want some ideas of how useful they'll be, even in Pixelmon, let me know... I don't want to make this issue an essay though, so I'll leave it for now :D

But basically: if we do get a 1.15+ Pixelmon, I'd love for villagers to be implemented... It will remain balanced too since zombies don't seem to spawn in Heill from what I've seen, the broken aspect of villagers, which is to say "zombie curing" them, isn't possible. 

The main downfall is that a map reset might be needed... but seeing as the whole state of the economy would likely change with the update, I think that's worth it. If we get upgraded to 1.16.4, it will most definitely be worth it. 1.12 and 1.16 are played very differently to each other after all- it's practically a whole new game.

**Comment by fatyg5** [comment]
Here's the issue with this suggestion, which is why I'd direct you to specifically send this to the Pixelmon forums. Pixelmon unfortunately overwrites the Minecraft Villager entity. Even when we spawn in minecraft villagers they become Pixelmon villagers. Even if we wanted to I doubt we could add villagers due to this coding decision. For that reason I suggest you make a post on the Pixelmon forums suggestion page for this idea!

**Comment by Vohras2** [comment]
Also, our server does have zombie mobs in Heill, so you could cure them.

**Comment by MJDeveloping** [comment]
> 
> 
> Here's the issue with this suggestion, which is why I'd direct you to specifically send this to the Pixelmon forums. Pixelmon unfortunately overwrites the Minecraft Villager entity. Even when we spawn in minecraft villagers they become Pixelmon villagers. Even if we wanted to I doubt we could add villagers due to this coding decision. For that reason I suggest you make a post on the Pixelmon forums suggestion page for this idea!

I did do my research into this beforehand :D In the pixelmon config, on line 443 there is a toggle for that behaviour! I also tested it and observed that shopkeepers, healer npcs, trainer npcs are still around. it's only the dialogue NPCs that stay as villagers.




> 
> 
> Also, our server does have zombie mobs in Heill, so you could cure them.

In regards to this... I've not seen any zombies despite staying there for a good hour, only passive mobs and ghasts. But assuming I'm just very unlucky, according to the test I just did, while said config option is active, healed villagers just turn back into Pixelmon npcs. At least in single player.

**Comment by Vohras2** [comment]
That's because Heill is currently bugged so mobs aren't spawning properly. When it's fixed, hostile mobs will spawn all across the land.

**Comment by MJDeveloping** [comment]
> 
> 
> That's because Heill is currently bugged so mobs aren't spawning properly. When it's fixed, hostile mobs will spawn all across the land. Also, dialogue npcs are a rather big requirement for our server, since we use them quite a lot for our quests.

I see.. it's a shame that Heill is currently bugged.

As for the dialogue npcs being essential- I don't mind working on a mod that allows villagers to have dialogue boxes. purely server-side custom GUIs have been possible for a long time after all. I find that it would be a massive pity to lose out on villagers due to being reliant on dialogue npcs :)

**Comment by Rasgnarok** [comment]
Closing, since it's factually impossible to have vanilla villagers and Pixelmon NPCs. Maybe a suggestion for PixelmonMod, https://pixelmonmod.com/viewforum.php?f=146 .

**Comment by MJDeveloping** [comment]
Reopening- It's already possible. As mentioned earlier- Line 443 of the Pixelmon.hocon. This is set to "false" by default. Upon setting to "true" any freshly generated villages (Or villagers bred in a breeder) will not turn into NPCs.

![idea64_Ssh5tMqk3p](https://user-images.githubusercontent.com/63269417/107107917-1d0a5c00-682c-11eb-981d-d62975f2d524.png)
