### ISSUE TITLE
Unmarked Quest Giver

### ISSUE THREAD

**Issue by BunkerMonk** [ObliqueNET/Server#966]
The NPC that gives the quest "On the Road Again" does not have the QG title above his head. The only way for a player to know he's a quest giver is getting suspicious that there's a small farm in the middle of nowhere and trying to talk to him. Rough Coordinates can be seen in the photo.

![2021-01-24_09 18 36](https://user-images.githubusercontent.com/69098930/105633393-47204f00-5e26-11eb-9ba5-7ea93243d740.png)

**Comment by starwarschamp4** [comment]
Already added
