### ISSUE TITLE
Previous purchases

### ISSUE THREAD

**Issue by blackmamba856** [ObliqueNET/Server#967]
Hello, I played on this server a year or two ago and I purchased kits and ranks at that time. When I relogged recently I noticed all my purchased things are gone. Just wondering if there is anything that can be done. 

Thanks

**Comment by Rasgnarok** [comment]
Hi! Can you please DM me on Discord with your username at the time, your username now, and your purchase email? I can walk you through our store policy, as you do keep your rank. Your purchase might be so old though, that our transfer on the last reset never picked it up.

Discord: https://discord.gg/B3XcYcR
Discord username to message: @Rasgnarok#6969

**Comment by Rasgnarok** [comment]
Resolved, rank was re-applied.
