### ISSUE TITLE
[BUG] Quest Rewards | Murkrow Invasion

### ISSUE THREAD

**Issue by MJDeveloping** [ObliqueNET/Server#968]
I was doing the quest 'Murkrow Invasion'. I dunno if this is unique to Murkrow Invasion or whether it's every quest...

```
You scared off enough Murkrow to please the farmer.
You have received: 10!
```

10.... what? Quest points? money? some item I already had some of? I don't know... I think it's probably meant to be pokeballs though, since quest book says it was 2 QPs rewarded and 10 pokedollars seems far too little :D

**Comment by Vohras2** [comment]
You got the loot, and yes, it was pokeballs. It just doesn't say it correctly.

**Comment by MJDeveloping** [comment]
Sorry for the lack of clarity, the bug I was referring to was it failing to display the reward properly :)

**Comment by PrimalCyndaquil** [comment]
This is, as far as I know, a bug common to all quests whenever items are given using the give-item trigger.
