### ISSUE TITLE
pixelmon refresh

### ISSUE THREAD

**Issue by carrdala** [ObliqueNET/Server#971]
i am wondering if i could get a refresh on the server as i just took over the account carr_dala aka Warsong which has another account so please get back to me either here or in game

**Comment by Rasgnarok** [comment]
Can I get some proof of the OG owner relinquishing his account? As far as I know, Mojang doesn't offer a transfer

**Comment by Vohras2** [comment]
Going to close this, as it's nearing a month old. Reopen if you can provide what Ras requested.
