### ISSUE TITLE
Legends spawning despite changelog. 

### ISSUE THREAD

**Issue by Vetrnn** [ObliqueNET/Server#972]
So about 4 days ago, changelog updated. One of the fixes was:
![image](https://user-images.githubusercontent.com/78167145/106175040-a30b1080-6163-11eb-9662-4612b0215f09.png)

This morning, despite that fix, a Tapu Koko appeared at spawn. We were not sure at first, but it turns out that somebody lost while fighting the Tapu, so it was gone before I could personally see it. Despite that, RapidFlames saw the player fighting with the tapu, and it was indeed at spawn.  
![image](https://user-images.githubusercontent.com/78167145/106176880-d77fcc00-6165-11eb-8df3-6b1c19a5d8ca.png)

![Screenshot 2021-01-28 122842](https://user-images.githubusercontent.com/78167145/106175671-6390f400-6164-11eb-8aea-03c72ad2527e.png)

Thanks for taking the time to read this
Vet

**Comment by Vohras2** [comment]
Should now be fixed.
