### ISSUE TITLE
Drericeto ban appeal

### ISSUE THREAD

**Issue by Drericeto321** [ObliqueNET/Server#973]
Yo unban me its been like half a year. im sorry. i grew up and stopped being a dick.

**Comment by ElementalMP** [comment]
I don't see how this was any different to the last time you promised something. You said you were sorry, then you said it was your brother, then you admitted to it and said you regret it, then told me to kill myself, and I quote "Suck my fat fucking cock". You know as well as I do 6 months is not enough to redeem that, and you have proven to me and everyone else that your word has little to no value when it comes to sincerity. 
I think you know where this is going.
Your application is declined. Further posts outside this ticket will result in action taken against your GitHub account.
Enjoy your day! :)

**Comment by Drericeto321** [comment]
ill suck your dick for unban daddy

**Comment by AdmiralCrunch56** [comment]
Natalie Portman is the reason I work out. I have this fantasy where we start talking at the Vanity Fair Oscars party bar. We exchange a few pleasantries. She asks what I do. I say I loved her in New Girl. She laughs. I get my drink.

"Well, see ya," I say and walk away. I've got her attention now. How many guys voluntarily leave a conversation with Natalie Portman? She touches her neck as she watches me leave.

Later, as the night's dragged on and the coterie of gorgeous narcissists grows increasingly loose, she finds me on the balcony, my bowtie undone, smoking a cigarette.

"Got a spare?" she asks.

"What's in it for me?" I say as I hand her one of my little white ladies. She smiles.

"Conversation with me, duh."

I laugh.

"What's so funny?" she protests.

"Nothing, nothing... It's just... don't you grow tired of the egos?"

"You get used to it," she says, lighting her cigarette and handing me back the lighter.

"What would you do if you weren't an actress?" I ask.

"Teaching, I think."

"And if I was your student, what would I be learning?"

"Discipline," she says quickly, looking up into my eyes, before changing the subject. "Where are you from?"

"Bermuda," I say.

"Oh wow. That's lovely."

"It's ok," I admit. "Not everything is to my liking."

"What could possibly be not to your liking in Bermuda?" she inquires.

"I don't like sand," I tell her. "It's coarse and rough and irritating and it gets everywhere."

**Comment by Drericeto321** [comment]
whats this supposed to mean

**Comment by AdmiralCrunch56** [comment]
It means that we no longer care so I can use copypastas in an attempt to be funny.

**Comment by Drericeto321** [comment]
fuck you
