### ISSUE TITLE
Nyctophobia missing from /quests

### ISSUE THREAD

**Issue by CptTCov** [ObliqueNET/Server#974]
Someone asked about Nyctophobia being missing from quest book so I looked, and it was indeed gone. Wanted to toss this here. 
![Screenshot_134](https://user-images.githubusercontent.com/78214029/106277630-4a348a00-61ee-11eb-9821-96d7c9192d66.png)

**Comment by menno516** [comment]
This quest is currently down since we have a new old ione, It is currently being debugged again to check if everything is ok.
It should be back soon.

**Comment by PrimalCyndaquil** [comment]
Now that all of the Ione quests have moved, this issue should be fixed. Closing!
