### ISSUE TITLE
Unable to kick players from town

### ISSUE THREAD

**Issue by SpermitTheFrog** [ObliqueNET/Server#975]
I've tried to kick multiple members from my town (Stole from me, innapropriate usernames etc.) and upon using the command /town kick [username] I am given an error message saying Invalid user, I don't know if the issue only prevents kicking players that are offline, or all players.
![image](https://user-images.githubusercontent.com/75085971/106364698-f64faf80-636b-11eb-89cb-da2abca09e04.png)
![image](https://user-images.githubusercontent.com/75085971/106364709-0a93ac80-636c-11eb-8ed2-701310b7ff64.png)
![image](https://user-images.githubusercontent.com/75085971/106364726-25662100-636c-11eb-842d-3052f6381fe9.png)
![image](https://user-images.githubusercontent.com/75085971/106364731-331ba680-636c-11eb-916f-03fb177aaf1e.png)

**Comment by Hiroku** [comment]
Next time the server restarts there should be a fix for this. It will need to be re-tested at that time.

**Comment by Vohras2** [comment]
Closing this. If you still have this issue, please reopen this ticket.
