### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by AtlyBalty** [ObliqueNET/Server#976]
MC name: AltyBalty (old Unklet1)
Hello,

Today I got banned of the reason: "Reward glitching and xray" 

Reward glitching: This is a common issue for me, because me and my brother are always playing the same games together. So when he wanted to join the pixelmon server aswell, I invited him to the server so I could get extra rewards. From staff perspective I understand that it looks weird, but unfortunately I couldn't explain that I was playing with my brother. I didn't know this counted as reward glitching and I wouldn't mind to give the rewards back. 
More info:
My brother has a really difficult study and only had this week to play with me. So thats why he gave me all his stuff because he wasn't gonna play for a long time. He only helped me with getting the stuff I needed to move further in my leveling. 

Xray: (I edited this party as I want to answer truthfully)

I was banned today for using Xray, and I admit I was using the mod. I wish to apologize for it and ask for a second chance since it was my first offense. In the rest of my appeal I will go into detail my motives of using Xray, how long I have used Xray, how much money I made using Xray, apologize for using it, and ask for forgiveness.

My motives for using Xray were originally to test it out and see what the hype was about, and then after I knew that I would stop using it. But after testing it I discovered the greatness of this modification. I realized I could make money using the mod. I realized I could have all the iron, diamonds, redstone, gold and other ores I could ever need, then sell what was left for profit. What started out as a test turned into an income that I enjoyed. My original intent was not to make profit.

I have been using Xray since about 2 days ago total, I estimate my profit to be about $15000, but I have more ore that I got by using this mod in chests around my houses. I believe I have about 1 stack of diamonds less than half a stack of gold, 14 and 1-2 stacks of coal in chests, furnaces, or my inventory. I do not know anything for sure, nor can I check because I cannot access the server anymore.

I wish to apologize for using this mod. Right from the start I knew it was illegal, but I wanted to test it. After testing it I did not stop using it, which was wrong of me. I do not believe I profited as much as other offenders of my type. Even so, what I did was wrong and it harmed the economy to a small extent, but it was still wrong.

Please forgive my offense. I will never use this mod on your server again, never. Not to any extent. If I do use this mod again I will accept any punishment that is served for two reasons. I would be lying to you if I continued using this mod after you gave me a second chance and I wouldn’t deserve a third chance if I did this again.

As you are the administrators of Oblique, you have the decision to do what you want for my offense of using Xray. If you want to give me a second chance on the server, I thank you. If you decide to not give me a second chance, I will leave the site alone and it will be as if I were never there. Please note, I tried writing this letter professionally and I hope you take it as such.

Thank you for understanding.

If you have any questsions please let me know.

**Comment by Katadreme** [comment]
I believe you are genuine in your apology, whats troubling is how you knew it was wrong / against rules to use such mods and used them anyway. Whats also troubling is how you say 'If I do use this mod again'. Makes it sound like you do plan on using it again. I hope not. I will give you a second chance. Please delete or disable any mods / xray mods you have before you log in next. I have also confiscated most of the things you obtained through xray and the sum of money. If we find you are using any mods again, you will be banned immediately, and like you say, you won't get a third chance.
