### ISSUE TITLE
Apricorn Trees not growing properly

### ISSUE THREAD

**Issue by Epix120** [ObliqueNET/Server#977]
I have an apricorn tree farm, and some of them refuse to grow, and do so in odd patterns. Force-growing doesn't fix this either, and it seems buggy to me.

![whatub](https://user-images.githubusercontent.com/75963693/106391998-b3b2c500-63b5-11eb-99dc-1627e8702235.png)

**Comment by menno516** [comment]
you are missing light sources. 
place a sea lantern above 1 of the middle parts and you will notice that they grow.

**Comment by Epix120** [comment]
ok so im just bad ty
