### ISSUE TITLE
Mach Bike and Broken Signs

### ISSUE THREAD

**Issue by MissElyri** [ObliqueNET/Server#979]
I've found something interesting with the new Bikes (Mach Bike in this situation) is causing the meme signs to break when players collide with it.  I didn't know if it was already noted somewhere but I wanted to bring it up

When it was brought to my attention, he described it as "When the model of the mach bike collides with the meme sign, it has an adverse reaction, and causes it to be removed from the wall."  (Players words exactly.)

The same happens when you ride a bike into a wall, you suffocate. So the hitboxes might be a little wonky I guess.

Edited to include: Tested on a single player world. Does the same thing. Riding a bike along the wall picture frames are on, causes them to pop off
![memebroken](https://user-images.githubusercontent.com/78369601/106482699-b37cfd00-647b-11eb-8588-33ee513f59f7.png)

**Comment by Rasgnarok** [comment]
This is technically a Pixelmon bug, since the Mach bike is colliding with item frames. Can you bump it to https://pixelmonmod.com/tracker.php?p=2? On our end, all we can do is fix and place down invisible blocks to prevent it from happening. I'll forward to builders.

**Comment by Vohras2** [comment]
Closing this as I assume (hope) that it's been reported to Pixelmon. Our builders are working on designs to hopefully prevent in game.
