### ISSUE TITLE
Quest: "Just Keep Smithing" showing objective wrong

### ISSUE THREAD

**Issue by menno516** [ObliqueNET/Server#980]
on stage 4 of "Just Keep Smithing" the quest book will show you 2 times "A description"
This stage is when you fight a boss pokemon for your quest.

![image](https://user-images.githubusercontent.com/63118334/106630856-7ea49f00-657c-11eb-8691-693f6da6fceb.png)

**Comment by PrimalCyndaquil** [comment]
Though the player isn't meant to be able to see this stage (seeing it in the first place is likely related to #956), I've added "Defeat Salamence" and "Lose to Salamence" to these descriptions so QDs assisting players know what's going on and players who need help can more accurately convey what's happened.
