### ISSUE TITLE
Quest "On The Road Again" not taking all the items

### ISSUE THREAD

**Issue by menno516** [ObliqueNET/Server#981]
For the quest in the beginning you are getting 5 wheat, 3 melons and 5 pink wool, you need to deliver this to the warehouse in agni to recieve a bag of money.

When handing over the items the pc only takes 5 wheat, 3 melons and 3 pink wool instead of 5. (stage 10)

**Comment by PrimalCyndaquil** [comment]
Corrected from 3 wool to 5 wool as proper.
