### ISSUE TITLE
Question Issues (A Blank Mind and Porygon's conundrum)

### ISSUE THREAD

**Issue by ZipperMan500** [ObliqueNET/Server#982]
Hi so I have a similiar isssue on both of these quest after I have acquired the pc for so I am at 25%.  The quest book says to talk to Suzanne I did and it brings up her normal greet dialogue if you're not doing the quest. And a blanked I have the previous items from the previous steps and the onix. And the quest completition precentage is 50% and it says talk to Miner Joe. When I talk to Joe with the Onix and Items in my inventory the quest doesn't update and it gives me his non-quest greet dialogue.

**Comment by menno516** [comment]
for the quest with porygon: Grab a new set of the pc materials and talk to her.
The stage that you were on wanted to materials and than talk to the npc again, After this she wants the pc in crafted form.

For A Blank Mind: Make sure you have the onix in your party + all previous items, these include: 10 carrots, 5 beef, 5 apples and 1 fresh water.

**Comment by PrimalCyndaquil** [comment]
Both of theses issues were simple misunderstandings, no bugs here thankfully.
