### ISSUE TITLE
Banned for Additional Mods when using the same mods as others

### ISSUE THREAD

**Issue by AtlyBalty** [ObliqueNET/Server#983]
Banned for using additionals mods while those mods are used by other ingame players aswell.
MC name: AltyBalty

**Comment by AtlyBalty** [comment]
![bhjgi](https://user-images.githubusercontent.com/78279431/106905126-4035ee00-66fc-11eb-9213-495dd24faa80.PNG)

**Comment by AtlyBalty** [comment]
I can even show you that my mod files has been changed

**Comment by AtlyBalty** [comment]
![image](https://user-images.githubusercontent.com/78279431/106906396-6b6d0d00-66fd-11eb-9379-5f3c736f8a81.png)

**Comment by Katadreme** [comment]
I apologise for the delay in responding. Anyway, you were banned again as we had found you had 'Auto-fish' mod enabled after you were unbanned. The agreement of your un-ban was that you would disable / delete any other mods upon your unbanning. Though you have provided evidence of your mods folder, we can easily say that you removed that certain mod before showing this folder.

**Comment by AtlyBalty** [comment]
You can count the mods and check that with the modcount when I joined the server

**Comment by AtlyBalty** [comment]
1-2 was before my unban, and the last time I edited this folder is alos 24-1

![image](https://user-images.githubusercontent.com/78279431/107743144-a6300000-6d10-11eb-86e3-b2d3dc6086d1.png)

**Comment by Katadreme** [comment]
Was meant to post this too: 
![Screen Shot 2021-02-12 at 8 03 01 pm](https://user-images.githubusercontent.com/50907133/107748603-6f3c0780-6d6d-11eb-9f79-9d58f898967f.png)
Here we have 11, and in your screenshots show 9.

**Comment by AtlyBalty** [comment]
I had 9 not 11 I am pretty sure.

**Comment by Katadreme** [comment]
I apologise for the delay in responding again. After looking into this ban again, I've learnt that I was reading the mod login incorrectly, so I will unban you. But like I've stated before and really hope this isn't an issue again, please disable any server-rule breaking mods whenever you log in. Do consider yourself lucky, most people don't get 2 unbans.
