### ISSUE TITLE
Legendary Quest rewards not given

### ISSUE THREAD

**Issue by SpermitTheFrog** [ObliqueNET/Server#984]
Completed Quest: Project TALLOW, recieved fatal error and crashed during final step attempting to talk to quest NPC, quest was finished and shows up as finished in quest book, but was not given $10k  and cherrish balls as the quest completion reward 
![image](https://user-images.githubusercontent.com/75085971/107024397-f542d600-67e2-11eb-8c2f-addd72951635.png)

**Comment by PrimalCyndaquil** [comment]
That is some very poor luck. It is likely related to the issue #956 , where triggers do not fire properly if a player is offline when they are meant to. This will have to be refunded by a lead or similar. DM Me on discord if you want as I'll likely be on later today and can refund it then.
