### ISSUE TITLE
Plot issues

### ISSUE THREAD

**Issue by warsong85** [ObliqueNET/Server#985]
I and the ppl in my village are all mayors so we all have the same ability. Last night we had somone join our town and we have been made aware of this issue. Ppl in my town/village are experiencing this same issue. We cannot create, claim, delete, or edit plots that we had set up for new joins. I tried to figure it out just now and still having this issue

**Comment by Hiroku** [comment]
I don't understand what's being reported. You and the people in your village are all mayors? But there can only be 1 mayor. I also don't know what you used to setup the plots for new residents. Do you know the way you used the plot create command?

**Comment by warsong85** [comment]
Obviously I do understand how to make a plot. As I said before the commands to edit the price, placement, to buy, and to delete the plot are not working correctly. For example if I stand inside of a plot that I had made before this issue started and tell it /plot delete is says there is no plot there but when I walk onto the said location it clearly states plot and the price. I just had somone join my town and he tried to buy one of the premade plots and it told him that there was no plot but again when you walk into the location it says plot and its price. When I try to edit the price of the locations that I made 4 days ago it says again the plot does not exist but once again if you walk onto the location it says plot and the price.
As for multiple mayors I just gave them administrative abilities. They should by right have the same powers and abilitys as I do so I call them co mayors because we work as a unit

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by warsong85** [comment]
Also if I try to make a new plot now it tells me that the location is overlapping another. It should not be because I have roads deciding the spaces so that should not be happening

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Rasgnarok** [comment]
Can this one be closed, @Hiroku ?

**Comment by Vohras2** [comment]
Closing this as old, and probably resolved.
