### ISSUE TITLE
Ore placement blocking some ores

### ISSUE THREAD

**Issue by menno516** [ObliqueNET/Server#986]
So today me, TVX and bunker were talking about the ores and found out that you can place certain ores while others are possible.
So I dont know if this should be possible or not. (This is only on the server, on single player it all works normal)
A list below will show the ore and yes or no behind it if its possible or not.
gold-no
iron-no
bauxite-no
silicon-no

coal-yes
lapis-yes
diamond-yes
redstone-yes
emerald-yes
nether quartz-yes
thunderstone-yes
leafstone-yes
waterstone-yes
firestone-yes
dusk/dawn stone-yes
sunstone-yes
ruby-yes
saphire-yes
amethyst-yes
crystal-yes

**Comment by Vohras2** [comment]
This is as intended. If you could place iron/gold ore then you could infinitely farm mining rpg levels.
