### ISSUE TITLE
Pixelmon Oblique

### ISSUE THREAD

**Issue by Fatherbosh09** [ObliqueNET/Server#987]
Hey I can't connect to the server for some reason. Its says disconnected, times up, or a weird text. It looks like a an server address. People on the discord try to help me like The Kung Of Sweden and PJ Lesure. Its not my internet because I can join other server butIt's just your's server. Pls help me, we try everything. My account is Father_bosh09 on minecraft and my discord is father_bosh
#8762.

**Comment by xztq** [comment]
I got banned for stealing from a unclaimed base when I didn’t so can I get unbanned pls

**Comment by CptTCov** [comment]
xztq you should make a new message by hitting "New issue" on the right side under Watch - Star - Fork

**Comment by Vohras2** [comment]
Closing as I think you were able to join? Re-open if this is still an issue.
