### ISSUE TITLE
Voting issue

### ISSUE THREAD

**Issue by CptTCov** [ObliqueNET/Server#989]
A handful of players were asking if voting was broken so I went to check what showed up.
Error 500 Server error
![Screenshot_47](https://user-images.githubusercontent.com/78214029/107157754-c8a1d200-693a-11eb-8f2c-0260f418f8c2.png)

**Comment by Vohras2** [comment]
Closing as seems to be error with their website? Voting has been working for plenty of others. Re-open if you still have issues.
