### ISSUE TITLE
[Suggestion] Entry Zones that disable flying

### ISSUE THREAD

**Issue by BunkerMonk** [ObliqueNET/Server#991]
Could we have a No Flying Zone system for the quest builder?

Basically, it would be an entry zone that checks the players that touch it to see if they have /fly toggled on. 
If they do, toggle it off so they fall to the nearest ground.
If they don't, the zone will do nothing.

The purpose of this would be to craft parkour areas where players can't cheat without having to alter the players' permissions. The current system requires either barrier blocks (which players can fly around with some difficulty), Disable perms, which really is a terrible can of worms from Primal's description of it, and entry zones that catch the stupid ones who fly to high (doesn't stop the smart ones who fly where they are supposed to jump through.)

**Comment by Vohras2** [comment]
Closing to merge with https://github.com/ObliqueNET/Server/issues/1113
