### ISSUE TITLE
[Quest] "On the Road Again."

### ISSUE THREAD

**Issue by BunkerMonk** [ObliqueNET/Server#993]
I got all the way to the warehouse, and the quest let me in. The next step is to talk to Tony in the back, but nothing happens. I believe this might be due to me missing the items the quest tried to give me at the very beginning. Said items auto-deleted themselves because I already had a full inventory from doing another quest. I attempted to talk to the farmer but he gives no replacements for them and I am thus stuck.

**Comment by PrimalCyndaquil** [comment]
A failsafe mechanism has been added to ensure that players can still progress if they lose these items.
