### ISSUE TITLE
Pokemon switching Genders

### ISSUE THREAD

**Issue by Varvarus1** [ObliqueNET/Server#994]
I've had two pokemon switch genders when I log in. One was my Luxray in my party who when I logged in the next day changed from a boy to a girl. The other was my Swinub I was breeding in my ranch which switch from a girl to a boy.

**Comment by Rasgnarok** [comment]
This sounds like Pixelmon storage issues at its finest. I recommend either reporting to Pixelmon, or simply having us fix them by resetting the correct gender as it happens. Please report Pixelmon bugs to https://www.pixelmonmod.com/tracker.php?p=2 .
