### ISSUE TITLE
Got banned

### ISSUE THREAD

**Issue by xztq** [ObliqueNET/Server#996]
I got banned from stealing from a unclaimed base when I didn’t

**Comment by xztq** [comment]
Can any mods help me Bc I haven’t stole from a unclaimed base only looked in a chest Bc I just wanted to see what they had

**Comment by Katadreme** [comment]
You would be mistaken. Heres the log:
![Screen_Shot_2021-02-10_at_5 23 55_PM](https://user-images.githubusercontent.com/50907133/107729409-f1fc9c80-6d44-11eb-88f8-552f4c8b366e.png)

Either way, you were temp-banned for this, and your other offences. So I would suggest waiting out your temporary ban.

**Comment by xztq** [comment]
But that was from my chest in my house after joining my friends town

**Comment by xztq** [comment]
Nvm I’ll just wait
