### ISSUE TITLE
SPLEEF ISSUE + ban appeal

### ISSUE THREAD

**Issue by JackDimonds** [ObliqueNET/Server#998]
I cant scroll up to show the issue at this time

I joined a spleef, did the event. No issue

I teleported out of the location and got my stuff, no issue.

I was put in the event when it started without joining the event. Me and about 3/4 other people "was knocked out" right as the event started. I personally got coal instead of a shovel, I do believe a few other people got coal aswell.
![Screenshot 2021-02-11 154320](https://user-images.githubusercontent.com/77371567/107696394-e5fad700-6c7f-11eb-903c-3fc4b59daa3a.png)

When i said something about this issue in chat, I was just told I was wrong then banned.

The whole spleef issue I understand, but in this event I was not warned or mentioned beyond "saying its broken doesnt mean its bad"

**Comment by JackDimonds** [comment]
I was typing the appeal when I got banned as a side note. 

The event part of that I am noting is idc about my inventory except I had a moonstone god shovel which is the only thing

**Comment by JackDimonds** [comment]
![Screenshot 2021-02-11 154933](https://user-images.githubusercontent.com/77371567/107697071-c2845c00-6c80-11eb-8a8c-de020630e490.png)
Here is the only interaction between staff and I during this event other than me saying that I just lost my stuff

**Comment by Katadreme** [comment]
To address the spleef issue, I checked server-logs to see if there was commands used that made you join somehow and couldn't find anything, so am very confused as to why it made it tped you when the game started. And all players that join who join the spleef game but don't /confirm it will automatically lose. 

To address your ban, you have tested staff and event runners countless times, and be given more warnings than most get. Needing to be warned at different events multiple times is an issue, which here has resulted in your ban. And frankly, you've had your chances. Your appeal has been denied.
